<?php
//==============================================================================
//===   giftpreparation.php                         
//===   Autogenerated by Druid from MySQL db Build:6
//==============================================================================

include_once("druid_interfaces.php");

class huh_giftpreparation implements  model , loadableModel, saveableModel, tableSchema 
{
   // These constants hold the sizes the fields in this table in the database.
   const GIFTPREPARATIONID_SIZE = 11; //INTEGER
   const TIMESTAMPCREATED_SIZE = 21; //TIMESTAMP
   const TIMESTAMPMODIFIED_SIZE = 21; //TIMESTAMP
   const VERSION_SIZE         = 11; //INTEGER
   const DESCRIPTIONOFMATERIAL_SIZE = 255; //LONGVARCHAR
   const INCOMMENTS_SIZE      = 255; //LONGVARCHAR
   const ITEMCOUNT_SIZE       = 11; //INTEGER
   const NONSPECIMENCOUNT_SIZE = 11; //INTEGER
   const OUTCOMMENTS_SIZE     = 255; //LONGVARCHAR
   const RECEIVEDCOMMENTS_SIZE = 255; //LONGVARCHAR
   const TYPECOUNT_SIZE       = 11; //INTEGER
   const MODIFIEDBYAGENTID_SIZE = 11; //INTEGER
   const GIFTID_SIZE          = 11; //INTEGER
   const DISCIPLINEID_SIZE    = 11; //INTEGER
   const PREPARATIONID_SIZE   = 11; //INTEGER
   const CREATEDBYAGENTID_SIZE = 11; //INTEGER
    // These constants hold the field names of the table in the database. 
   const GIFTPREPARATIONID = 'GiftPreparationID';
   const TIMESTAMPCREATED  = 'TimestampCreated';
   const TIMESTAMPMODIFIED = 'TimestampModified';
   const VERSION           = 'Version';
   const DESCRIPTIONOFMATERIAL = 'DescriptionOfMaterial';
   const INCOMMENTS        = 'InComments';
   const ITEMCOUNT         = 'ItemCount';
   const NONSPECIMENCOUNT  = 'NonSpecimenCount';
   const OUTCOMMENTS       = 'OutComments';
   const RECEIVEDCOMMENTS  = 'ReceivedComments';
   const TYPECOUNT         = 'TypeCount';
   const MODIFIEDBYAGENTID = 'ModifiedByAgentID';
   const GIFTID            = 'GiftID';
   const DISCIPLINEID      = 'DisciplineID';
   const PREPARATIONID     = 'PreparationID';
   const CREATEDBYAGENTID  = 'CreatedByAgentID';

   //---------------------------------------------------------------------------

   // interface tableSchema implementation
   // schemaPK returns array of primary key field names
   public function schemaPK() {
       return $this->primaryKeyArray;
   } 
   // schemaHaveDistinct returns array of field names for which selectDistinct{fieldname} methods are available.
   public function schemaHaveDistinct() {
       return $this->selectDistinctFieldsArray;
   } 
   // schemaFields returns array of all field names
   public function schemaFields() { 
       return $this->allFieldsArray;
   } 
/*  Example sanitized retrieval of variable matching object variables from $_GET 
/*  Customize these to limit each variable to narrowest possible set of known good values. 

  $GiftPreparationID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['GiftPreparationID']), 0, 11);
  $TimestampCreated = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampCreated']), 0, 21);
  $TimestampModified = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampModified']), 0, 21);
  $Version = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Version']), 0, 11);
  $DescriptionOfMaterial = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['DescriptionOfMaterial']), 0, 255);
  $InComments = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['InComments']), 0, 255);
  $ItemCount = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ItemCount']), 0, 11);
  $NonSpecimenCount = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['NonSpecimenCount']), 0, 11);
  $OutComments = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['OutComments']), 0, 255);
  $ReceivedComments = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['ReceivedComments']), 0, 255);
  $TypeCount = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['TypeCount']), 0, 11);
  $ModifiedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ModifiedByAgentID']), 0, 11);
  $GiftID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['GiftID']), 0, 11);
  $DisciplineID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['DisciplineID']), 0, 11);
  $PreparationID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['PreparationID']), 0, 11);
  $CreatedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['CreatedByAgentID']), 0, 11);
*/

   //---------------------------------------------------------------------------

   private $GiftPreparationID; // PK INTEGER 
   private $TimestampCreated; // TIMESTAMP 
   private $TimestampModified; // TIMESTAMP 
   private $Version; // INTEGER 
   private $DescriptionOfMaterial; // LONGVARCHAR 
   private $InComments; // LONGVARCHAR 
   private $ItemCount; // INTEGER 
   private $NonSpecimenCount; // INTEGER 
   private $OutComments; // LONGVARCHAR 
   private $ReceivedComments; // LONGVARCHAR 
   private $TypeCount; // INTEGER 
   private $ModifiedByAgentID; // INTEGER 
   private $GiftID; // INTEGER 
   private $DisciplineID; // INTEGER 
   private $PreparationID; // INTEGER 
   private $CreatedByAgentID; // INTEGER 
   private $dirty;
   private $loaded;
   private $error;
   const FIELDLIST = ' GiftPreparationID, TimestampCreated, TimestampModified, Version, DescriptionOfMaterial, InComments, ItemCount, NonSpecimenCount, OutComments, ReceivedComments, TypeCount, ModifiedByAgentID, GiftID, DisciplineID, PreparationID, CreatedByAgentID, ';
   const PKFIELDLIST = ' GiftPreparationID, ';
   const NUMBER_OF_PRIMARY_KEYS = 1;
   private $primaryKeyArray = array( 1 => 'GiftPreparationID'  ) ;
   private $allFieldsArray = array( 0 => 'GiftPreparationID' , 1 => 'TimestampCreated' , 2 => 'TimestampModified' , 3 => 'Version' , 4 => 'DescriptionOfMaterial' , 5 => 'InComments' , 6 => 'ItemCount' , 7 => 'NonSpecimenCount' , 8 => 'OutComments' , 9 => 'ReceivedComments' , 10 => 'TypeCount' , 11 => 'ModifiedByAgentID' , 12 => 'GiftID' , 13 => 'DisciplineID' , 14 => 'PreparationID' , 15 => 'CreatedByAgentID'  ) ;
   private $selectDistinctFieldsArray = array( 11 => 'ModifiedByAgentID' , 12 => 'GiftID' , 13 => 'DisciplineID' , 14 => 'PreparationID' , 15 => 'CreatedByAgentID'  ) ;

   //---------------------------------------------------------------------------

   // constructor 
   function huh_giftpreparation(){
       $this->GiftPreparationID = NULL;
       $this->TimestampCreated = '';
       $this->TimestampModified = '';
       $this->Version = '';
       $this->DescriptionOfMaterial = '';
       $this->InComments = '';
       $this->ItemCount = '';
       $this->NonSpecimenCount = '';
       $this->OutComments = '';
       $this->ReceivedComments = '';
       $this->TypeCount = '';
       $this->ModifiedByAgentID = '';
       $this->GiftID = '';
       $this->DisciplineID = '';
       $this->PreparationID = '';
       $this->CreatedByAgentID = '';
       $this->dirty = false;
       $this->loaded = false;
       $this->error = '';
   }

   private function l_addslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = addslashes($value);
      }
      return $retval;
   }
   private function l_stripslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = stripslashes($value);
      }
      return $retval;
   }
   public function isDirty() {
       return $this->dirty;
   }
   public function isLoaded() {
       return $this->loaded;
   }
   public function errorMessage() {
       return $this->error;
   }

   //---------------------------------------------------------------------------

   public function keyValueSet($fieldname,$value) {
       $returnvalue = false;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='GiftPreparationID') { $returnvalue = $this->setGiftPreparationID($value); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->setTimestampCreated($value); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->setTimestampModified($value); } 
             if ($fieldname=='Version') { $returnvalue = $this->setVersion($value); } 
             if ($fieldname=='DescriptionOfMaterial') { $returnvalue = $this->setDescriptionOfMaterial($value); } 
             if ($fieldname=='InComments') { $returnvalue = $this->setInComments($value); } 
             if ($fieldname=='ItemCount') { $returnvalue = $this->setItemCount($value); } 
             if ($fieldname=='NonSpecimenCount') { $returnvalue = $this->setNonSpecimenCount($value); } 
             if ($fieldname=='OutComments') { $returnvalue = $this->setOutComments($value); } 
             if ($fieldname=='ReceivedComments') { $returnvalue = $this->setReceivedComments($value); } 
             if ($fieldname=='TypeCount') { $returnvalue = $this->setTypeCount($value); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->setModifiedByAgentID($value); } 
             if ($fieldname=='GiftID') { $returnvalue = $this->setGiftID($value); } 
             if ($fieldname=='DisciplineID') { $returnvalue = $this->setDisciplineID($value); } 
             if ($fieldname=='PreparationID') { $returnvalue = $this->setPreparationID($value); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->setCreatedByAgentID($value); } 
             $returnvalue = true;
          }
          catch (exception $e) { ;
              $returnvalue = false;
              throw new Exception('Field Set Error'.$e->getMessage()); 
          }
       } else { 
          throw new Exception('No Such field'); 
       }  
       return $returnvalue;
   }
   public function keyGet($fieldname) {
       $returnvalue = null;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='GiftPreparationID') { $returnvalue = $this->getGiftPreparationID(); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->getTimestampCreated(); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->getTimestampModified(); } 
             if ($fieldname=='Version') { $returnvalue = $this->getVersion(); } 
             if ($fieldname=='DescriptionOfMaterial') { $returnvalue = $this->getDescriptionOfMaterial(); } 
             if ($fieldname=='InComments') { $returnvalue = $this->getInComments(); } 
             if ($fieldname=='ItemCount') { $returnvalue = $this->getItemCount(); } 
             if ($fieldname=='NonSpecimenCount') { $returnvalue = $this->getNonSpecimenCount(); } 
             if ($fieldname=='OutComments') { $returnvalue = $this->getOutComments(); } 
             if ($fieldname=='ReceivedComments') { $returnvalue = $this->getReceivedComments(); } 
             if ($fieldname=='TypeCount') { $returnvalue = $this->getTypeCount(); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->getModifiedByAgentID(); } 
             if ($fieldname=='GiftID') { $returnvalue = $this->getGiftID(); } 
             if ($fieldname=='DisciplineID') { $returnvalue = $this->getDisciplineID(); } 
             if ($fieldname=='PreparationID') { $returnvalue = $this->getPreparationID(); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->getCreatedByAgentID(); } 
          }
          catch (exception $e) { ;
              $returnvalue = null;
          }
       }
       return $returnvalue;
   }
/*GiftPreparationID*/
   public function getGiftPreparationID() {
       if ($this->GiftPreparationID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->GiftPreparationID));
       }
   }
   public function setGiftPreparationID($GiftPreparationID) {
       if (strlen(preg_replace('/[^0-9]/','',$GiftPreparationID)) > huh_giftpreparation::GIFTPREPARATIONID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $GiftPreparationID = trim($GiftPreparationID);
       if (!ctype_digit(strval($GiftPreparationID)) && trim(strval($GiftPreparationID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->GiftPreparationID = $this->l_addslashes($GiftPreparationID);
       $this->dirty = true;
   }
/*TimestampCreated*/
   public function getTimestampCreated() {
       if ($this->TimestampCreated==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampCreated));
       }
   }
   public function setTimestampCreated($TimestampCreated) {
       if (strlen($TimestampCreated) > huh_giftpreparation::TIMESTAMPCREATED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampCreated = $this->l_addslashes($TimestampCreated);
       $this->dirty = true;
   }
/*TimestampModified*/
   public function getTimestampModified() {
       if ($this->TimestampModified==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampModified));
       }
   }
   public function setTimestampModified($TimestampModified) {
       if (strlen($TimestampModified) > huh_giftpreparation::TIMESTAMPMODIFIED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampModified = $this->l_addslashes($TimestampModified);
       $this->dirty = true;
   }
/*Version*/
   public function getVersion() {
       if ($this->Version==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Version));
       }
   }
   public function setVersion($Version) {
       if (strlen(preg_replace('/[^0-9]/','',$Version)) > huh_giftpreparation::VERSION_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Version = trim($Version);
       if (!ctype_digit(strval($Version)) && trim(strval($Version))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Version = $this->l_addslashes($Version);
       $this->dirty = true;
   }
/*DescriptionOfMaterial*/
   public function getDescriptionOfMaterial() {
       if ($this->DescriptionOfMaterial==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->DescriptionOfMaterial));
       }
   }
   public function setDescriptionOfMaterial($DescriptionOfMaterial) {
       if (strlen($DescriptionOfMaterial) > huh_giftpreparation::DESCRIPTIONOFMATERIAL_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->DescriptionOfMaterial = $this->l_addslashes($DescriptionOfMaterial);
       $this->dirty = true;
   }
/*InComments*/
   public function getInComments() {
       if ($this->InComments==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->InComments));
       }
   }
   public function setInComments($InComments) {
       if (strlen($InComments) > huh_giftpreparation::INCOMMENTS_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->InComments = $this->l_addslashes($InComments);
       $this->dirty = true;
   }
/*ItemCount*/
   public function getItemCount() {
       if ($this->ItemCount==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ItemCount));
       }
   }
   public function setItemCount($ItemCount) {
       if (strlen(preg_replace('/[^0-9]/','',$ItemCount)) > huh_giftpreparation::ITEMCOUNT_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ItemCount = trim($ItemCount);
       if (!ctype_digit(strval($ItemCount)) && trim(strval($ItemCount))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ItemCount = $this->l_addslashes($ItemCount);
       $this->dirty = true;
   }
/*NonSpecimenCount*/
   public function getNonSpecimenCount() {
       if ($this->NonSpecimenCount==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->NonSpecimenCount));
       }
   }
   public function setNonSpecimenCount($NonSpecimenCount) {
       if (strlen(preg_replace('/[^0-9]/','',$NonSpecimenCount)) > huh_giftpreparation::NONSPECIMENCOUNT_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $NonSpecimenCount = trim($NonSpecimenCount);
       if (!ctype_digit(strval($NonSpecimenCount)) && trim(strval($NonSpecimenCount))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->NonSpecimenCount = $this->l_addslashes($NonSpecimenCount);
       $this->dirty = true;
   }
/*OutComments*/
   public function getOutComments() {
       if ($this->OutComments==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->OutComments));
       }
   }
   public function setOutComments($OutComments) {
       if (strlen($OutComments) > huh_giftpreparation::OUTCOMMENTS_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->OutComments = $this->l_addslashes($OutComments);
       $this->dirty = true;
   }
/*ReceivedComments*/
   public function getReceivedComments() {
       if ($this->ReceivedComments==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ReceivedComments));
       }
   }
   public function setReceivedComments($ReceivedComments) {
       if (strlen($ReceivedComments) > huh_giftpreparation::RECEIVEDCOMMENTS_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->ReceivedComments = $this->l_addslashes($ReceivedComments);
       $this->dirty = true;
   }
/*TypeCount*/
   public function getTypeCount() {
       if ($this->TypeCount==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TypeCount));
       }
   }
   public function setTypeCount($TypeCount) {
       if (strlen(preg_replace('/[^0-9]/','',$TypeCount)) > huh_giftpreparation::TYPECOUNT_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $TypeCount = trim($TypeCount);
       if (!ctype_digit(strval($TypeCount)) && trim(strval($TypeCount))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->TypeCount = $this->l_addslashes($TypeCount);
       $this->dirty = true;
   }
/*ModifiedByAgentID*/
   public function getModifiedByAgentID() {
       if ($this->ModifiedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ModifiedByAgentID));
       }
   }
   public function setModifiedByAgentID($ModifiedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$ModifiedByAgentID)) > huh_giftpreparation::MODIFIEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ModifiedByAgentID = trim($ModifiedByAgentID);
       if (!ctype_digit(strval($ModifiedByAgentID)) && trim(strval($ModifiedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ModifiedByAgentID = $this->l_addslashes($ModifiedByAgentID);
       $this->dirty = true;
   }
/*GiftID*/
   public function getGiftID() {
       if ($this->GiftID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->GiftID));
       }
   }
   public function setGiftID($GiftID) {
       if (strlen(preg_replace('/[^0-9]/','',$GiftID)) > huh_giftpreparation::GIFTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $GiftID = trim($GiftID);
       if (!ctype_digit(strval($GiftID)) && trim(strval($GiftID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->GiftID = $this->l_addslashes($GiftID);
       $this->dirty = true;
   }
/*DisciplineID*/
   public function getDisciplineID() {
       if ($this->DisciplineID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->DisciplineID));
       }
   }
   public function setDisciplineID($DisciplineID) {
       if (strlen(preg_replace('/[^0-9]/','',$DisciplineID)) > huh_giftpreparation::DISCIPLINEID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $DisciplineID = trim($DisciplineID);
       if (!ctype_digit(strval($DisciplineID))) {
             throw new Exception("Value must be an integer");
       }
       $this->DisciplineID = $this->l_addslashes($DisciplineID);
       $this->dirty = true;
   }
/*PreparationID*/
   public function getPreparationID() {
       if ($this->PreparationID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->PreparationID));
       }
   }
   public function setPreparationID($PreparationID) {
       if (strlen(preg_replace('/[^0-9]/','',$PreparationID)) > huh_giftpreparation::PREPARATIONID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $PreparationID = trim($PreparationID);
       if (!ctype_digit(strval($PreparationID)) && trim(strval($PreparationID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->PreparationID = $this->l_addslashes($PreparationID);
       $this->dirty = true;
   }
/*CreatedByAgentID*/
   public function getCreatedByAgentID() {
       if ($this->CreatedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->CreatedByAgentID));
       }
   }
   public function setCreatedByAgentID($CreatedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$CreatedByAgentID)) > huh_giftpreparation::CREATEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $CreatedByAgentID = trim($CreatedByAgentID);
       if (!ctype_digit(strval($CreatedByAgentID)) && trim(strval($CreatedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->CreatedByAgentID = $this->l_addslashes($CreatedByAgentID);
       $this->dirty = true;
   }
   public function PK() { // get value of primary key 
        $returnvalue = '';
        $returnvalue .= $this->getGiftPreparationID();
        return $returnvalue;
   }
   public function PKArray() { // get name and value of primary key fields 
        $returnvalue = array();
        $returnvalue['GiftPreparationID'] = $this->getGiftPreparationID();
        return $returnvalue;
   }
   public function NumberOfPrimaryKeyFields() { // returns the number of primary key fields defined for this table 
        return 1;
   }

   // Constants holding the mysqli field type character (s,i,d) for each field
  const C_GiftPreparationIDMYSQLI_TYPE = 'i';
  const C_TimestampCreatedMYSQLI_TYPE = 's';
  const C_TimestampModifiedMYSQLI_TYPE = 's';
  const C_VersionMYSQLI_TYPE = 'i';
  const C_DescriptionOfMaterialMYSQLI_TYPE = 's';
  const C_InCommentsMYSQLI_TYPE = 's';
  const C_ItemCountMYSQLI_TYPE = 'i';
  const C_NonSpecimenCountMYSQLI_TYPE = 'i';
  const C_OutCommentsMYSQLI_TYPE = 's';
  const C_ReceivedCommentsMYSQLI_TYPE = 's';
  const C_TypeCountMYSQLI_TYPE = 'i';
  const C_ModifiedByAgentIDMYSQLI_TYPE = 'i';
  const C_GiftIDMYSQLI_TYPE = 'i';
  const C_DisciplineIDMYSQLI_TYPE = 'i';
  const C_PreparationIDMYSQLI_TYPE = 'i';
  const C_CreatedByAgentIDMYSQLI_TYPE = 'i';

   // function to obtain the mysqli field type character from a fieldname
   public function MySQLiFieldType($aFieldname) { 
      $retval = '';
      if ($aFieldname=='GiftPreparationID') { $retval = self::C_GiftPreparationIDMYSQLI_TYPE; }
      if ($aFieldname=='TimestampCreated') { $retval = self::C_TimestampCreatedMYSQLI_TYPE; }
      if ($aFieldname=='TimestampModified') { $retval = self::C_TimestampModifiedMYSQLI_TYPE; }
      if ($aFieldname=='Version') { $retval = self::C_VersionMYSQLI_TYPE; }
      if ($aFieldname=='DescriptionOfMaterial') { $retval = self::C_DescriptionOfMaterialMYSQLI_TYPE; }
      if ($aFieldname=='InComments') { $retval = self::C_InCommentsMYSQLI_TYPE; }
      if ($aFieldname=='ItemCount') { $retval = self::C_ItemCountMYSQLI_TYPE; }
      if ($aFieldname=='NonSpecimenCount') { $retval = self::C_NonSpecimenCountMYSQLI_TYPE; }
      if ($aFieldname=='OutComments') { $retval = self::C_OutCommentsMYSQLI_TYPE; }
      if ($aFieldname=='ReceivedComments') { $retval = self::C_ReceivedCommentsMYSQLI_TYPE; }
      if ($aFieldname=='TypeCount') { $retval = self::C_TypeCountMYSQLI_TYPE; }
      if ($aFieldname=='ModifiedByAgentID') { $retval = self::C_ModifiedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='GiftID') { $retval = self::C_GiftIDMYSQLI_TYPE; }
      if ($aFieldname=='DisciplineID') { $retval = self::C_DisciplineIDMYSQLI_TYPE; }
      if ($aFieldname=='PreparationID') { $retval = self::C_PreparationIDMYSQLI_TYPE; }
      if ($aFieldname=='CreatedByAgentID') { $retval = self::C_CreatedByAgentIDMYSQLI_TYPE; }
      return $retval;
   }

   // Function load() can take either the value of the primary key which uniquely identifies a particular row
   // or an array of array('primarykeyfieldname'=>'value') in the case of a single field primary key
   // or an array of fieldname value pairs in the case of multiple field primary key.
   public function load($pk) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        try {
             if (is_array($pk)) { 
                 $this->setGiftPreparationID($pk[GiftPreparationID]);
             } else { ;
                 $this->setGiftPreparationID($pk);
             };
        } 
        catch (Exception $e) { 
             throw new Exception($e->getMessage());
        }
        if($this->GiftPreparationID != NULL) {
           $sql = 'SELECT GiftPreparationID, TimestampCreated, TimestampModified, Version, DescriptionOfMaterial, InComments, ItemCount, NonSpecimenCount, OutComments, ReceivedComments, TypeCount, ModifiedByAgentID, GiftID, DisciplineID, PreparationID, CreatedByAgentID FROM giftpreparation WHERE GiftPreparationID = '.$this->GiftPreparationID ;

           $preparesql = 'SELECT GiftPreparationID, TimestampCreated, TimestampModified, Version, DescriptionOfMaterial, InComments, ItemCount, NonSpecimenCount, OutComments, ReceivedComments, TypeCount, ModifiedByAgentID, GiftID, DisciplineID, PreparationID, CreatedByAgentID FROM giftpreparation WHERE GiftPreparationID = ? ';

           if ($statement = $connection->prepare($preparesql)) { 
              $statement->bind_param("i", $this->GiftPreparationID);
              $statement->execute();
              $statement->bind_result($this->GiftPreparationID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->DescriptionOfMaterial, $this->InComments, $this->ItemCount, $this->NonSpecimenCount, $this->OutComments, $this->ReceivedComments, $this->TypeCount, $this->ModifiedByAgentID, $this->GiftID, $this->DisciplineID, $this->PreparationID, $this->CreatedByAgentID);
              $statement->fetch();
              $statement->close();
           }

            $this->loaded = true;
            $this->dirty = false;
        } else { 
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   // Function save() will either save the current record or insert a new record.
   // Inserts new record if the primary key field in this table is null 
   // for this instance of this object.
   // Otherwise updates the record identified by the primary key value.
   public function save() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        // Test to see if this is an insert or update.
        if ($this->GiftPreparationID!= NULL) {
            $sql  = 'UPDATE  giftpreparation SET ';
            $isInsert = false;
            $sql .=  "TimestampCreated = ? ";
            $sql .=  ", TimestampModified = ? ";
            $sql .=  ", Version = ? ";
            $sql .=  ", DescriptionOfMaterial = ? ";
            $sql .=  ", InComments = ? ";
            $sql .=  ", ItemCount = ? ";
            $sql .=  ", NonSpecimenCount = ? ";
            $sql .=  ", OutComments = ? ";
            $sql .=  ", ReceivedComments = ? ";
            $sql .=  ", TypeCount = ? ";
            $sql .=  ", ModifiedByAgentID = ? ";
            $sql .=  ", GiftID = ? ";
            $sql .=  ", DisciplineID = ? ";
            $sql .=  ", PreparationID = ? ";
            $sql .=  ", CreatedByAgentID = ? ";

            $sql .= "  WHERE GiftPreparationID = ? ";
        } else {
            $sql  = 'INSERT INTO giftpreparation ';
            $isInsert = true;
if ($this->PK==NULL) { throw new Exception('Can\'t insert record with null primary key for this table'); }
            $sql .= '( GiftPreparationID ,  TimestampCreated ,  TimestampModified ,  Version ,  DescriptionOfMaterial ,  InComments ,  ItemCount ,  NonSpecimenCount ,  OutComments ,  ReceivedComments ,  TypeCount ,  ModifiedByAgentID ,  GiftID ,  DisciplineID ,  PreparationID ,  CreatedByAgentID ) VALUES (';
            $sql .=  "  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .= ')';

        }
        if ($statement = $connection->prepare($sql)) { 
           if ($this->GiftPreparationID!= NULL ) {
              $statement->bind_param("ississiissiiiiiii", $this->GiftPreparationID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->DescriptionOfMaterial , $this->InComments , $this->ItemCount , $this->NonSpecimenCount , $this->OutComments , $this->ReceivedComments , $this->TypeCount , $this->ModifiedByAgentID , $this->GiftID , $this->DisciplineID , $this->PreparationID , $this->CreatedByAgentID , $this->GiftPreparationID );
           } else { 
              $statement->bind_param("ississiissiiiiii", $this->GiftPreparationID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->DescriptionOfMaterial , $this->InComments , $this->ItemCount , $this->NonSpecimenCount , $this->OutComments , $this->ReceivedComments , $this->TypeCount , $this->ModifiedByAgentID , $this->GiftID , $this->DisciplineID , $this->PreparationID , $this->CreatedByAgentID );
           } 
           $statement->execute();
           if ($statement->num_rows()!=1) {
               $this->error = $statement->error; 
           }
           $statement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }
        if ($this->error=='') { 
            $returnvalue = true;
        };

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function delete() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        if($this->GiftPreparationID != NULL) {
           $sql = 'SELECT GiftPreparationID, TimestampCreated, TimestampModified, Version, DescriptionOfMaterial, InComments, ItemCount, NonSpecimenCount, OutComments, ReceivedComments, TypeCount, ModifiedByAgentID, GiftID, DisciplineID, PreparationID, CreatedByAgentID FROM giftpreparation WHERE GiftPreparationID = "'.$this->GiftPreparationID.'"  ' ;

           $preparedsql = 'SELECT  FROM giftpreparation WHERE  and GiftPreparationID = ?  ' ;
        if ($statement = $connection->prepare($preparedsql)) { 
           $statement->bind_param("ississiissiiiiii", $this->GiftPreparationID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->DescriptionOfMaterial, $this->InComments, $this->ItemCount, $this->NonSpecimenCount, $this->OutComments, $this->ReceivedComments, $this->TypeCount, $this->ModifiedByAgentID, $this->GiftID, $this->DisciplineID, $this->PreparationID, $this->CreatedByAgentID);
           $statement->execute();
           $statement->store_result();
           if ($statement->num_rows()==1) {
                $sql = 'DELETE FROM giftpreparation WHERE  and GiftPreparationID = ?  ';
                if ($stmt_delete = $connection->prepare($sql)) { 
                   $stmt_delete->bind_param("ississiissiiiiii", $this->GiftPreparationID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->DescriptionOfMaterial, $this->InComments, $this->ItemCount, $this->NonSpecimenCount, $this->OutComments, $this->ReceivedComments, $this->TypeCount, $this->ModifiedByAgentID, $this->GiftID, $this->DisciplineID, $this->PreparationID, $this->CreatedByAgentID);
                   if ($stmnt_delete->execute()) { 
                       $returnvalue = true;
                   } else {
                       $this->error = mysqli_error($connection); 
                   }
                   $stmt_delete->close();
                }
           } else { 
               $this->error = mysqli_error($connection); 
           }
           $tatement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }

            $this->loaded = true;
            // record was deleted, so set PK to null
            $this->GiftPreparationID = NULL; 
        } else { 
           throw new Exception('Unable to identify which record to delete, primary key is not set');
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function count() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        $sql = 'SELECT count(*)  FROM giftpreparation';
        if ($result = $connection->query($sql)) { 
           if ($result->num_rows()==1) {
             $row = $result->fetch_row();
             if ($row) {
                $returnvalue = $row[0];
             }
           }
        } else { 
           $this->error = mysqli_error($connection); 
        }
        mysqli_free_result($result);

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function loadArrayKeyValueSearch($searchTermArray) {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = array();
       $and = '';
       $wherebit = 'WHERE ';
       foreach($searchTermArray as $fieldname => $searchTerm) {
           if ($this->hasField($fieldname)) { 
               $operator = '='; 
               // change to a like search if a wildcard character is present
               if (!(strpos($searchTerm,'%')===false)) { $operator = 'like'; }
               if (!(strpos($searchTerm,'_')===false)) { $operator = 'like'; }
               if ($searchTerm=='[NULL]') { 
                   $wherebit .= "$and ($fieldname is null or $fieldname='') "; 
               } else { 
                   $wherebit .= "$and $fieldname $operator ? ";
                   $types = $types . $this->MySQLiFieldType($fieldname);
               } 
               $and = ' and ';
           }
       }
       $sql = "SELECT GiftPreparationID FROM giftpreparation $wherebit";
       if ($wherebit=='') { 
             $this->error = 'Error: No search terms provided';
       } else {
          $statement = $connection->prepare($sql);
          $vars = Array();
          $vars[] = $types;
          $i = 0;
          foreach ($searchTermArray as $value) { 
               $varname = 'bind'.$i;  // create a variable name
               $$varname = $value;    // using that variable name store the value 
               $vars[] = &$$varname;  // add a reference to the variable to the array
               $i++;
           }
           //$vars[] contains $types followed by references to variables holding each value in $searchTermArray.
          call_user_func_array(array($statement,'bind_param'),$vars);
          //$statement->bind_param($types,$names);
          $statement->execute();
          $statement->bind_result($id);
          $ids = array();
          while ($statement->fetch()) {
              $ids[] = $id;
          } // double loop to allow all data to be retrieved before preparing a new statement. 
          $statement->close();
          for ($i=0;$i<count($ids);$i++) {
              $obj = new huh_giftpreparation();
              $obj->load($ids[$i]);
              $returnvalue[] = $obj;
              $result=true;
          }
          if ($result===false) { $this->error = mysqli_error($connection); }
       }
       return $returnvalue;
   }	

   //---------------------------------------------------------------------------

// TODO: *************** link to related tables 

   //---------------------------------------------------------------------------

  public function loadLinkedTo() { 
     $returnvalue = array(); 
       // fk: ModifiedByAgentID
      $t = new agent();
      $t->load(getModifiedByAgentID());
      $returnvalue[ModifiedByAgentID] = $t;
       // fk: GiftID
      $t = new gift();
      $t->load(getGiftID());
      $returnvalue[GiftID] = $t;
       // fk: DisciplineID
      $t = new discipline();
      $t->load(getDisciplineID());
      $returnvalue[DisciplineID] = $t;
       // fk: PreparationID
      $t = new preparation();
      $t->load(getPreparationID());
      $returnvalue[PreparationID] = $t;
       // fk: CreatedByAgentID
      $t = new agent();
      $t->load(getCreatedByAgentID());
      $returnvalue[CreatedByAgentID] = $t;
     return $returnvalue;
  } 
   // Returns an array of primary key values (id) and concatenated values of all other fields (fields)
   // wrapped as $values in: '{ "identifier":"id", "items": [ '.$values.' ] }';
   // when druid_handler.php is called with druid_action=returnfkjson
   // Used with dojo dijit.form.FilteringSelect to submit surrogate numeric key values from a text picklist 
   public function keySelectAllConcatJSON($orderby='ASC') {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
       $returnvalue = '';
       $order = '';
       if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
       $sql = "SELECT GiftPreparationID, concat(IFNULL(TimestampCreated,'') || ' ' || IFNULL(TimestampModified,'') || ' ' || IFNULL(Version,'') || ' ' || IFNULL(DescriptionOfMaterial,'') || ' ' || IFNULL(InComments,'') || ' ' || IFNULL(ItemCount,'') || ' ' || IFNULL(NonSpecimenCount,'') || ' ' || IFNULL(OutComments,'') || ' ' || IFNULL(ReceivedComments,'') || ' ' || IFNULL(TypeCount,'') || ' ' || IFNULL(ModifiedByAgentID,'') || ' ' || IFNULL(GiftID,'') || ' ' || IFNULL(DisciplineID,'') || ' ' || IFNULL(PreparationID,'') || ' ' || IFNULL(CreatedByAgentID,'')) FROM giftpreparation order by ModifiedByAgentID, GiftID, DisciplineID, PreparationID, CreatedByAgentID $order ";
       $comma = '';
       if ($result = $connection->query($sql)) { 
          while ($row = $result->fetch_row()) {
             if ($row) {
                $pkval = trim($row[0]);
                $fval = trim($row[1]);
                if ($pkval!='') { 
                    $pkval = str_replace('"','&quot;',$pkval);
                    $fval = str_replace('"','&quot;',$fval);
                    $returnvalue .= $comma . ' { "id":"'.$pkval.'", "fields": "'.$fval.'" } ';
                    $comma = ', ';
                }
             }
          }
       } else { 
          $this->error = mysqli_error(); 
       }
       $result->close();
       return $returnvalue;
   }
   //---------------------------------------------------------------------------

   public function keySelectDistinctJSON($field,$orderby='ASC') {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = '';
       if ($this->hasField($field)) { 
          $order = '';
          $fieldesc = mysql_escape_string($field);
          if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
          $preparemysql = "SELECT DISTINCT $fieldesc FROM giftpreparation order by $fieldesc $order ";
          $comma = '';
         if ($stmt = $connection->prepare($preparemysql)) { 
             $stmt->execute();
             $stmt->bind_result($val);
             while ($stmt->fetch()) {
                $val = trim($val);                if ($val!='') { 
                    $val = str_replace('"','&quot;',$val);
                    $returnvalue .= $comma . ' { "'.$field.'":"'.$val.'" } ';
                    $comma = ', ';
                 }
             }
             $stmt->close();
         }
       }
       return $returnvalue;
   }
   //---------------------------------------------------------------------------


   //---------------------------------------------------------------------------

   // Each field with an index has a load array method generated for it.
   public function loadArrayByModifiedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT GiftPreparationID FROM giftpreparation WHERE ModifiedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT GiftPreparationID FROM giftpreparation WHERE ModifiedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_giftpreparation();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByGiftID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT GiftPreparationID FROM giftpreparation WHERE GiftID $operator '$searchTerm'";
        $preparedsql = "SELECT GiftPreparationID FROM giftpreparation WHERE GiftID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_giftpreparation();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByDisciplineID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT GiftPreparationID FROM giftpreparation WHERE DisciplineID $operator '$searchTerm'";
        $preparedsql = "SELECT GiftPreparationID FROM giftpreparation WHERE DisciplineID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_giftpreparation();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByPreparationID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT GiftPreparationID FROM giftpreparation WHERE PreparationID $operator '$searchTerm'";
        $preparedsql = "SELECT GiftPreparationID FROM giftpreparation WHERE PreparationID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_giftpreparation();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByCreatedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT GiftPreparationID FROM giftpreparation WHERE CreatedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT GiftPreparationID FROM giftpreparation WHERE CreatedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_giftpreparation();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }

   //---------------------------------------------------------------------------

   // Each fulltext index has a load array method generated for it.

   //---------------------------------------------------------------------------

   // Each field with an index has a select distinct method generated for it.
   public function selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ModifiedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ModifiedByAgentID FROM giftpreparation group by ModifiedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ModifiedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctGiftID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' GiftID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, GiftID FROM giftpreparation group by GiftID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&GiftID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctDisciplineID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' DisciplineID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, DisciplineID FROM giftpreparation group by DisciplineID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&DisciplineID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctPreparationID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' PreparationID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, PreparationID FROM giftpreparation group by PreparationID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&PreparationID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' CreatedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, CreatedByAgentID FROM giftpreparation group by CreatedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&CreatedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }

   public function keySelectDistinct($fieldname,$startline,$link,$endline,$includecount=false,$orderbycount=false) {
       $returnvalue = '';
       switch ($fieldname) { 
          case 'ModifiedByAgentID':
             $returnvalue = $this->selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'GiftID':
             $returnvalue = $this->selectDistinctGiftID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'DisciplineID':
             $returnvalue = $this->selectDistinctDisciplineID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'PreparationID':
             $returnvalue = $this->selectDistinctPreparationID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'CreatedByAgentID':
             $returnvalue = $this->selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
       }
       return $returnvalue;
    }

   //---------------------------------------------------------------------------

   public function hasField($fieldname) {
       $returnvalue = false;
       if (trim($fieldname)!='' && trim($fieldname)!=',') {
            if (strpos(self::FIELDLIST," $fieldname, ")!==false) { 
               $returnvalue = true;
            }
       }
       return $returnvalue;
    }
   //---------------------------------------------------------------------------

}


// Write your own views by extending this class.
// Place your extended views in a separate file and you
// can use Druid to regenerate the giftpreparation.php file to reflect changes
// in the underlying database without overwriting your custom views of the data.
// 
class huh_giftpreparationView implements viewer
{
   var $model = null;
   public function setModel($aModel) { 
       $this->model = $aModel;
   }
   // @param $includeRelated default true shows rows from other tables through foreign key relationships.
   // @param $editLinkURL default '' allows adding a link to show this record in an editing form.
   public function getDetailsView($includeRelated=true, $editLinkURL='') {
       $returnvalue = '<ul>';
       $editLinkURL=trim($editLinkURL);
       $model = $this->model;
       $primarykeys = $model->schemaPK();
       if ($editLinkURL!='') { 
          if (!preg_match('/\&$/',$editLinkURL)) { $editLinkURL .= '&'; } 
          $nullpk = false; 
          foreach ($primarykeys as $primarykey) { 
              // Add fieldname=value pairs for primary key(s) to editLinkURL. 
              $editLinkURL .= urlencode($primarykey) . '=' . urlencode($model->keyGet($primarykey));
              if ($model->keyGet($primarykey)=='') { $nullpk = true; } 
          }
          if (!$nullpk) { $returnvalue .= "<li>huh_giftpreparation <a href='$editLinkURL'>Edit</a></li>\n";  } 
       }
       $returnvalue .= "<li>".huh_giftpreparation::GIFTPREPARATIONID.": ".$model->getGiftPreparationID()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::TIMESTAMPCREATED.": ".$model->getTimestampCreated()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::TIMESTAMPMODIFIED.": ".$model->getTimestampModified()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::VERSION.": ".$model->getVersion()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::DESCRIPTIONOFMATERIAL.": ".$model->getDescriptionOfMaterial()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::INCOMMENTS.": ".$model->getInComments()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::ITEMCOUNT.": ".$model->getItemCount()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::NONSPECIMENCOUNT.": ".$model->getNonSpecimenCount()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::OUTCOMMENTS.": ".$model->getOutComments()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::RECEIVEDCOMMENTS.": ".$model->getReceivedComments()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::TYPECOUNT.": ".$model->getTypeCount()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::MODIFIEDBYAGENTID.": ".$model->getModifiedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::GIFTID.": ".$model->getGiftID()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::DISCIPLINEID.": ".$model->getDisciplineID()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::PREPARATIONID.": ".$model->getPreparationID()."</li>\n";
       $returnvalue .= "<li>".huh_giftpreparation::CREATEDBYAGENTID.": ".$model->getCreatedByAgentID()."</li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getModifiedByAgentID() != '') { 
               $t_agent->load($model->getModifiedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>gift</li>";
           $t_gift = new huh_gift();
           $t_giftView = new huh_giftView();
           $t_giftView->setModel($t_gift);
           if ($model->getGiftID() != '') { 
               $t_gift->load($model->getGiftID());
               $returnvalue .= $t_giftView->getDetailsView(false);
           }
           $returnvalue .= "<li>discipline</li>";
           $t_discipline = new huh_discipline();
           $t_disciplineView = new huh_disciplineView();
           $t_disciplineView->setModel($t_discipline);
           if ($model->getDisciplineID() != '') { 
               $t_discipline->load($model->getDisciplineID());
               $returnvalue .= $t_disciplineView->getDetailsView(false);
           }
           $returnvalue .= "<li>preparation</li>";
           $t_preparation = new huh_preparation();
           $t_preparationView = new huh_preparationView();
           $t_preparationView->setModel($t_preparation);
           if ($model->getPreparationID() != '') { 
               $t_preparation->load($model->getPreparationID());
               $returnvalue .= $t_preparationView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getCreatedByAgentID() != '') { 
               $t_agent->load($model->getCreatedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }

        }
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getJSON() {
       $returnvalue = '{ ';
       $model = $this->model;
       $returnvalue .= '"'.huh_giftpreparation::GIFTPREPARATIONID.': "'.$model->getGiftPreparationID().'",';
       $returnvalue .= '"'.huh_giftpreparation::TIMESTAMPCREATED.': "'.$model->getTimestampCreated().'",';
       $returnvalue .= '"'.huh_giftpreparation::TIMESTAMPMODIFIED.': "'.$model->getTimestampModified().'",';
       $returnvalue .= '"'.huh_giftpreparation::VERSION.': "'.$model->getVersion().'",';
       $returnvalue .= '"'.huh_giftpreparation::DESCRIPTIONOFMATERIAL.': "'.$model->getDescriptionOfMaterial().'",';
       $returnvalue .= '"'.huh_giftpreparation::INCOMMENTS.': "'.$model->getInComments().'",';
       $returnvalue .= '"'.huh_giftpreparation::ITEMCOUNT.': "'.$model->getItemCount().'",';
       $returnvalue .= '"'.huh_giftpreparation::NONSPECIMENCOUNT.': "'.$model->getNonSpecimenCount().'",';
       $returnvalue .= '"'.huh_giftpreparation::OUTCOMMENTS.': "'.$model->getOutComments().'",';
       $returnvalue .= '"'.huh_giftpreparation::RECEIVEDCOMMENTS.': "'.$model->getReceivedComments().'",';
       $returnvalue .= '"'.huh_giftpreparation::TYPECOUNT.': "'.$model->getTypeCount().'",';
       $returnvalue .= '"'.huh_giftpreparation::MODIFIEDBYAGENTID.': "'.$model->getModifiedByAgentID().'",';
       $returnvalue .= '"'.huh_giftpreparation::GIFTID.': "'.$model->getGiftID().'",';
       $returnvalue .= '"'.huh_giftpreparation::DISCIPLINEID.': "'.$model->getDisciplineID().'",';
       $returnvalue .= '"'.huh_giftpreparation::PREPARATIONID.': "'.$model->getPreparationID().'",';
       $returnvalue .= '"'.huh_giftpreparation::CREATEDBYAGENTID.': "'.$model->getCreatedByAgentID().'" }';
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getTableRowView() {
       $returnvalue = '<tr>';
       $model = $this->model;
       $returnvalue .= "<td>".$model->getGiftPreparationID()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampCreated()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampModified()."</td>\n";
       $returnvalue .= "<td>".$model->getVersion()."</td>\n";
       $returnvalue .= "<td>".$model->getDescriptionOfMaterial()."</td>\n";
       $returnvalue .= "<td>".$model->getInComments()."</td>\n";
       $returnvalue .= "<td>".$model->getItemCount()."</td>\n";
       $returnvalue .= "<td>".$model->getNonSpecimenCount()."</td>\n";
       $returnvalue .= "<td>".$model->getOutComments()."</td>\n";
       $returnvalue .= "<td>".$model->getReceivedComments()."</td>\n";
       $returnvalue .= "<td>".$model->getTypeCount()."</td>\n";
       $returnvalue .= "<td>".$model->getModifiedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getGiftID()."</td>\n";
       $returnvalue .= "<td>".$model->getDisciplineID()."</td>\n";
       $returnvalue .= "<td>".$model->getPreparationID()."</td>\n";
       $returnvalue .= "<td>".$model->getCreatedByAgentID()."</td>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getHeaderRow() {
       $returnvalue = '<tr>';
       $returnvalue .= "<th>".huh_giftpreparation::GIFTPREPARATIONID."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::TIMESTAMPCREATED."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::TIMESTAMPMODIFIED."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::VERSION."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::DESCRIPTIONOFMATERIAL."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::INCOMMENTS."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::ITEMCOUNT."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::NONSPECIMENCOUNT."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::OUTCOMMENTS."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::RECEIVEDCOMMENTS."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::TYPECOUNT."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::MODIFIEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::GIFTID."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::DISCIPLINEID."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::PREPARATIONID."</th>\n";
       $returnvalue .= "<th>".huh_giftpreparation::CREATEDBYAGENTID."</th>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getEditFormDojoView($includeRelated=true) {
       $model = $this->model;
       if ($model->PK()=='') { $addform=true; } else { $addform=false; } 
       $returnvalue = '';
       $id = trim($model->PK());
       $feedback = "status$id";
       $formname = "editform$id";
       $script = '
  var saveprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function save'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Saving...";
     dojo.xhrGet(saveprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_giftpreparation">';
       $returnvalue .= "<div id='div_$formnane' >";
       if($addform) { 
          $returnvalue .= "Add a new GiftPreparationID"; 
       } else { 
         $returnvalue .= "<div><label for=".huh_giftpreparation::GIFTPREPARATIONID.">GIFTPREPARATIONID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::GIFTPREPARATIONID." id=".huh_giftpreparation::GIFTPREPARATIONID." value='".$model->getGiftPreparationID()."'  style=' width:".huh_giftpreparation::GIFTPREPARATIONID_SIZE ."em;  '  maxlength='".huh_giftpreparation::GIFTPREPARATIONID_SIZE ."' ></div>\n";
       }  
       $returnvalue .= "<div><label for=".huh_giftpreparation::TIMESTAMPCREATED.">TIMESTAMPCREATED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_giftpreparation::TIMESTAMPCREATED." id=".huh_giftpreparation::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  style=' width:".huh_giftpreparation::TIMESTAMPCREATED_SIZE ."em;  '  maxlength='".huh_giftpreparation::TIMESTAMPCREATED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::TIMESTAMPMODIFIED.">TIMESTAMPMODIFIED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_giftpreparation::TIMESTAMPMODIFIED." id=".huh_giftpreparation::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  style=' width:".huh_giftpreparation::TIMESTAMPMODIFIED_SIZE ."em;  '  maxlength='".huh_giftpreparation::TIMESTAMPMODIFIED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::VERSION.">VERSION</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::VERSION." id=".huh_giftpreparation::VERSION." value='".$model->getVersion()."'  style=' width:".huh_giftpreparation::VERSION_SIZE ."em;  '  maxlength='".huh_giftpreparation::VERSION_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::DESCRIPTIONOFMATERIAL.">DESCRIPTIONOFMATERIAL</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_giftpreparation::DESCRIPTIONOFMATERIAL." id=".huh_giftpreparation::DESCRIPTIONOFMATERIAL." >".$model->getDescriptionOfMaterial()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::INCOMMENTS.">INCOMMENTS</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_giftpreparation::INCOMMENTS." id=".huh_giftpreparation::INCOMMENTS." >".$model->getInComments()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::ITEMCOUNT.">ITEMCOUNT</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::ITEMCOUNT." id=".huh_giftpreparation::ITEMCOUNT." value='".$model->getItemCount()."'  style=' width:".huh_giftpreparation::ITEMCOUNT_SIZE ."em;  '  maxlength='".huh_giftpreparation::ITEMCOUNT_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::NONSPECIMENCOUNT.">NONSPECIMENCOUNT</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::NONSPECIMENCOUNT." id=".huh_giftpreparation::NONSPECIMENCOUNT." value='".$model->getNonSpecimenCount()."'  style=' width:".huh_giftpreparation::NONSPECIMENCOUNT_SIZE ."em;  '  maxlength='".huh_giftpreparation::NONSPECIMENCOUNT_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::OUTCOMMENTS.">OUTCOMMENTS</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_giftpreparation::OUTCOMMENTS." id=".huh_giftpreparation::OUTCOMMENTS." >".$model->getOutComments()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::RECEIVEDCOMMENTS.">RECEIVEDCOMMENTS</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_giftpreparation::RECEIVEDCOMMENTS." id=".huh_giftpreparation::RECEIVEDCOMMENTS." >".$model->getReceivedComments()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::TYPECOUNT.">TYPECOUNT</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::TYPECOUNT." id=".huh_giftpreparation::TYPECOUNT." value='".$model->getTypeCount()."'  style=' width:".huh_giftpreparation::TYPECOUNT_SIZE ."em;  '  maxlength='".huh_giftpreparation::TYPECOUNT_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::MODIFIEDBYAGENTID.">MODIFIEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::MODIFIEDBYAGENTID." id=".huh_giftpreparation::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  style=' width:".huh_giftpreparation::MODIFIEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_giftpreparation::MODIFIEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::GIFTID.">GIFTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::GIFTID." id=".huh_giftpreparation::GIFTID." value='".$model->getGiftID()."'  style=' width:".huh_giftpreparation::GIFTID_SIZE ."em;  '  maxlength='".huh_giftpreparation::GIFTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::DISCIPLINEID.">DISCIPLINEID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::DISCIPLINEID." id=".huh_giftpreparation::DISCIPLINEID." value='".$model->getDisciplineID()."'  style=' width:".huh_giftpreparation::DISCIPLINEID_SIZE ."em;  '  maxlength='".huh_giftpreparation::DISCIPLINEID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::PREPARATIONID.">PREPARATIONID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::PREPARATIONID." id=".huh_giftpreparation::PREPARATIONID." value='".$model->getPreparationID()."'  style=' width:".huh_giftpreparation::PREPARATIONID_SIZE ."em;  '  maxlength='".huh_giftpreparation::PREPARATIONID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_giftpreparation::CREATEDBYAGENTID.">CREATEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_giftpreparation::CREATEDBYAGENTID." id=".huh_giftpreparation::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  style=' width:".huh_giftpreparation::CREATEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_giftpreparation::CREATEDBYAGENTID_SIZE ."' ></div>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= "<li><input name=save id=save type=button value='Save' onclick='$script  save$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</div>';
       $returnvalue .= '</form>';
       if(!$addform) { 
          // show delete button if editing an existing record 
       $id = trim($model->PK());
       $feedback = "deletestatus$id";
       $formname = "deleteform$id";
       $script = '
  var deleteprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function deleterecord'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Deleting...";
     dojo.xhrGet(deleteprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=delete>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_table value="huh_giftpreparation">';
       $returnvalue .= '<input type=hidden name=GiftPreparationID id=druid_table value="'.$id.'">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li><input name=delete id=save type=button value='Delete' onclick='$script  deleterecord$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       } 
       return  $returnvalue;
   }
   public function getEditFormView($includeRelated=true) {
       $model = $this->model;
       $returnvalue = '<form method=get action=druid_handler.php>';
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_giftpreparation">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li>GIFTPREPARATIONID<input type=text name=".huh_giftpreparation::GIFTPREPARATIONID." id=".huh_giftpreparation::GIFTPREPARATIONID." value='".$model->getGiftPreparationID()."'  size='".huh_giftpreparation::GIFTPREPARATIONID_SIZE ."'  maxlength='".huh_giftpreparation::GIFTPREPARATIONID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPCREATED<input type=text name=".huh_giftpreparation::TIMESTAMPCREATED." id=".huh_giftpreparation::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  size='".huh_giftpreparation::TIMESTAMPCREATED_SIZE ."'  maxlength='".huh_giftpreparation::TIMESTAMPCREATED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPMODIFIED<input type=text name=".huh_giftpreparation::TIMESTAMPMODIFIED." id=".huh_giftpreparation::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  size='".huh_giftpreparation::TIMESTAMPMODIFIED_SIZE ."'  maxlength='".huh_giftpreparation::TIMESTAMPMODIFIED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VERSION<input type=text name=".huh_giftpreparation::VERSION." id=".huh_giftpreparation::VERSION." value='".$model->getVersion()."'  size='".huh_giftpreparation::VERSION_SIZE ."'  maxlength='".huh_giftpreparation::VERSION_SIZE ."' ></li>\n";
       $returnvalue .= "<li>DESCRIPTIONOFMATERIAL<input type=text name=".huh_giftpreparation::DESCRIPTIONOFMATERIAL." id=".huh_giftpreparation::DESCRIPTIONOFMATERIAL." value='".$model->getDescriptionOfMaterial()."'  size='51'  maxlength='".huh_giftpreparation::DESCRIPTIONOFMATERIAL_SIZE ."' ></li>\n";
       $returnvalue .= "<li>INCOMMENTS<input type=text name=".huh_giftpreparation::INCOMMENTS." id=".huh_giftpreparation::INCOMMENTS." value='".$model->getInComments()."'  size='51'  maxlength='".huh_giftpreparation::INCOMMENTS_SIZE ."' ></li>\n";
       $returnvalue .= "<li>ITEMCOUNT<input type=text name=".huh_giftpreparation::ITEMCOUNT." id=".huh_giftpreparation::ITEMCOUNT." value='".$model->getItemCount()."'  size='".huh_giftpreparation::ITEMCOUNT_SIZE ."'  maxlength='".huh_giftpreparation::ITEMCOUNT_SIZE ."' ></li>\n";
       $returnvalue .= "<li>NONSPECIMENCOUNT<input type=text name=".huh_giftpreparation::NONSPECIMENCOUNT." id=".huh_giftpreparation::NONSPECIMENCOUNT." value='".$model->getNonSpecimenCount()."'  size='".huh_giftpreparation::NONSPECIMENCOUNT_SIZE ."'  maxlength='".huh_giftpreparation::NONSPECIMENCOUNT_SIZE ."' ></li>\n";
       $returnvalue .= "<li>OUTCOMMENTS<input type=text name=".huh_giftpreparation::OUTCOMMENTS." id=".huh_giftpreparation::OUTCOMMENTS." value='".$model->getOutComments()."'  size='51'  maxlength='".huh_giftpreparation::OUTCOMMENTS_SIZE ."' ></li>\n";
       $returnvalue .= "<li>RECEIVEDCOMMENTS<input type=text name=".huh_giftpreparation::RECEIVEDCOMMENTS." id=".huh_giftpreparation::RECEIVEDCOMMENTS." value='".$model->getReceivedComments()."'  size='51'  maxlength='".huh_giftpreparation::RECEIVEDCOMMENTS_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TYPECOUNT<input type=text name=".huh_giftpreparation::TYPECOUNT." id=".huh_giftpreparation::TYPECOUNT." value='".$model->getTypeCount()."'  size='".huh_giftpreparation::TYPECOUNT_SIZE ."'  maxlength='".huh_giftpreparation::TYPECOUNT_SIZE ."' ></li>\n";
       $returnvalue .= "<li>MODIFIEDBYAGENTID<input type=text name=".huh_giftpreparation::MODIFIEDBYAGENTID." id=".huh_giftpreparation::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  size='".huh_giftpreparation::MODIFIEDBYAGENTID_SIZE ."'  maxlength='".huh_giftpreparation::MODIFIEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>GIFTID<input type=text name=".huh_giftpreparation::GIFTID." id=".huh_giftpreparation::GIFTID." value='".$model->getGiftID()."'  size='".huh_giftpreparation::GIFTID_SIZE ."'  maxlength='".huh_giftpreparation::GIFTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>DISCIPLINEID<input type=text name=".huh_giftpreparation::DISCIPLINEID." id=".huh_giftpreparation::DISCIPLINEID." value='".$model->getDisciplineID()."'  size='".huh_giftpreparation::DISCIPLINEID_SIZE ."'  maxlength='".huh_giftpreparation::DISCIPLINEID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>PREPARATIONID<input type=text name=".huh_giftpreparation::PREPARATIONID." id=".huh_giftpreparation::PREPARATIONID." value='".$model->getPreparationID()."'  size='".huh_giftpreparation::PREPARATIONID_SIZE ."'  maxlength='".huh_giftpreparation::PREPARATIONID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>CREATEDBYAGENTID<input type=text name=".huh_giftpreparation::CREATEDBYAGENTID." id=".huh_giftpreparation::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  size='".huh_giftpreparation::CREATEDBYAGENTID_SIZE ."'  maxlength='".huh_giftpreparation::CREATEDBYAGENTID_SIZE ."' ></li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= '<li><input type=submit value="Save"></li>';
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       return  $returnvalue;
   }
}

//==============================================================================
?>
