<?php
//==============================================================================
//===   project.php                         
//===   Autogenerated by Druid from MySQL db Build:6
//==============================================================================

include_once("druid_interfaces.php");

class huh_project implements  model , loadableModel, saveableModel, tableSchema 
{
   // These constants hold the sizes the fields in this table in the database.
   const PROJECTID_SIZE       = 11; //INTEGER
   const TIMESTAMPCREATED_SIZE = 21; //TIMESTAMP
   const TIMESTAMPMODIFIED_SIZE = 21; //TIMESTAMP
   const VERSION_SIZE         = 11; //INTEGER
   const COLLECTIONMEMBERID_SIZE = 11; //INTEGER
   const ENDDATE_SIZE         = 12; //DATE
   const GRANTAGENCY_SIZE     = 64; //64
   const GRANTNUMBER_SIZE     = 64; //64
   const NUMBER1_SIZE         = 20; //REAL
   const NUMBER2_SIZE         = 20; //REAL
   const PROJECTDESCRIPTION_SIZE = 255; //255
   const PROJECTNAME_SIZE     = 50; //50
   const PROJECTNUMBER_SIZE   = 64; //64
   const REMARKS_SIZE         = 255; //LONGVARCHAR
   const STARTDATE_SIZE       = 12; //DATE
   const TEXT1_SIZE           = 255; //LONGVARCHAR
   const TEXT2_SIZE           = 255; //LONGVARCHAR
   const URL_SIZE             = 255; //LONGVARCHAR
   const YESNO1_SIZE          = 1; //1
   const YESNO2_SIZE          = 1; //1
   const CREATEDBYAGENTID_SIZE = 11; //INTEGER
   const MODIFIEDBYAGENTID_SIZE = 11; //INTEGER
   const PROJECTAGENTID_SIZE  = 11; //INTEGER
    // These constants hold the field names of the table in the database. 
   const PROJECTID         = 'ProjectID';
   const TIMESTAMPCREATED  = 'TimestampCreated';
   const TIMESTAMPMODIFIED = 'TimestampModified';
   const VERSION           = 'Version';
   const COLLECTIONMEMBERID = 'CollectionMemberID';
   const ENDDATE           = 'EndDate';
   const GRANTAGENCY       = 'GrantAgency';
   const GRANTNUMBER       = 'GrantNumber';
   const NUMBER1           = 'Number1';
   const NUMBER2           = 'Number2';
   const PROJECTDESCRIPTION = 'ProjectDescription';
   const PROJECTNAME       = 'ProjectName';
   const PROJECTNUMBER     = 'ProjectNumber';
   const REMARKS           = 'Remarks';
   const STARTDATE         = 'StartDate';
   const TEXT1             = 'Text1';
   const TEXT2             = 'Text2';
   const URL               = 'URL';
   const YESNO1            = 'YesNo1';
   const YESNO2            = 'YesNo2';
   const CREATEDBYAGENTID  = 'CreatedByAgentID';
   const MODIFIEDBYAGENTID = 'ModifiedByAgentID';
   const PROJECTAGENTID    = 'ProjectAgentID';

   //---------------------------------------------------------------------------

   // interface tableSchema implementation
   // schemaPK returns array of primary key field names
   public function schemaPK() {
       return $this->primaryKeyArray;
   } 
   // schemaHaveDistinct returns array of field names for which selectDistinct{fieldname} methods are available.
   public function schemaHaveDistinct() {
       return $this->selectDistinctFieldsArray;
   } 
   // schemaFields returns array of all field names
   public function schemaFields() { 
       return $this->allFieldsArray;
   } 
/*  Example sanitized retrieval of variable matching object variables from $_GET 
/*  Customize these to limit each variable to narrowest possible set of known good values. 

  $ProjectID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ProjectID']), 0, 11);
  $TimestampCreated = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampCreated']), 0, 21);
  $TimestampModified = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampModified']), 0, 21);
  $Version = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Version']), 0, 11);
  $CollectionMemberID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['CollectionMemberID']), 0, 11);
  $EndDate = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['EndDate']), 0, 12);
  $GrantAgency = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['GrantAgency']), 0, 64);
  $GrantNumber = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['GrantNumber']), 0, 64);
  $Number1 = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Number1']), 0, 20);
  $Number2 = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Number2']), 0, 20);
  $ProjectDescription = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['ProjectDescription']), 0, 255);
  $ProjectName = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['ProjectName']), 0, 20);
  $ProjectNumber = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['ProjectNumber']), 0, 64);
  $Remarks = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Remarks']), 0, 255);
  $StartDate = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['StartDate']), 0, 12);
  $Text1 = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Text1']), 0, 255);
  $Text2 = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Text2']), 0, 255);
  $URL = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['URL']), 0, 255);
  $YesNo1 = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['YesNo1']), 0, 1);
  $YesNo2 = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['YesNo2']), 0, 1);
  $CreatedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['CreatedByAgentID']), 0, 11);
  $ModifiedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ModifiedByAgentID']), 0, 11);
  $ProjectAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ProjectAgentID']), 0, 11);
*/

   //---------------------------------------------------------------------------

   private $ProjectID; // PK INTEGER 
   private $TimestampCreated; // TIMESTAMP 
   private $TimestampModified; // TIMESTAMP 
   private $Version; // INTEGER 
   private $CollectionMemberID; // INTEGER 
   private $EndDate; // DATE 
   private $GrantAgency; // VARCHAR(64) 
   private $GrantNumber; // VARCHAR(64) 
   private $Number1; // REAL 
   private $Number2; // REAL 
   private $ProjectDescription; // VARCHAR(255) 
   private $ProjectName; // YEAR 
   private $ProjectNumber; // VARCHAR(64) 
   private $Remarks; // LONGVARCHAR 
   private $StartDate; // DATE 
   private $Text1; // LONGVARCHAR 
   private $Text2; // LONGVARCHAR 
   private $URL; // LONGVARCHAR 
   private $YesNo1; // BIT(1) 
   private $YesNo2; // BIT(1) 
   private $CreatedByAgentID; // INTEGER 
   private $ModifiedByAgentID; // INTEGER 
   private $ProjectAgentID; // INTEGER 
   private $dirty;
   private $loaded;
   private $error;
   const FIELDLIST = ' ProjectID, TimestampCreated, TimestampModified, Version, CollectionMemberID, EndDate, GrantAgency, GrantNumber, Number1, Number2, ProjectDescription, ProjectName, ProjectNumber, Remarks, StartDate, Text1, Text2, URL, YesNo1, YesNo2, CreatedByAgentID, ModifiedByAgentID, ProjectAgentID, ';
   const PKFIELDLIST = ' ProjectID, ';
   const NUMBER_OF_PRIMARY_KEYS = 1;
   private $primaryKeyArray = array( 1 => 'ProjectID'  ) ;
   private $allFieldsArray = array( 0 => 'ProjectID' , 1 => 'TimestampCreated' , 2 => 'TimestampModified' , 3 => 'Version' , 4 => 'CollectionMemberID' , 5 => 'EndDate' , 6 => 'GrantAgency' , 7 => 'GrantNumber' , 8 => 'Number1' , 9 => 'Number2' , 10 => 'ProjectDescription' , 11 => 'ProjectName' , 12 => 'ProjectNumber' , 13 => 'Remarks' , 14 => 'StartDate' , 15 => 'Text1' , 16 => 'Text2' , 17 => 'URL' , 18 => 'YesNo1' , 19 => 'YesNo2' , 20 => 'CreatedByAgentID' , 21 => 'ModifiedByAgentID' , 22 => 'ProjectAgentID'  ) ;
   private $selectDistinctFieldsArray = array( 11 => 'ProjectName' , 12 => 'ProjectNumber' , 20 => 'CreatedByAgentID' , 21 => 'ModifiedByAgentID' , 22 => 'ProjectAgentID'  ) ;

   //---------------------------------------------------------------------------

   // constructor 
   function huh_project(){
       $this->ProjectID = NULL;
       $this->TimestampCreated = '';
       $this->TimestampModified = '';
       $this->Version = '';
       $this->CollectionMemberID = '';
       $this->EndDate = '';
       $this->GrantAgency = '';
       $this->GrantNumber = '';
       $this->Number1 = '';
       $this->Number2 = '';
       $this->ProjectDescription = '';
       $this->ProjectName = '';
       $this->ProjectNumber = '';
       $this->Remarks = '';
       $this->StartDate = '';
       $this->Text1 = '';
       $this->Text2 = '';
       $this->URL = '';
       $this->YesNo1 = '';
       $this->YesNo2 = '';
       $this->CreatedByAgentID = '';
       $this->ModifiedByAgentID = '';
       $this->ProjectAgentID = '';
       $this->dirty = false;
       $this->loaded = false;
       $this->error = '';
   }

   private function l_addslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = addslashes($value);
      }
      return $retval;
   }
   private function l_stripslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = stripslashes($value);
      }
      return $retval;
   }
   public function isDirty() {
       return $this->dirty;
   }
   public function isLoaded() {
       return $this->loaded;
   }
   public function errorMessage() {
       return $this->error;
   }

   //---------------------------------------------------------------------------

   public function keyValueSet($fieldname,$value) {
       $returnvalue = false;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='ProjectID') { $returnvalue = $this->setProjectID($value); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->setTimestampCreated($value); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->setTimestampModified($value); } 
             if ($fieldname=='Version') { $returnvalue = $this->setVersion($value); } 
             if ($fieldname=='CollectionMemberID') { $returnvalue = $this->setCollectionMemberID($value); } 
             if ($fieldname=='EndDate') { $returnvalue = $this->setEndDate($value); } 
             if ($fieldname=='GrantAgency') { $returnvalue = $this->setGrantAgency($value); } 
             if ($fieldname=='GrantNumber') { $returnvalue = $this->setGrantNumber($value); } 
             if ($fieldname=='Number1') { $returnvalue = $this->setNumber1($value); } 
             if ($fieldname=='Number2') { $returnvalue = $this->setNumber2($value); } 
             if ($fieldname=='ProjectDescription') { $returnvalue = $this->setProjectDescription($value); } 
             if ($fieldname=='ProjectName') { $returnvalue = $this->setProjectName($value); } 
             if ($fieldname=='ProjectNumber') { $returnvalue = $this->setProjectNumber($value); } 
             if ($fieldname=='Remarks') { $returnvalue = $this->setRemarks($value); } 
             if ($fieldname=='StartDate') { $returnvalue = $this->setStartDate($value); } 
             if ($fieldname=='Text1') { $returnvalue = $this->setText1($value); } 
             if ($fieldname=='Text2') { $returnvalue = $this->setText2($value); } 
             if ($fieldname=='URL') { $returnvalue = $this->setURL($value); } 
             if ($fieldname=='YesNo1') { $returnvalue = $this->setYesNo1($value); } 
             if ($fieldname=='YesNo2') { $returnvalue = $this->setYesNo2($value); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->setCreatedByAgentID($value); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->setModifiedByAgentID($value); } 
             if ($fieldname=='ProjectAgentID') { $returnvalue = $this->setProjectAgentID($value); } 
             $returnvalue = true;
          }
          catch (exception $e) { ;
              $returnvalue = false;
              throw new Exception('Field Set Error'.$e->getMessage()); 
          }
       } else { 
          throw new Exception('No Such field'); 
       }  
       return $returnvalue;
   }
   public function keyGet($fieldname) {
       $returnvalue = null;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='ProjectID') { $returnvalue = $this->getProjectID(); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->getTimestampCreated(); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->getTimestampModified(); } 
             if ($fieldname=='Version') { $returnvalue = $this->getVersion(); } 
             if ($fieldname=='CollectionMemberID') { $returnvalue = $this->getCollectionMemberID(); } 
             if ($fieldname=='EndDate') { $returnvalue = $this->getEndDate(); } 
             if ($fieldname=='GrantAgency') { $returnvalue = $this->getGrantAgency(); } 
             if ($fieldname=='GrantNumber') { $returnvalue = $this->getGrantNumber(); } 
             if ($fieldname=='Number1') { $returnvalue = $this->getNumber1(); } 
             if ($fieldname=='Number2') { $returnvalue = $this->getNumber2(); } 
             if ($fieldname=='ProjectDescription') { $returnvalue = $this->getProjectDescription(); } 
             if ($fieldname=='ProjectName') { $returnvalue = $this->getProjectName(); } 
             if ($fieldname=='ProjectNumber') { $returnvalue = $this->getProjectNumber(); } 
             if ($fieldname=='Remarks') { $returnvalue = $this->getRemarks(); } 
             if ($fieldname=='StartDate') { $returnvalue = $this->getStartDate(); } 
             if ($fieldname=='Text1') { $returnvalue = $this->getText1(); } 
             if ($fieldname=='Text2') { $returnvalue = $this->getText2(); } 
             if ($fieldname=='URL') { $returnvalue = $this->getURL(); } 
             if ($fieldname=='YesNo1') { $returnvalue = $this->getYesNo1(); } 
             if ($fieldname=='YesNo2') { $returnvalue = $this->getYesNo2(); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->getCreatedByAgentID(); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->getModifiedByAgentID(); } 
             if ($fieldname=='ProjectAgentID') { $returnvalue = $this->getProjectAgentID(); } 
          }
          catch (exception $e) { ;
              $returnvalue = null;
          }
       }
       return $returnvalue;
   }
/*ProjectID*/
   public function getProjectID() {
       if ($this->ProjectID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ProjectID));
       }
   }
   public function setProjectID($ProjectID) {
       if (strlen(preg_replace('/[^0-9]/','',$ProjectID)) > huh_project::PROJECTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ProjectID = trim($ProjectID);
       if (!ctype_digit(strval($ProjectID)) && trim(strval($ProjectID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ProjectID = $this->l_addslashes($ProjectID);
       $this->dirty = true;
   }
/*TimestampCreated*/
   public function getTimestampCreated() {
       if ($this->TimestampCreated==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampCreated));
       }
   }
   public function setTimestampCreated($TimestampCreated) {
       if (strlen($TimestampCreated) > huh_project::TIMESTAMPCREATED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampCreated = $this->l_addslashes($TimestampCreated);
       $this->dirty = true;
   }
/*TimestampModified*/
   public function getTimestampModified() {
       if ($this->TimestampModified==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampModified));
       }
   }
   public function setTimestampModified($TimestampModified) {
       if (strlen($TimestampModified) > huh_project::TIMESTAMPMODIFIED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampModified = $this->l_addslashes($TimestampModified);
       $this->dirty = true;
   }
/*Version*/
   public function getVersion() {
       if ($this->Version==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Version));
       }
   }
   public function setVersion($Version) {
       if (strlen(preg_replace('/[^0-9]/','',$Version)) > huh_project::VERSION_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Version = trim($Version);
       if (!ctype_digit(strval($Version)) && trim(strval($Version))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Version = $this->l_addslashes($Version);
       $this->dirty = true;
   }
/*CollectionMemberID*/
   public function getCollectionMemberID() {
       if ($this->CollectionMemberID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->CollectionMemberID));
       }
   }
   public function setCollectionMemberID($CollectionMemberID) {
       if (strlen(preg_replace('/[^0-9]/','',$CollectionMemberID)) > huh_project::COLLECTIONMEMBERID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $CollectionMemberID = trim($CollectionMemberID);
       if (!ctype_digit(strval($CollectionMemberID))) {
             throw new Exception("Value must be an integer");
       }
       $this->CollectionMemberID = $this->l_addslashes($CollectionMemberID);
       $this->dirty = true;
   }
/*EndDate*/
   public function getEndDate() {
       if ($this->EndDate==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->EndDate));
       }
   }
   public function setEndDate($EndDate) {
       if (strlen($EndDate) > huh_project::ENDDATE_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->EndDate = $this->l_addslashes($EndDate);
       $this->dirty = true;
   }
/*GrantAgency*/
   public function getGrantAgency() {
       if ($this->GrantAgency==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->GrantAgency));
       }
   }
   public function setGrantAgency($GrantAgency) {
       if (strlen($GrantAgency) > huh_project::GRANTAGENCY_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->GrantAgency = $this->l_addslashes($GrantAgency);
       $this->dirty = true;
   }
/*GrantNumber*/
   public function getGrantNumber() {
       if ($this->GrantNumber==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->GrantNumber));
       }
   }
   public function setGrantNumber($GrantNumber) {
       if (strlen($GrantNumber) > huh_project::GRANTNUMBER_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->GrantNumber = $this->l_addslashes($GrantNumber);
       $this->dirty = true;
   }
/*Number1*/
   public function getNumber1() {
       if ($this->Number1==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Number1));
       }
   }
   public function setNumber1($Number1) {
       if (strlen($Number1) > huh_project::NUMBER1_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Number1 = $this->l_addslashes($Number1);
       $this->dirty = true;
   }
/*Number2*/
   public function getNumber2() {
       if ($this->Number2==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Number2));
       }
   }
   public function setNumber2($Number2) {
       if (strlen($Number2) > huh_project::NUMBER2_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Number2 = $this->l_addslashes($Number2);
       $this->dirty = true;
   }
/*ProjectDescription*/
   public function getProjectDescription() {
       if ($this->ProjectDescription==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ProjectDescription));
       }
   }
   public function setProjectDescription($ProjectDescription) {
       if (strlen($ProjectDescription) > huh_project::PROJECTDESCRIPTION_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->ProjectDescription = $this->l_addslashes($ProjectDescription);
       $this->dirty = true;
   }
/*ProjectName*/
   public function getProjectName() {
       if ($this->ProjectName==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ProjectName));
       }
   }
   public function setProjectName($ProjectName) {
       if (strlen($ProjectName) > huh_project::PROJECTNAME_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->ProjectName = $this->l_addslashes($ProjectName);
       $this->dirty = true;
   }
/*ProjectNumber*/
   public function getProjectNumber() {
       if ($this->ProjectNumber==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ProjectNumber));
       }
   }
   public function setProjectNumber($ProjectNumber) {
       if (strlen($ProjectNumber) > huh_project::PROJECTNUMBER_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->ProjectNumber = $this->l_addslashes($ProjectNumber);
       $this->dirty = true;
   }
/*Remarks*/
   public function getRemarks() {
       if ($this->Remarks==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Remarks));
       }
   }
   public function setRemarks($Remarks) {
       if (strlen($Remarks) > huh_project::REMARKS_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Remarks = $this->l_addslashes($Remarks);
       $this->dirty = true;
   }
/*StartDate*/
   public function getStartDate() {
       if ($this->StartDate==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->StartDate));
       }
   }
   public function setStartDate($StartDate) {
       if (strlen($StartDate) > huh_project::STARTDATE_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->StartDate = $this->l_addslashes($StartDate);
       $this->dirty = true;
   }
/*Text1*/
   public function getText1() {
       if ($this->Text1==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Text1));
       }
   }
   public function setText1($Text1) {
       if (strlen($Text1) > huh_project::TEXT1_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Text1 = $this->l_addslashes($Text1);
       $this->dirty = true;
   }
/*Text2*/
   public function getText2() {
       if ($this->Text2==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Text2));
       }
   }
   public function setText2($Text2) {
       if (strlen($Text2) > huh_project::TEXT2_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Text2 = $this->l_addslashes($Text2);
       $this->dirty = true;
   }
/*URL*/
   public function getURL() {
       if ($this->URL==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->URL));
       }
   }
   public function setURL($URL) {
       if (strlen($URL) > huh_project::URL_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->URL = $this->l_addslashes($URL);
       $this->dirty = true;
   }
/*YesNo1*/
   public function getYesNo1() {
       if ($this->YesNo1==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->YesNo1));
       }
   }
   public function setYesNo1($YesNo1) {
       if (strlen($YesNo1) > huh_project::YESNO1_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->YesNo1 = $this->l_addslashes($YesNo1);
       $this->dirty = true;
   }
/*YesNo2*/
   public function getYesNo2() {
       if ($this->YesNo2==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->YesNo2));
       }
   }
   public function setYesNo2($YesNo2) {
       if (strlen($YesNo2) > huh_project::YESNO2_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->YesNo2 = $this->l_addslashes($YesNo2);
       $this->dirty = true;
   }
/*CreatedByAgentID*/
   public function getCreatedByAgentID() {
       if ($this->CreatedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->CreatedByAgentID));
       }
   }
   public function setCreatedByAgentID($CreatedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$CreatedByAgentID)) > huh_project::CREATEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $CreatedByAgentID = trim($CreatedByAgentID);
       if (!ctype_digit(strval($CreatedByAgentID)) && trim(strval($CreatedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->CreatedByAgentID = $this->l_addslashes($CreatedByAgentID);
       $this->dirty = true;
   }
/*ModifiedByAgentID*/
   public function getModifiedByAgentID() {
       if ($this->ModifiedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ModifiedByAgentID));
       }
   }
   public function setModifiedByAgentID($ModifiedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$ModifiedByAgentID)) > huh_project::MODIFIEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ModifiedByAgentID = trim($ModifiedByAgentID);
       if (!ctype_digit(strval($ModifiedByAgentID)) && trim(strval($ModifiedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ModifiedByAgentID = $this->l_addslashes($ModifiedByAgentID);
       $this->dirty = true;
   }
/*ProjectAgentID*/
   public function getProjectAgentID() {
       if ($this->ProjectAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ProjectAgentID));
       }
   }
   public function setProjectAgentID($ProjectAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$ProjectAgentID)) > huh_project::PROJECTAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ProjectAgentID = trim($ProjectAgentID);
       if (!ctype_digit(strval($ProjectAgentID)) && trim(strval($ProjectAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ProjectAgentID = $this->l_addslashes($ProjectAgentID);
       $this->dirty = true;
   }
   public function PK() { // get value of primary key 
        $returnvalue = '';
        $returnvalue .= $this->getProjectID();
        return $returnvalue;
   }
   public function PKArray() { // get name and value of primary key fields 
        $returnvalue = array();
        $returnvalue['ProjectID'] = $this->getProjectID();
        return $returnvalue;
   }
   public function NumberOfPrimaryKeyFields() { // returns the number of primary key fields defined for this table 
        return 1;
   }

   // Constants holding the mysqli field type character (s,i,d) for each field
  const C_ProjectIDMYSQLI_TYPE = 'i';
  const C_TimestampCreatedMYSQLI_TYPE = 's';
  const C_TimestampModifiedMYSQLI_TYPE = 's';
  const C_VersionMYSQLI_TYPE = 'i';
  const C_CollectionMemberIDMYSQLI_TYPE = 'i';
  const C_EndDateMYSQLI_TYPE = 's';
  const C_GrantAgencyMYSQLI_TYPE = 's';
  const C_GrantNumberMYSQLI_TYPE = 's';
  const C_Number1MYSQLI_TYPE = 's';
  const C_Number2MYSQLI_TYPE = 's';
  const C_ProjectDescriptionMYSQLI_TYPE = 's';
  const C_ProjectNameMYSQLI_TYPE = 's';
  const C_ProjectNumberMYSQLI_TYPE = 's';
  const C_RemarksMYSQLI_TYPE = 's';
  const C_StartDateMYSQLI_TYPE = 's';
  const C_Text1MYSQLI_TYPE = 's';
  const C_Text2MYSQLI_TYPE = 's';
  const C_URLMYSQLI_TYPE = 's';
  const C_YesNo1MYSQLI_TYPE = 'i';
  const C_YesNo2MYSQLI_TYPE = 'i';
  const C_CreatedByAgentIDMYSQLI_TYPE = 'i';
  const C_ModifiedByAgentIDMYSQLI_TYPE = 'i';
  const C_ProjectAgentIDMYSQLI_TYPE = 'i';

   // function to obtain the mysqli field type character from a fieldname
   public function MySQLiFieldType($aFieldname) { 
      $retval = '';
      if ($aFieldname=='ProjectID') { $retval = self::C_ProjectIDMYSQLI_TYPE; }
      if ($aFieldname=='TimestampCreated') { $retval = self::C_TimestampCreatedMYSQLI_TYPE; }
      if ($aFieldname=='TimestampModified') { $retval = self::C_TimestampModifiedMYSQLI_TYPE; }
      if ($aFieldname=='Version') { $retval = self::C_VersionMYSQLI_TYPE; }
      if ($aFieldname=='CollectionMemberID') { $retval = self::C_CollectionMemberIDMYSQLI_TYPE; }
      if ($aFieldname=='EndDate') { $retval = self::C_EndDateMYSQLI_TYPE; }
      if ($aFieldname=='GrantAgency') { $retval = self::C_GrantAgencyMYSQLI_TYPE; }
      if ($aFieldname=='GrantNumber') { $retval = self::C_GrantNumberMYSQLI_TYPE; }
      if ($aFieldname=='Number1') { $retval = self::C_Number1MYSQLI_TYPE; }
      if ($aFieldname=='Number2') { $retval = self::C_Number2MYSQLI_TYPE; }
      if ($aFieldname=='ProjectDescription') { $retval = self::C_ProjectDescriptionMYSQLI_TYPE; }
      if ($aFieldname=='ProjectName') { $retval = self::C_ProjectNameMYSQLI_TYPE; }
      if ($aFieldname=='ProjectNumber') { $retval = self::C_ProjectNumberMYSQLI_TYPE; }
      if ($aFieldname=='Remarks') { $retval = self::C_RemarksMYSQLI_TYPE; }
      if ($aFieldname=='StartDate') { $retval = self::C_StartDateMYSQLI_TYPE; }
      if ($aFieldname=='Text1') { $retval = self::C_Text1MYSQLI_TYPE; }
      if ($aFieldname=='Text2') { $retval = self::C_Text2MYSQLI_TYPE; }
      if ($aFieldname=='URL') { $retval = self::C_URLMYSQLI_TYPE; }
      if ($aFieldname=='YesNo1') { $retval = self::C_YesNo1MYSQLI_TYPE; }
      if ($aFieldname=='YesNo2') { $retval = self::C_YesNo2MYSQLI_TYPE; }
      if ($aFieldname=='CreatedByAgentID') { $retval = self::C_CreatedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='ModifiedByAgentID') { $retval = self::C_ModifiedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='ProjectAgentID') { $retval = self::C_ProjectAgentIDMYSQLI_TYPE; }
      return $retval;
   }

   // Function load() can take either the value of the primary key which uniquely identifies a particular row
   // or an array of array('primarykeyfieldname'=>'value') in the case of a single field primary key
   // or an array of fieldname value pairs in the case of multiple field primary key.
   public function load($pk) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        try {
             if (is_array($pk)) { 
                 $this->setProjectID($pk[ProjectID]);
             } else { ;
                 $this->setProjectID($pk);
             };
        } 
        catch (Exception $e) { 
             throw new Exception($e->getMessage());
        }
        if($this->ProjectID != NULL) {
           $sql = 'SELECT ProjectID, TimestampCreated, TimestampModified, Version, CollectionMemberID, EndDate, GrantAgency, GrantNumber, Number1, Number2, ProjectDescription, ProjectName, ProjectNumber, Remarks, StartDate, Text1, Text2, URL, YesNo1, YesNo2, CreatedByAgentID, ModifiedByAgentID, ProjectAgentID FROM project WHERE ProjectID = '.$this->ProjectID ;

           $preparesql = 'SELECT ProjectID, TimestampCreated, TimestampModified, Version, CollectionMemberID, EndDate, GrantAgency, GrantNumber, Number1, Number2, ProjectDescription, ProjectName, ProjectNumber, Remarks, StartDate, Text1, Text2, URL, YesNo1, YesNo2, CreatedByAgentID, ModifiedByAgentID, ProjectAgentID FROM project WHERE ProjectID = ? ';

           if ($statement = $connection->prepare($preparesql)) { 
              $statement->bind_param("i", $this->ProjectID);
              $statement->execute();
              $statement->bind_result($this->ProjectID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->CollectionMemberID, $this->EndDate, $this->GrantAgency, $this->GrantNumber, $this->Number1, $this->Number2, $this->ProjectDescription, $this->ProjectName, $this->ProjectNumber, $this->Remarks, $this->StartDate, $this->Text1, $this->Text2, $this->URL, $this->YesNo1, $this->YesNo2, $this->CreatedByAgentID, $this->ModifiedByAgentID, $this->ProjectAgentID);
              $statement->fetch();
              $statement->close();
           }

            $this->loaded = true;
            $this->dirty = false;
        } else { 
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   // Function save() will either save the current record or insert a new record.
   // Inserts new record if the primary key field in this table is null 
   // for this instance of this object.
   // Otherwise updates the record identified by the primary key value.
   public function save() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        // Test to see if this is an insert or update.
        if ($this->ProjectID!= NULL) {
            $sql  = 'UPDATE  project SET ';
            $isInsert = false;
            $sql .=  "TimestampCreated = ? ";
            $sql .=  ", TimestampModified = ? ";
            $sql .=  ", Version = ? ";
            $sql .=  ", CollectionMemberID = ? ";
            $sql .=  ", EndDate = ? ";
            $sql .=  ", GrantAgency = ? ";
            $sql .=  ", GrantNumber = ? ";
            $sql .=  ", Number1 = ? ";
            $sql .=  ", Number2 = ? ";
            $sql .=  ", ProjectDescription = ? ";
            $sql .=  ", ProjectName = ? ";
            $sql .=  ", ProjectNumber = ? ";
            $sql .=  ", Remarks = ? ";
            $sql .=  ", StartDate = ? ";
            $sql .=  ", Text1 = ? ";
            $sql .=  ", Text2 = ? ";
            $sql .=  ", URL = ? ";
            $sql .=  ", YesNo1 = ? ";
            $sql .=  ", YesNo2 = ? ";
            $sql .=  ", CreatedByAgentID = ? ";
            $sql .=  ", ModifiedByAgentID = ? ";
            $sql .=  ", ProjectAgentID = ? ";

            $sql .= "  WHERE ProjectID = ? ";
        } else {
            $sql  = 'INSERT INTO project ';
            $isInsert = true;
if ($this->PK==NULL) { throw new Exception('Can\'t insert record with null primary key for this table'); }
            $sql .= '( ProjectID ,  TimestampCreated ,  TimestampModified ,  Version ,  CollectionMemberID ,  EndDate ,  GrantAgency ,  GrantNumber ,  Number1 ,  Number2 ,  ProjectDescription ,  ProjectName ,  ProjectNumber ,  Remarks ,  StartDate ,  Text1 ,  Text2 ,  URL ,  YesNo1 ,  YesNo2 ,  CreatedByAgentID ,  ModifiedByAgentID ,  ProjectAgentID ) VALUES (';
            $sql .=  "  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .= ')';

        }
        if ($statement = $connection->prepare($sql)) { 
           if ($this->ProjectID!= NULL ) {
              $statement->bind_param("issiisssssssssssssiiiiii", $this->ProjectID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->CollectionMemberID , $this->EndDate , $this->GrantAgency , $this->GrantNumber , $this->Number1 , $this->Number2 , $this->ProjectDescription , $this->ProjectName , $this->ProjectNumber , $this->Remarks , $this->StartDate , $this->Text1 , $this->Text2 , $this->URL , $this->YesNo1 , $this->YesNo2 , $this->CreatedByAgentID , $this->ModifiedByAgentID , $this->ProjectAgentID , $this->ProjectID );
           } else { 
              $statement->bind_param("issiisssssssssssssiiiii", $this->ProjectID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->CollectionMemberID , $this->EndDate , $this->GrantAgency , $this->GrantNumber , $this->Number1 , $this->Number2 , $this->ProjectDescription , $this->ProjectName , $this->ProjectNumber , $this->Remarks , $this->StartDate , $this->Text1 , $this->Text2 , $this->URL , $this->YesNo1 , $this->YesNo2 , $this->CreatedByAgentID , $this->ModifiedByAgentID , $this->ProjectAgentID );
           } 
           $statement->execute();
           if ($statement->num_rows()!=1) {
               $this->error = $statement->error; 
           }
           $statement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }
        if ($this->error=='') { 
            $returnvalue = true;
        };

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function delete() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        if($this->ProjectID != NULL) {
           $sql = 'SELECT ProjectID, TimestampCreated, TimestampModified, Version, CollectionMemberID, EndDate, GrantAgency, GrantNumber, Number1, Number2, ProjectDescription, ProjectName, ProjectNumber, Remarks, StartDate, Text1, Text2, URL, YesNo1, YesNo2, CreatedByAgentID, ModifiedByAgentID, ProjectAgentID FROM project WHERE ProjectID = "'.$this->ProjectID.'"  ' ;

           $preparedsql = 'SELECT  FROM project WHERE  and ProjectID = ?  ' ;
        if ($statement = $connection->prepare($preparedsql)) { 
           $statement->bind_param("issiisssssssssssssiiiii", $this->ProjectID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->CollectionMemberID, $this->EndDate, $this->GrantAgency, $this->GrantNumber, $this->Number1, $this->Number2, $this->ProjectDescription, $this->ProjectName, $this->ProjectNumber, $this->Remarks, $this->StartDate, $this->Text1, $this->Text2, $this->URL, $this->YesNo1, $this->YesNo2, $this->CreatedByAgentID, $this->ModifiedByAgentID, $this->ProjectAgentID);
           $statement->execute();
           $statement->store_result();
           if ($statement->num_rows()==1) {
                $sql = 'DELETE FROM project WHERE  and ProjectID = ?  ';
                if ($stmt_delete = $connection->prepare($sql)) { 
                   $stmt_delete->bind_param("issiisssssssssssssiiiii", $this->ProjectID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->CollectionMemberID, $this->EndDate, $this->GrantAgency, $this->GrantNumber, $this->Number1, $this->Number2, $this->ProjectDescription, $this->ProjectName, $this->ProjectNumber, $this->Remarks, $this->StartDate, $this->Text1, $this->Text2, $this->URL, $this->YesNo1, $this->YesNo2, $this->CreatedByAgentID, $this->ModifiedByAgentID, $this->ProjectAgentID);
                   if ($stmnt_delete->execute()) { 
                       $returnvalue = true;
                   } else {
                       $this->error = mysqli_error($connection); 
                   }
                   $stmt_delete->close();
                }
           } else { 
               $this->error = mysqli_error($connection); 
           }
           $tatement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }

            $this->loaded = true;
            // record was deleted, so set PK to null
            $this->ProjectID = NULL; 
        } else { 
           throw new Exception('Unable to identify which record to delete, primary key is not set');
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function count() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        $sql = 'SELECT count(*)  FROM project';
        if ($result = $connection->query($sql)) { 
           if ($result->num_rows()==1) {
             $row = $result->fetch_row();
             if ($row) {
                $returnvalue = $row[0];
             }
           }
        } else { 
           $this->error = mysqli_error($connection); 
        }
        mysqli_free_result($result);

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function loadArrayKeyValueSearch($searchTermArray) {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = array();
       $and = '';
       $wherebit = 'WHERE ';
       foreach($searchTermArray as $fieldname => $searchTerm) {
           if ($this->hasField($fieldname)) { 
               $operator = '='; 
               // change to a like search if a wildcard character is present
               if (!(strpos($searchTerm,'%')===false)) { $operator = 'like'; }
               if (!(strpos($searchTerm,'_')===false)) { $operator = 'like'; }
               if ($searchTerm=='[NULL]') { 
                   $wherebit .= "$and ($fieldname is null or $fieldname='') "; 
               } else { 
                   $wherebit .= "$and $fieldname $operator ? ";
                   $types = $types . $this->MySQLiFieldType($fieldname);
               } 
               $and = ' and ';
           }
       }
       $sql = "SELECT ProjectID FROM project $wherebit";
       if ($wherebit=='') { 
             $this->error = 'Error: No search terms provided';
       } else {
          $statement = $connection->prepare($sql);
          $vars = Array();
          $vars[] = $types;
          $i = 0;
          foreach ($searchTermArray as $value) { 
               $varname = 'bind'.$i;  // create a variable name
               $$varname = $value;    // using that variable name store the value 
               $vars[] = &$$varname;  // add a reference to the variable to the array
               $i++;
           }
           //$vars[] contains $types followed by references to variables holding each value in $searchTermArray.
          call_user_func_array(array($statement,'bind_param'),$vars);
          //$statement->bind_param($types,$names);
          $statement->execute();
          $statement->bind_result($id);
          $ids = array();
          while ($statement->fetch()) {
              $ids[] = $id;
          } // double loop to allow all data to be retrieved before preparing a new statement. 
          $statement->close();
          for ($i=0;$i<count($ids);$i++) {
              $obj = new huh_project();
              $obj->load($ids[$i]);
              $returnvalue[] = $obj;
              $result=true;
          }
          if ($result===false) { $this->error = mysqli_error($connection); }
       }
       return $returnvalue;
   }	

   //---------------------------------------------------------------------------

// TODO: *************** link to related tables 
  public function loadLinkedFromproject_colobj() { 
      // ForeignKey in: project_colobj
      $t = new project_colobj();
  } 

   //---------------------------------------------------------------------------

  public function loadLinkedTo() { 
     $returnvalue = array(); 
       // fk: CreatedByAgentID
      $t = new agent();
      $t->load(getCreatedByAgentID());
      $returnvalue[CreatedByAgentID] = $t;
       // fk: ModifiedByAgentID
      $t = new agent();
      $t->load(getModifiedByAgentID());
      $returnvalue[ModifiedByAgentID] = $t;
       // fk: ProjectAgentID
      $t = new agent();
      $t->load(getProjectAgentID());
      $returnvalue[ProjectAgentID] = $t;
     return $returnvalue;
  } 
   // Returns an array of primary key values (id) and concatenated values of all other fields (fields)
   // wrapped as $values in: '{ "identifier":"id", "items": [ '.$values.' ] }';
   // when druid_handler.php is called with druid_action=returnfkjson
   // Used with dojo dijit.form.FilteringSelect to submit surrogate numeric key values from a text picklist 
   public function keySelectAllConcatJSON($orderby='ASC') {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
       $returnvalue = '';
       $order = '';
       if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
       $sql = "SELECT ProjectID, concat(IFNULL(TimestampCreated,'') || ' ' || IFNULL(TimestampModified,'') || ' ' || IFNULL(Version,'') || ' ' || IFNULL(CollectionMemberID,'') || ' ' || IFNULL(EndDate,'') || ' ' || IFNULL(GrantAgency,'') || ' ' || IFNULL(GrantNumber,'') || ' ' || IFNULL(Number1,'') || ' ' || IFNULL(Number2,'') || ' ' || IFNULL(ProjectDescription,'') || ' ' || IFNULL(ProjectName,'') || ' ' || IFNULL(ProjectNumber,'') || ' ' || IFNULL(Remarks,'') || ' ' || IFNULL(StartDate,'') || ' ' || IFNULL(Text1,'') || ' ' || IFNULL(Text2,'') || ' ' || IFNULL(URL,'') || ' ' || IFNULL(YesNo1,'') || ' ' || IFNULL(YesNo2,'') || ' ' || IFNULL(CreatedByAgentID,'') || ' ' || IFNULL(ModifiedByAgentID,'') || ' ' || IFNULL(ProjectAgentID,'')) FROM project order by ProjectName, ProjectNumber, CreatedByAgentID, ModifiedByAgentID, ProjectAgentID $order ";
       $comma = '';
       if ($result = $connection->query($sql)) { 
          while ($row = $result->fetch_row()) {
             if ($row) {
                $pkval = trim($row[0]);
                $fval = trim($row[1]);
                if ($pkval!='') { 
                    $pkval = str_replace('"','&quot;',$pkval);
                    $fval = str_replace('"','&quot;',$fval);
                    $returnvalue .= $comma . ' { "id":"'.$pkval.'", "fields": "'.$fval.'" } ';
                    $comma = ', ';
                }
             }
          }
       } else { 
          $this->error = mysqli_error(); 
       }
       $result->close();
       return $returnvalue;
   }
   //---------------------------------------------------------------------------

   public function keySelectDistinctJSON($field,$orderby='ASC') {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = '';
       if ($this->hasField($field)) { 
          $order = '';
          $fieldesc = mysql_escape_string($field);
          if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
          $preparemysql = "SELECT DISTINCT $fieldesc FROM project order by $fieldesc $order ";
          $comma = '';
         if ($stmt = $connection->prepare($preparemysql)) { 
             $stmt->execute();
             $stmt->bind_result($val);
             while ($stmt->fetch()) {
                $val = trim($val);                if ($val!='') { 
                    $val = str_replace('"','&quot;',$val);
                    $returnvalue .= $comma . ' { "'.$field.'":"'.$val.'" } ';
                    $comma = ', ';
                 }
             }
             $stmt->close();
         }
       }
       return $returnvalue;
   }
   //---------------------------------------------------------------------------


   //---------------------------------------------------------------------------

   // Each field with an index has a load array method generated for it.
   public function loadArrayByProjectName($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT ProjectID FROM project WHERE ProjectName $operator '$searchTerm'";
        $preparedsql = "SELECT ProjectID FROM project WHERE ProjectName $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_project();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByProjectNumber($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT ProjectID FROM project WHERE ProjectNumber $operator '$searchTerm'";
        $preparedsql = "SELECT ProjectID FROM project WHERE ProjectNumber $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_project();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByCreatedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT ProjectID FROM project WHERE CreatedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT ProjectID FROM project WHERE CreatedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_project();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByModifiedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT ProjectID FROM project WHERE ModifiedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT ProjectID FROM project WHERE ModifiedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_project();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByProjectAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT ProjectID FROM project WHERE ProjectAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT ProjectID FROM project WHERE ProjectAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_project();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }

   //---------------------------------------------------------------------------

   // Each fulltext index has a load array method generated for it.

   //---------------------------------------------------------------------------

   // Each field with an index has a select distinct method generated for it.
   public function selectDistinctProjectName($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ProjectName ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ProjectName FROM project group by ProjectName order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ProjectName=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctProjectNumber($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ProjectNumber ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ProjectNumber FROM project group by ProjectNumber order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ProjectNumber=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' CreatedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, CreatedByAgentID FROM project group by CreatedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&CreatedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ModifiedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ModifiedByAgentID FROM project group by ModifiedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ModifiedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctProjectAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ProjectAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ProjectAgentID FROM project group by ProjectAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ProjectAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }

   public function keySelectDistinct($fieldname,$startline,$link,$endline,$includecount=false,$orderbycount=false) {
       $returnvalue = '';
       switch ($fieldname) { 
          case 'ProjectName':
             $returnvalue = $this->selectDistinctProjectName($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'ProjectNumber':
             $returnvalue = $this->selectDistinctProjectNumber($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'CreatedByAgentID':
             $returnvalue = $this->selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'ModifiedByAgentID':
             $returnvalue = $this->selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'ProjectAgentID':
             $returnvalue = $this->selectDistinctProjectAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
       }
       return $returnvalue;
    }

   //---------------------------------------------------------------------------

   public function hasField($fieldname) {
       $returnvalue = false;
       if (trim($fieldname)!='' && trim($fieldname)!=',') {
            if (strpos(self::FIELDLIST," $fieldname, ")!==false) { 
               $returnvalue = true;
            }
       }
       return $returnvalue;
    }
   //---------------------------------------------------------------------------

}


// Write your own views by extending this class.
// Place your extended views in a separate file and you
// can use Druid to regenerate the project.php file to reflect changes
// in the underlying database without overwriting your custom views of the data.
// 
class huh_projectView implements viewer
{
   var $model = null;
   public function setModel($aModel) { 
       $this->model = $aModel;
   }
   // @param $includeRelated default true shows rows from other tables through foreign key relationships.
   // @param $editLinkURL default '' allows adding a link to show this record in an editing form.
   public function getDetailsView($includeRelated=true, $editLinkURL='') {
       $returnvalue = '<ul>';
       $editLinkURL=trim($editLinkURL);
       $model = $this->model;
       $primarykeys = $model->schemaPK();
       if ($editLinkURL!='') { 
          if (!preg_match('/\&$/',$editLinkURL)) { $editLinkURL .= '&'; } 
          $nullpk = false; 
          foreach ($primarykeys as $primarykey) { 
              // Add fieldname=value pairs for primary key(s) to editLinkURL. 
              $editLinkURL .= urlencode($primarykey) . '=' . urlencode($model->keyGet($primarykey));
              if ($model->keyGet($primarykey)=='') { $nullpk = true; } 
          }
          if (!$nullpk) { $returnvalue .= "<li>huh_project <a href='$editLinkURL'>Edit</a></li>\n";  } 
       }
       $returnvalue .= "<li>".huh_project::PROJECTID.": ".$model->getProjectID()."</li>\n";
       $returnvalue .= "<li>".huh_project::TIMESTAMPCREATED.": ".$model->getTimestampCreated()."</li>\n";
       $returnvalue .= "<li>".huh_project::TIMESTAMPMODIFIED.": ".$model->getTimestampModified()."</li>\n";
       $returnvalue .= "<li>".huh_project::VERSION.": ".$model->getVersion()."</li>\n";
       $returnvalue .= "<li>".huh_project::COLLECTIONMEMBERID.": ".$model->getCollectionMemberID()."</li>\n";
       $returnvalue .= "<li>".huh_project::ENDDATE.": ".$model->getEndDate()."</li>\n";
       $returnvalue .= "<li>".huh_project::GRANTAGENCY.": ".$model->getGrantAgency()."</li>\n";
       $returnvalue .= "<li>".huh_project::GRANTNUMBER.": ".$model->getGrantNumber()."</li>\n";
       $returnvalue .= "<li>".huh_project::NUMBER1.": ".$model->getNumber1()."</li>\n";
       $returnvalue .= "<li>".huh_project::NUMBER2.": ".$model->getNumber2()."</li>\n";
       $returnvalue .= "<li>".huh_project::PROJECTDESCRIPTION.": ".$model->getProjectDescription()."</li>\n";
       $returnvalue .= "<li>".huh_project::PROJECTNAME.": ".$model->getProjectName()."</li>\n";
       $returnvalue .= "<li>".huh_project::PROJECTNUMBER.": ".$model->getProjectNumber()."</li>\n";
       $returnvalue .= "<li>".huh_project::REMARKS.": ".$model->getRemarks()."</li>\n";
       $returnvalue .= "<li>".huh_project::STARTDATE.": ".$model->getStartDate()."</li>\n";
       $returnvalue .= "<li>".huh_project::TEXT1.": ".$model->getText1()."</li>\n";
       $returnvalue .= "<li>".huh_project::TEXT2.": ".$model->getText2()."</li>\n";
       $returnvalue .= "<li>".huh_project::URL.": ".$model->getURL()."</li>\n";
       $returnvalue .= "<li>".huh_project::YESNO1.": ".$model->getYesNo1()."</li>\n";
       $returnvalue .= "<li>".huh_project::YESNO2.": ".$model->getYesNo2()."</li>\n";
       $returnvalue .= "<li>".huh_project::CREATEDBYAGENTID.": ".$model->getCreatedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_project::MODIFIEDBYAGENTID.": ".$model->getModifiedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_project::PROJECTAGENTID.": ".$model->getProjectAgentID()."</li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getCreatedByAgentID() != '') { 
               $t_agent->load($model->getCreatedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getModifiedByAgentID() != '') { 
               $t_agent->load($model->getModifiedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getProjectAgentID() != '') { 
               $t_agent->load($model->getProjectAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }

        }
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getJSON() {
       $returnvalue = '{ ';
       $model = $this->model;
       $returnvalue .= '"'.huh_project::PROJECTID.': "'.$model->getProjectID().'",';
       $returnvalue .= '"'.huh_project::TIMESTAMPCREATED.': "'.$model->getTimestampCreated().'",';
       $returnvalue .= '"'.huh_project::TIMESTAMPMODIFIED.': "'.$model->getTimestampModified().'",';
       $returnvalue .= '"'.huh_project::VERSION.': "'.$model->getVersion().'",';
       $returnvalue .= '"'.huh_project::COLLECTIONMEMBERID.': "'.$model->getCollectionMemberID().'",';
       $returnvalue .= '"'.huh_project::ENDDATE.': "'.$model->getEndDate().'",';
       $returnvalue .= '"'.huh_project::GRANTAGENCY.': "'.$model->getGrantAgency().'",';
       $returnvalue .= '"'.huh_project::GRANTNUMBER.': "'.$model->getGrantNumber().'",';
       $returnvalue .= '"'.huh_project::NUMBER1.': "'.$model->getNumber1().'",';
       $returnvalue .= '"'.huh_project::NUMBER2.': "'.$model->getNumber2().'",';
       $returnvalue .= '"'.huh_project::PROJECTDESCRIPTION.': "'.$model->getProjectDescription().'",';
       $returnvalue .= '"'.huh_project::PROJECTNAME.': "'.$model->getProjectName().'",';
       $returnvalue .= '"'.huh_project::PROJECTNUMBER.': "'.$model->getProjectNumber().'",';
       $returnvalue .= '"'.huh_project::REMARKS.': "'.$model->getRemarks().'",';
       $returnvalue .= '"'.huh_project::STARTDATE.': "'.$model->getStartDate().'",';
       $returnvalue .= '"'.huh_project::TEXT1.': "'.$model->getText1().'",';
       $returnvalue .= '"'.huh_project::TEXT2.': "'.$model->getText2().'",';
       $returnvalue .= '"'.huh_project::URL.': "'.$model->getURL().'",';
       $returnvalue .= '"'.huh_project::YESNO1.': "'.$model->getYesNo1().'",';
       $returnvalue .= '"'.huh_project::YESNO2.': "'.$model->getYesNo2().'",';
       $returnvalue .= '"'.huh_project::CREATEDBYAGENTID.': "'.$model->getCreatedByAgentID().'",';
       $returnvalue .= '"'.huh_project::MODIFIEDBYAGENTID.': "'.$model->getModifiedByAgentID().'",';
       $returnvalue .= '"'.huh_project::PROJECTAGENTID.': "'.$model->getProjectAgentID().'" }';
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getTableRowView() {
       $returnvalue = '<tr>';
       $model = $this->model;
       $returnvalue .= "<td>".$model->getProjectID()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampCreated()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampModified()."</td>\n";
       $returnvalue .= "<td>".$model->getVersion()."</td>\n";
       $returnvalue .= "<td>".$model->getCollectionMemberID()."</td>\n";
       $returnvalue .= "<td>".$model->getEndDate()."</td>\n";
       $returnvalue .= "<td>".$model->getGrantAgency()."</td>\n";
       $returnvalue .= "<td>".$model->getGrantNumber()."</td>\n";
       $returnvalue .= "<td>".$model->getNumber1()."</td>\n";
       $returnvalue .= "<td>".$model->getNumber2()."</td>\n";
       $returnvalue .= "<td>".$model->getProjectDescription()."</td>\n";
       $returnvalue .= "<td>".$model->getProjectName()."</td>\n";
       $returnvalue .= "<td>".$model->getProjectNumber()."</td>\n";
       $returnvalue .= "<td>".$model->getRemarks()."</td>\n";
       $returnvalue .= "<td>".$model->getStartDate()."</td>\n";
       $returnvalue .= "<td>".$model->getText1()."</td>\n";
       $returnvalue .= "<td>".$model->getText2()."</td>\n";
       $returnvalue .= "<td>".$model->getURL()."</td>\n";
       $returnvalue .= "<td>".$model->getYesNo1()."</td>\n";
       $returnvalue .= "<td>".$model->getYesNo2()."</td>\n";
       $returnvalue .= "<td>".$model->getCreatedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getModifiedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getProjectAgentID()."</td>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getHeaderRow() {
       $returnvalue = '<tr>';
       $returnvalue .= "<th>".huh_project::PROJECTID."</th>\n";
       $returnvalue .= "<th>".huh_project::TIMESTAMPCREATED."</th>\n";
       $returnvalue .= "<th>".huh_project::TIMESTAMPMODIFIED."</th>\n";
       $returnvalue .= "<th>".huh_project::VERSION."</th>\n";
       $returnvalue .= "<th>".huh_project::COLLECTIONMEMBERID."</th>\n";
       $returnvalue .= "<th>".huh_project::ENDDATE."</th>\n";
       $returnvalue .= "<th>".huh_project::GRANTAGENCY."</th>\n";
       $returnvalue .= "<th>".huh_project::GRANTNUMBER."</th>\n";
       $returnvalue .= "<th>".huh_project::NUMBER1."</th>\n";
       $returnvalue .= "<th>".huh_project::NUMBER2."</th>\n";
       $returnvalue .= "<th>".huh_project::PROJECTDESCRIPTION."</th>\n";
       $returnvalue .= "<th>".huh_project::PROJECTNAME."</th>\n";
       $returnvalue .= "<th>".huh_project::PROJECTNUMBER."</th>\n";
       $returnvalue .= "<th>".huh_project::REMARKS."</th>\n";
       $returnvalue .= "<th>".huh_project::STARTDATE."</th>\n";
       $returnvalue .= "<th>".huh_project::TEXT1."</th>\n";
       $returnvalue .= "<th>".huh_project::TEXT2."</th>\n";
       $returnvalue .= "<th>".huh_project::URL."</th>\n";
       $returnvalue .= "<th>".huh_project::YESNO1."</th>\n";
       $returnvalue .= "<th>".huh_project::YESNO2."</th>\n";
       $returnvalue .= "<th>".huh_project::CREATEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_project::MODIFIEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_project::PROJECTAGENTID."</th>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getEditFormDojoView($includeRelated=true) {
       $model = $this->model;
       if ($model->PK()=='') { $addform=true; } else { $addform=false; } 
       $returnvalue = '';
       $id = trim($model->PK());
       $feedback = "status$id";
       $formname = "editform$id";
       $script = '
  var saveprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function save'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Saving...";
     dojo.xhrGet(saveprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_project">';
       $returnvalue .= "<div id='div_$formnane' >";
       if($addform) { 
          $returnvalue .= "Add a new ProjectID"; 
       } else { 
         $returnvalue .= "<div><label for=".huh_project::PROJECTID.">PROJECTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_project::PROJECTID." id=".huh_project::PROJECTID." value='".$model->getProjectID()."'  style=' width:".huh_project::PROJECTID_SIZE ."em;  '  maxlength='".huh_project::PROJECTID_SIZE ."' ></div>\n";
       }  
       $returnvalue .= "<div><label for=".huh_project::TIMESTAMPCREATED.">TIMESTAMPCREATED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::TIMESTAMPCREATED." id=".huh_project::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  style=' width:".huh_project::TIMESTAMPCREATED_SIZE ."em;  '  maxlength='".huh_project::TIMESTAMPCREATED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::TIMESTAMPMODIFIED.">TIMESTAMPMODIFIED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::TIMESTAMPMODIFIED." id=".huh_project::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  style=' width:".huh_project::TIMESTAMPMODIFIED_SIZE ."em;  '  maxlength='".huh_project::TIMESTAMPMODIFIED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::VERSION.">VERSION</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_project::VERSION." id=".huh_project::VERSION." value='".$model->getVersion()."'  style=' width:".huh_project::VERSION_SIZE ."em;  '  maxlength='".huh_project::VERSION_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::COLLECTIONMEMBERID.">COLLECTIONMEMBERID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_project::COLLECTIONMEMBERID." id=".huh_project::COLLECTIONMEMBERID." value='".$model->getCollectionMemberID()."'  style=' width:".huh_project::COLLECTIONMEMBERID_SIZE ."em;  '  maxlength='".huh_project::COLLECTIONMEMBERID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::ENDDATE.">ENDDATE</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::ENDDATE." id=".huh_project::ENDDATE." value='".$model->getEndDate()."'  style=' width:".huh_project::ENDDATE_SIZE ."em;  '  maxlength='".huh_project::ENDDATE_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::GRANTAGENCY.">GRANTAGENCY</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::GRANTAGENCY." id=".huh_project::GRANTAGENCY." >".$model->getGrantAgency()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::GRANTNUMBER.">GRANTNUMBER</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::GRANTNUMBER." id=".huh_project::GRANTNUMBER." >".$model->getGrantNumber()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::NUMBER1.">NUMBER1</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::NUMBER1." id=".huh_project::NUMBER1." value='".$model->getNumber1()."'  style=' width:".huh_project::NUMBER1_SIZE ."em;  '  maxlength='".huh_project::NUMBER1_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::NUMBER2.">NUMBER2</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::NUMBER2." id=".huh_project::NUMBER2." value='".$model->getNumber2()."'  style=' width:".huh_project::NUMBER2_SIZE ."em;  '  maxlength='".huh_project::NUMBER2_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::PROJECTDESCRIPTION.">PROJECTDESCRIPTION</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::PROJECTDESCRIPTION." id=".huh_project::PROJECTDESCRIPTION." >".$model->getProjectDescription()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::PROJECTNAME.">PROJECTNAME</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::PROJECTNAME." id=".huh_project::PROJECTNAME." value='".$model->getProjectName()."'  style=' width:".huh_project::PROJECTNAME_SIZE ."em;  '  maxlength='".huh_project::PROJECTNAME_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::PROJECTNUMBER.">PROJECTNUMBER</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::PROJECTNUMBER." id=".huh_project::PROJECTNUMBER." >".$model->getProjectNumber()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::REMARKS.">REMARKS</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::REMARKS." id=".huh_project::REMARKS." >".$model->getRemarks()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::STARTDATE.">STARTDATE</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::STARTDATE." id=".huh_project::STARTDATE." value='".$model->getStartDate()."'  style=' width:".huh_project::STARTDATE_SIZE ."em;  '  maxlength='".huh_project::STARTDATE_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::TEXT1.">TEXT1</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::TEXT1." id=".huh_project::TEXT1." >".$model->getText1()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::TEXT2.">TEXT2</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::TEXT2." id=".huh_project::TEXT2." >".$model->getText2()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::URL.">URL</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_project::URL." id=".huh_project::URL." >".$model->getURL()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_project::YESNO1.">YESNO1</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::YESNO1." id=".huh_project::YESNO1." value='".$model->getYesNo1()."'  style=' width:".huh_project::YESNO1_SIZE ."em;  '  maxlength='".huh_project::YESNO1_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::YESNO2.">YESNO2</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_project::YESNO2." id=".huh_project::YESNO2." value='".$model->getYesNo2()."'  style=' width:".huh_project::YESNO2_SIZE ."em;  '  maxlength='".huh_project::YESNO2_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::CREATEDBYAGENTID.">CREATEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_project::CREATEDBYAGENTID." id=".huh_project::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  style=' width:".huh_project::CREATEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_project::CREATEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::MODIFIEDBYAGENTID.">MODIFIEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_project::MODIFIEDBYAGENTID." id=".huh_project::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  style=' width:".huh_project::MODIFIEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_project::MODIFIEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_project::PROJECTAGENTID.">PROJECTAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_project::PROJECTAGENTID." id=".huh_project::PROJECTAGENTID." value='".$model->getProjectAgentID()."'  style=' width:".huh_project::PROJECTAGENTID_SIZE ."em;  '  maxlength='".huh_project::PROJECTAGENTID_SIZE ."' ></div>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= "<li><input name=save id=save type=button value='Save' onclick='$script  save$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</div>';
       $returnvalue .= '</form>';
       if(!$addform) { 
          // show delete button if editing an existing record 
       $id = trim($model->PK());
       $feedback = "deletestatus$id";
       $formname = "deleteform$id";
       $script = '
  var deleteprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function deleterecord'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Deleting...";
     dojo.xhrGet(deleteprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=delete>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_table value="huh_project">';
       $returnvalue .= '<input type=hidden name=ProjectID id=druid_table value="'.$id.'">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li><input name=delete id=save type=button value='Delete' onclick='$script  deleterecord$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       } 
       return  $returnvalue;
   }
   public function getEditFormView($includeRelated=true) {
       $model = $this->model;
       $returnvalue = '<form method=get action=druid_handler.php>';
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_project">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li>PROJECTID<input type=text name=".huh_project::PROJECTID." id=".huh_project::PROJECTID." value='".$model->getProjectID()."'  size='".huh_project::PROJECTID_SIZE ."'  maxlength='".huh_project::PROJECTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPCREATED<input type=text name=".huh_project::TIMESTAMPCREATED." id=".huh_project::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  size='".huh_project::TIMESTAMPCREATED_SIZE ."'  maxlength='".huh_project::TIMESTAMPCREATED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPMODIFIED<input type=text name=".huh_project::TIMESTAMPMODIFIED." id=".huh_project::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  size='".huh_project::TIMESTAMPMODIFIED_SIZE ."'  maxlength='".huh_project::TIMESTAMPMODIFIED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VERSION<input type=text name=".huh_project::VERSION." id=".huh_project::VERSION." value='".$model->getVersion()."'  size='".huh_project::VERSION_SIZE ."'  maxlength='".huh_project::VERSION_SIZE ."' ></li>\n";
       $returnvalue .= "<li>COLLECTIONMEMBERID<input type=text name=".huh_project::COLLECTIONMEMBERID." id=".huh_project::COLLECTIONMEMBERID." value='".$model->getCollectionMemberID()."'  size='".huh_project::COLLECTIONMEMBERID_SIZE ."'  maxlength='".huh_project::COLLECTIONMEMBERID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>ENDDATE<input type=text name=".huh_project::ENDDATE." id=".huh_project::ENDDATE." value='".$model->getEndDate()."'  size='".huh_project::ENDDATE_SIZE ."'  maxlength='".huh_project::ENDDATE_SIZE ."' ></li>\n";
       $returnvalue .= "<li>GRANTAGENCY<input type=text name=".huh_project::GRANTAGENCY." id=".huh_project::GRANTAGENCY." value='".$model->getGrantAgency()."'  size='51'  maxlength='".huh_project::GRANTAGENCY_SIZE ."' ></li>\n";
       $returnvalue .= "<li>GRANTNUMBER<input type=text name=".huh_project::GRANTNUMBER." id=".huh_project::GRANTNUMBER." value='".$model->getGrantNumber()."'  size='51'  maxlength='".huh_project::GRANTNUMBER_SIZE ."' ></li>\n";
       $returnvalue .= "<li>NUMBER1<input type=text name=".huh_project::NUMBER1." id=".huh_project::NUMBER1." value='".$model->getNumber1()."'  size='".huh_project::NUMBER1_SIZE ."'  maxlength='".huh_project::NUMBER1_SIZE ."' ></li>\n";
       $returnvalue .= "<li>NUMBER2<input type=text name=".huh_project::NUMBER2." id=".huh_project::NUMBER2." value='".$model->getNumber2()."'  size='".huh_project::NUMBER2_SIZE ."'  maxlength='".huh_project::NUMBER2_SIZE ."' ></li>\n";
       $returnvalue .= "<li>PROJECTDESCRIPTION<input type=text name=".huh_project::PROJECTDESCRIPTION." id=".huh_project::PROJECTDESCRIPTION." value='".$model->getProjectDescription()."'  size='51'  maxlength='".huh_project::PROJECTDESCRIPTION_SIZE ."' ></li>\n";
       $returnvalue .= "<li>PROJECTNAME<input type=text name=".huh_project::PROJECTNAME." id=".huh_project::PROJECTNAME." value='".$model->getProjectName()."'  size='".huh_project::PROJECTNAME_SIZE ."'  maxlength='".huh_project::PROJECTNAME_SIZE ."' ></li>\n";
       $returnvalue .= "<li>PROJECTNUMBER<input type=text name=".huh_project::PROJECTNUMBER." id=".huh_project::PROJECTNUMBER." value='".$model->getProjectNumber()."'  size='51'  maxlength='".huh_project::PROJECTNUMBER_SIZE ."' ></li>\n";
       $returnvalue .= "<li>REMARKS<input type=text name=".huh_project::REMARKS." id=".huh_project::REMARKS." value='".$model->getRemarks()."'  size='51'  maxlength='".huh_project::REMARKS_SIZE ."' ></li>\n";
       $returnvalue .= "<li>STARTDATE<input type=text name=".huh_project::STARTDATE." id=".huh_project::STARTDATE." value='".$model->getStartDate()."'  size='".huh_project::STARTDATE_SIZE ."'  maxlength='".huh_project::STARTDATE_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TEXT1<input type=text name=".huh_project::TEXT1." id=".huh_project::TEXT1." value='".$model->getText1()."'  size='51'  maxlength='".huh_project::TEXT1_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TEXT2<input type=text name=".huh_project::TEXT2." id=".huh_project::TEXT2." value='".$model->getText2()."'  size='51'  maxlength='".huh_project::TEXT2_SIZE ."' ></li>\n";
       $returnvalue .= "<li>URL<input type=text name=".huh_project::URL." id=".huh_project::URL." value='".$model->getURL()."'  size='51'  maxlength='".huh_project::URL_SIZE ."' ></li>\n";
       $returnvalue .= "<li>YESNO1<input type=text name=".huh_project::YESNO1." id=".huh_project::YESNO1." value='".$model->getYesNo1()."'  size='".huh_project::YESNO1_SIZE ."'  maxlength='".huh_project::YESNO1_SIZE ."' ></li>\n";
       $returnvalue .= "<li>YESNO2<input type=text name=".huh_project::YESNO2." id=".huh_project::YESNO2." value='".$model->getYesNo2()."'  size='".huh_project::YESNO2_SIZE ."'  maxlength='".huh_project::YESNO2_SIZE ."' ></li>\n";
       $returnvalue .= "<li>CREATEDBYAGENTID<input type=text name=".huh_project::CREATEDBYAGENTID." id=".huh_project::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  size='".huh_project::CREATEDBYAGENTID_SIZE ."'  maxlength='".huh_project::CREATEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>MODIFIEDBYAGENTID<input type=text name=".huh_project::MODIFIEDBYAGENTID." id=".huh_project::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  size='".huh_project::MODIFIEDBYAGENTID_SIZE ."'  maxlength='".huh_project::MODIFIEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>PROJECTAGENTID<input type=text name=".huh_project::PROJECTAGENTID." id=".huh_project::PROJECTAGENTID." value='".$model->getProjectAgentID()."'  size='".huh_project::PROJECTAGENTID_SIZE ."'  maxlength='".huh_project::PROJECTAGENTID_SIZE ."' ></li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= '<li><input type=submit value="Save"></li>';
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       return  $returnvalue;
   }
}

//==============================================================================
?>
