<?php
//==============================================================================
//===   agentvariant.php                         
//===   Autogenerated by Druid from MySQL db Build:6
//==============================================================================

include_once("druid_interfaces.php");

class huh_agentvariant implements  model , loadableModel, saveableModel, tableSchema 
{
   // These constants hold the sizes the fields in this table in the database.
   const AGENTVARIANTID_SIZE  = 11; //INTEGER
   const TIMESTAMPCREATED_SIZE = 21; //TIMESTAMP
   const TIMESTAMPMODIFIED_SIZE = 21; //TIMESTAMP
   const VERSION_SIZE         = 11; //INTEGER
   const COUNTRY_SIZE         = 2; //2
   const LANGUAGE_SIZE        = 2; //2
   const NAME_SIZE            = 255; //255
   const VARTYPE_SIZE         = 4; //TINYINT
   const VARIANT_SIZE         = 2; //2
   const MODIFIEDBYAGENTID_SIZE = 11; //INTEGER
   const AGENTID_SIZE         = 11; //INTEGER
   const CREATEDBYAGENTID_SIZE = 11; //INTEGER
    // These constants hold the field names of the table in the database. 
   const AGENTVARIANTID    = 'AgentVariantID';
   const TIMESTAMPCREATED  = 'TimestampCreated';
   const TIMESTAMPMODIFIED = 'TimestampModified';
   const VERSION           = 'Version';
   const COUNTRY           = 'Country';
   const LANGUAGE          = 'Language';
   const NAME              = 'Name';
   const VARTYPE           = 'VarType';
   const VARIANT           = 'Variant';
   const MODIFIEDBYAGENTID = 'ModifiedByAgentID';
   const AGENTID           = 'AgentID';
   const CREATEDBYAGENTID  = 'CreatedByAgentID';

   //---------------------------------------------------------------------------

   // interface tableSchema implementation
   // schemaPK returns array of primary key field names
   public function schemaPK() {
       return $this->primaryKeyArray;
   } 
   // schemaHaveDistinct returns array of field names for which selectDistinct{fieldname} methods are available.
   public function schemaHaveDistinct() {
       return $this->selectDistinctFieldsArray;
   } 
   // schemaFields returns array of all field names
   public function schemaFields() { 
       return $this->allFieldsArray;
   } 
/*  Example sanitized retrieval of variable matching object variables from $_GET 
/*  Customize these to limit each variable to narrowest possible set of known good values. 

  $AgentVariantID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['AgentVariantID']), 0, 11);
  $TimestampCreated = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampCreated']), 0, 21);
  $TimestampModified = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampModified']), 0, 21);
  $Version = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Version']), 0, 11);
  $Country = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Country']), 0, 2);
  $Language = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Language']), 0, 2);
  $Name = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Name']), 0, 255);
  $VarType = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['VarType']), 0, 4);
  $Variant = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Variant']), 0, 2);
  $ModifiedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ModifiedByAgentID']), 0, 11);
  $AgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['AgentID']), 0, 11);
  $CreatedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['CreatedByAgentID']), 0, 11);
*/

   //---------------------------------------------------------------------------

   private $AgentVariantID; // PK INTEGER 
   private $TimestampCreated; // TIMESTAMP 
   private $TimestampModified; // TIMESTAMP 
   private $Version; // INTEGER 
   private $Country; // VARCHAR(2) 
   private $Language; // VARCHAR(2) 
   private $Name; // VARCHAR(255) 
   private $VarType; // TINYINT 
   private $Variant; // VARCHAR(2) 
   private $ModifiedByAgentID; // INTEGER 
   private $AgentID; // INTEGER 
   private $CreatedByAgentID; // INTEGER 
   private $dirty;
   private $loaded;
   private $error;
   const FIELDLIST = ' AgentVariantID, TimestampCreated, TimestampModified, Version, Country, Language, Name, VarType, Variant, ModifiedByAgentID, AgentID, CreatedByAgentID, ';
   const PKFIELDLIST = ' AgentVariantID, ';
   const NUMBER_OF_PRIMARY_KEYS = 1;
   private $primaryKeyArray = array( 1 => 'AgentVariantID'  ) ;
   private $allFieldsArray = array( 0 => 'AgentVariantID' , 1 => 'TimestampCreated' , 2 => 'TimestampModified' , 3 => 'Version' , 4 => 'Country' , 5 => 'Language' , 6 => 'Name' , 7 => 'VarType' , 8 => 'Variant' , 9 => 'ModifiedByAgentID' , 10 => 'AgentID' , 11 => 'CreatedByAgentID'  ) ;
   private $selectDistinctFieldsArray = array( 6 => 'Name' , 9 => 'ModifiedByAgentID' , 10 => 'AgentID' , 11 => 'CreatedByAgentID'  ) ;

   //---------------------------------------------------------------------------

   // constructor 
   function huh_agentvariant(){
       $this->AgentVariantID = NULL;
       $this->TimestampCreated = '';
       $this->TimestampModified = '';
       $this->Version = '';
       $this->Country = '';
       $this->Language = '';
       $this->Name = '';
       $this->VarType = '';
       $this->Variant = '';
       $this->ModifiedByAgentID = '';
       $this->AgentID = '';
       $this->CreatedByAgentID = '';
       $this->dirty = false;
       $this->loaded = false;
       $this->error = '';
   }

   private function l_addslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = addslashes($value);
      }
      return $retval;
   }
   private function l_stripslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = stripslashes($value);
      }
      return $retval;
   }
   public function isDirty() {
       return $this->dirty;
   }
   public function isLoaded() {
       return $this->loaded;
   }
   public function errorMessage() {
       return $this->error;
   }

   //---------------------------------------------------------------------------

   public function keyValueSet($fieldname,$value) {
       $returnvalue = false;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='AgentVariantID') { $returnvalue = $this->setAgentVariantID($value); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->setTimestampCreated($value); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->setTimestampModified($value); } 
             if ($fieldname=='Version') { $returnvalue = $this->setVersion($value); } 
             if ($fieldname=='Country') { $returnvalue = $this->setCountry($value); } 
             if ($fieldname=='Language') { $returnvalue = $this->setLanguage($value); } 
             if ($fieldname=='Name') { $returnvalue = $this->setName($value); } 
             if ($fieldname=='VarType') { $returnvalue = $this->setVarType($value); } 
             if ($fieldname=='Variant') { $returnvalue = $this->setVariant($value); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->setModifiedByAgentID($value); } 
             if ($fieldname=='AgentID') { $returnvalue = $this->setAgentID($value); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->setCreatedByAgentID($value); } 
             $returnvalue = true;
          }
          catch (exception $e) { ;
              $returnvalue = false;
              throw new Exception('Field Set Error'.$e->getMessage()); 
          }
       } else { 
          throw new Exception('No Such field'); 
       }  
       return $returnvalue;
   }
   public function keyGet($fieldname) {
       $returnvalue = null;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='AgentVariantID') { $returnvalue = $this->getAgentVariantID(); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->getTimestampCreated(); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->getTimestampModified(); } 
             if ($fieldname=='Version') { $returnvalue = $this->getVersion(); } 
             if ($fieldname=='Country') { $returnvalue = $this->getCountry(); } 
             if ($fieldname=='Language') { $returnvalue = $this->getLanguage(); } 
             if ($fieldname=='Name') { $returnvalue = $this->getName(); } 
             if ($fieldname=='VarType') { $returnvalue = $this->getVarType(); } 
             if ($fieldname=='Variant') { $returnvalue = $this->getVariant(); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->getModifiedByAgentID(); } 
             if ($fieldname=='AgentID') { $returnvalue = $this->getAgentID(); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->getCreatedByAgentID(); } 
          }
          catch (exception $e) { ;
              $returnvalue = null;
          }
       }
       return $returnvalue;
   }
/*AgentVariantID*/
   public function getAgentVariantID() {
       if ($this->AgentVariantID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->AgentVariantID));
       }
   }
   public function setAgentVariantID($AgentVariantID) {
       if (strlen(preg_replace('/[^0-9]/','',$AgentVariantID)) > huh_agentvariant::AGENTVARIANTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $AgentVariantID = trim($AgentVariantID);
       if (!ctype_digit(strval($AgentVariantID)) && trim(strval($AgentVariantID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->AgentVariantID = $this->l_addslashes($AgentVariantID);
       $this->dirty = true;
   }
/*TimestampCreated*/
   public function getTimestampCreated() {
       if ($this->TimestampCreated==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampCreated));
       }
   }
   public function setTimestampCreated($TimestampCreated) {
       if (strlen($TimestampCreated) > huh_agentvariant::TIMESTAMPCREATED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampCreated = $this->l_addslashes($TimestampCreated);
       $this->dirty = true;
   }
/*TimestampModified*/
   public function getTimestampModified() {
       if ($this->TimestampModified==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampModified));
       }
   }
   public function setTimestampModified($TimestampModified) {
       if (strlen($TimestampModified) > huh_agentvariant::TIMESTAMPMODIFIED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampModified = $this->l_addslashes($TimestampModified);
       $this->dirty = true;
   }
/*Version*/
   public function getVersion() {
       if ($this->Version==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Version));
       }
   }
   public function setVersion($Version) {
       if (strlen(preg_replace('/[^0-9]/','',$Version)) > huh_agentvariant::VERSION_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Version = trim($Version);
       if (!ctype_digit(strval($Version)) && trim(strval($Version))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Version = $this->l_addslashes($Version);
       $this->dirty = true;
   }
/*Country*/
   public function getCountry() {
       if ($this->Country==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Country));
       }
   }
   public function setCountry($Country) {
       if (strlen($Country) > huh_agentvariant::COUNTRY_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Country = $this->l_addslashes($Country);
       $this->dirty = true;
   }
/*Language*/
   public function getLanguage() {
       if ($this->Language==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Language));
       }
   }
   public function setLanguage($Language) {
       if (strlen($Language) > huh_agentvariant::LANGUAGE_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Language = $this->l_addslashes($Language);
       $this->dirty = true;
   }
/*Name*/
   public function getName() {
       if ($this->Name==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Name));
       }
   }
   public function setName($Name) {
       if (strlen($Name) > huh_agentvariant::NAME_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Name = $this->l_addslashes($Name);
       $this->dirty = true;
   }
/*VarType*/
   public function getVarType() {
       if ($this->VarType==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->VarType));
       }
   }
   public function setVarType($VarType) {
       if (strlen($VarType) > huh_agentvariant::VARTYPE_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->VarType = $this->l_addslashes($VarType);
       $this->dirty = true;
   }
/*Variant*/
   public function getVariant() {
       if ($this->Variant==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Variant));
       }
   }
   public function setVariant($Variant) {
       if (strlen($Variant) > huh_agentvariant::VARIANT_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Variant = $this->l_addslashes($Variant);
       $this->dirty = true;
   }
/*ModifiedByAgentID*/
   public function getModifiedByAgentID() {
       if ($this->ModifiedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ModifiedByAgentID));
       }
   }
   public function setModifiedByAgentID($ModifiedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$ModifiedByAgentID)) > huh_agentvariant::MODIFIEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ModifiedByAgentID = trim($ModifiedByAgentID);
       if (!ctype_digit(strval($ModifiedByAgentID)) && trim(strval($ModifiedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ModifiedByAgentID = $this->l_addslashes($ModifiedByAgentID);
       $this->dirty = true;
   }
/*AgentID*/
   public function getAgentID() {
       if ($this->AgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->AgentID));
       }
   }
   public function setAgentID($AgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$AgentID)) > huh_agentvariant::AGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $AgentID = trim($AgentID);
       if (!ctype_digit(strval($AgentID))) {
             throw new Exception("Value must be an integer");
       }
       $this->AgentID = $this->l_addslashes($AgentID);
       $this->dirty = true;
   }
/*CreatedByAgentID*/
   public function getCreatedByAgentID() {
       if ($this->CreatedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->CreatedByAgentID));
       }
   }
   public function setCreatedByAgentID($CreatedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$CreatedByAgentID)) > huh_agentvariant::CREATEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $CreatedByAgentID = trim($CreatedByAgentID);
       if (!ctype_digit(strval($CreatedByAgentID)) && trim(strval($CreatedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->CreatedByAgentID = $this->l_addslashes($CreatedByAgentID);
       $this->dirty = true;
   }
   public function PK() { // get value of primary key 
        $returnvalue = '';
        $returnvalue .= $this->getAgentVariantID();
        return $returnvalue;
   }
   public function PKArray() { // get name and value of primary key fields 
        $returnvalue = array();
        $returnvalue['AgentVariantID'] = $this->getAgentVariantID();
        return $returnvalue;
   }
   public function NumberOfPrimaryKeyFields() { // returns the number of primary key fields defined for this table 
        return 1;
   }

   // Constants holding the mysqli field type character (s,i,d) for each field
  const C_AgentVariantIDMYSQLI_TYPE = 'i';
  const C_TimestampCreatedMYSQLI_TYPE = 's';
  const C_TimestampModifiedMYSQLI_TYPE = 's';
  const C_VersionMYSQLI_TYPE = 'i';
  const C_CountryMYSQLI_TYPE = 's';
  const C_LanguageMYSQLI_TYPE = 's';
  const C_NameMYSQLI_TYPE = 's';
  const C_VarTypeMYSQLI_TYPE = 'i';
  const C_VariantMYSQLI_TYPE = 's';
  const C_ModifiedByAgentIDMYSQLI_TYPE = 'i';
  const C_AgentIDMYSQLI_TYPE = 'i';
  const C_CreatedByAgentIDMYSQLI_TYPE = 'i';

   // function to obtain the mysqli field type character from a fieldname
   public function MySQLiFieldType($aFieldname) { 
      $retval = '';
      if ($aFieldname=='AgentVariantID') { $retval = self::C_AgentVariantIDMYSQLI_TYPE; }
      if ($aFieldname=='TimestampCreated') { $retval = self::C_TimestampCreatedMYSQLI_TYPE; }
      if ($aFieldname=='TimestampModified') { $retval = self::C_TimestampModifiedMYSQLI_TYPE; }
      if ($aFieldname=='Version') { $retval = self::C_VersionMYSQLI_TYPE; }
      if ($aFieldname=='Country') { $retval = self::C_CountryMYSQLI_TYPE; }
      if ($aFieldname=='Language') { $retval = self::C_LanguageMYSQLI_TYPE; }
      if ($aFieldname=='Name') { $retval = self::C_NameMYSQLI_TYPE; }
      if ($aFieldname=='VarType') { $retval = self::C_VarTypeMYSQLI_TYPE; }
      if ($aFieldname=='Variant') { $retval = self::C_VariantMYSQLI_TYPE; }
      if ($aFieldname=='ModifiedByAgentID') { $retval = self::C_ModifiedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='AgentID') { $retval = self::C_AgentIDMYSQLI_TYPE; }
      if ($aFieldname=='CreatedByAgentID') { $retval = self::C_CreatedByAgentIDMYSQLI_TYPE; }
      return $retval;
   }

   // Function load() can take either the value of the primary key which uniquely identifies a particular row
   // or an array of array('primarykeyfieldname'=>'value') in the case of a single field primary key
   // or an array of fieldname value pairs in the case of multiple field primary key.
   public function load($pk) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        try {
             if (is_array($pk)) { 
                 $this->setAgentVariantID($pk[AgentVariantID]);
             } else { ;
                 $this->setAgentVariantID($pk);
             };
        } 
        catch (Exception $e) { 
             throw new Exception($e->getMessage());
        }
        if($this->AgentVariantID != NULL) {
           $sql = 'SELECT AgentVariantID, TimestampCreated, TimestampModified, Version, Country, Language, Name, VarType, Variant, ModifiedByAgentID, AgentID, CreatedByAgentID FROM agentvariant WHERE AgentVariantID = '.$this->AgentVariantID ;

           $preparesql = 'SELECT AgentVariantID, TimestampCreated, TimestampModified, Version, Country, Language, Name, VarType, Variant, ModifiedByAgentID, AgentID, CreatedByAgentID FROM agentvariant WHERE AgentVariantID = ? ';

           if ($statement = $connection->prepare($preparesql)) { 
              $statement->bind_param("i", $this->AgentVariantID);
              $statement->execute();
              $statement->bind_result($this->AgentVariantID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Country, $this->Language, $this->Name, $this->VarType, $this->Variant, $this->ModifiedByAgentID, $this->AgentID, $this->CreatedByAgentID);
              $statement->fetch();
              $statement->close();
           }

            $this->loaded = true;
            $this->dirty = false;
        } else { 
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   // Function save() will either save the current record or insert a new record.
   // Inserts new record if the primary key field in this table is null 
   // for this instance of this object.
   // Otherwise updates the record identified by the primary key value.
   public function save() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        // Test to see if this is an insert or update.
        if ($this->AgentVariantID!= NULL) {
            $sql  = 'UPDATE  agentvariant SET ';
            $isInsert = false;
            $sql .=  "TimestampCreated = ? ";
            $sql .=  ", TimestampModified = ? ";
            $sql .=  ", Version = ? ";
            $sql .=  ", Country = ? ";
            $sql .=  ", Language = ? ";
            $sql .=  ", Name = ? ";
            $sql .=  ", VarType = ? ";
            $sql .=  ", Variant = ? ";
            $sql .=  ", ModifiedByAgentID = ? ";
            $sql .=  ", AgentID = ? ";
            $sql .=  ", CreatedByAgentID = ? ";

            $sql .= "  WHERE AgentVariantID = ? ";
        } else {
            $sql  = 'INSERT INTO agentvariant ';
            $isInsert = true;
if ($this->PK==NULL) { throw new Exception('Can\'t insert record with null primary key for this table'); }
            $sql .= '( AgentVariantID ,  TimestampCreated ,  TimestampModified ,  Version ,  Country ,  Language ,  Name ,  VarType ,  Variant ,  ModifiedByAgentID ,  AgentID ,  CreatedByAgentID ) VALUES (';
            $sql .=  "  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .= ')';

        }
        if ($statement = $connection->prepare($sql)) { 
           if ($this->AgentVariantID!= NULL ) {
              $statement->bind_param("ississsisiiii", $this->AgentVariantID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->Country , $this->Language , $this->Name , $this->VarType , $this->Variant , $this->ModifiedByAgentID , $this->AgentID , $this->CreatedByAgentID , $this->AgentVariantID );
           } else { 
              $statement->bind_param("ississsisiii", $this->AgentVariantID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->Country , $this->Language , $this->Name , $this->VarType , $this->Variant , $this->ModifiedByAgentID , $this->AgentID , $this->CreatedByAgentID );
           } 
           $statement->execute();
           if ($statement->num_rows()!=1) {
               $this->error = $statement->error; 
           }
           $statement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }
        if ($this->error=='') { 
            $returnvalue = true;
        };

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function delete() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        if($this->AgentVariantID != NULL) {
           $sql = 'SELECT AgentVariantID, TimestampCreated, TimestampModified, Version, Country, Language, Name, VarType, Variant, ModifiedByAgentID, AgentID, CreatedByAgentID FROM agentvariant WHERE AgentVariantID = "'.$this->AgentVariantID.'"  ' ;

           $preparedsql = 'SELECT  FROM agentvariant WHERE  and AgentVariantID = ?  ' ;
        if ($statement = $connection->prepare($preparedsql)) { 
           $statement->bind_param("ississsisiii", $this->AgentVariantID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Country, $this->Language, $this->Name, $this->VarType, $this->Variant, $this->ModifiedByAgentID, $this->AgentID, $this->CreatedByAgentID);
           $statement->execute();
           $statement->store_result();
           if ($statement->num_rows()==1) {
                $sql = 'DELETE FROM agentvariant WHERE  and AgentVariantID = ?  ';
                if ($stmt_delete = $connection->prepare($sql)) { 
                   $stmt_delete->bind_param("ississsisiii", $this->AgentVariantID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Country, $this->Language, $this->Name, $this->VarType, $this->Variant, $this->ModifiedByAgentID, $this->AgentID, $this->CreatedByAgentID);
                   if ($stmnt_delete->execute()) { 
                       $returnvalue = true;
                   } else {
                       $this->error = mysqli_error($connection); 
                   }
                   $stmt_delete->close();
                }
           } else { 
               $this->error = mysqli_error($connection); 
           }
           $tatement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }

            $this->loaded = true;
            // record was deleted, so set PK to null
            $this->AgentVariantID = NULL; 
        } else { 
           throw new Exception('Unable to identify which record to delete, primary key is not set');
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function count() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        $sql = 'SELECT count(*)  FROM agentvariant';
        if ($result = $connection->query($sql)) { 
           if ($result->num_rows()==1) {
             $row = $result->fetch_row();
             if ($row) {
                $returnvalue = $row[0];
             }
           }
        } else { 
           $this->error = mysqli_error($connection); 
        }
        mysqli_free_result($result);

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function loadArrayKeyValueSearch($searchTermArray) {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = array();
       $and = '';
       $wherebit = 'WHERE ';
       foreach($searchTermArray as $fieldname => $searchTerm) {
           if ($this->hasField($fieldname)) { 
               $operator = '='; 
               // change to a like search if a wildcard character is present
               if (!(strpos($searchTerm,'%')===false)) { $operator = 'like'; }
               if (!(strpos($searchTerm,'_')===false)) { $operator = 'like'; }
               if ($searchTerm=='[NULL]') { 
                   $wherebit .= "$and ($fieldname is null or $fieldname='') "; 
               } else { 
                   $wherebit .= "$and $fieldname $operator ? ";
                   $types = $types . $this->MySQLiFieldType($fieldname);
               } 
               $and = ' and ';
           }
       }
       $sql = "SELECT AgentVariantID FROM agentvariant $wherebit";
       if ($wherebit=='') { 
             $this->error = 'Error: No search terms provided';
       } else {
          $statement = $connection->prepare($sql);
          $vars = Array();
          $vars[] = $types;
          $i = 0;
          foreach ($searchTermArray as $value) { 
               $varname = 'bind'.$i;  // create a variable name
               $$varname = $value;    // using that variable name store the value 
               $vars[] = &$$varname;  // add a reference to the variable to the array
               $i++;
           }
           //$vars[] contains $types followed by references to variables holding each value in $searchTermArray.
          call_user_func_array(array($statement,'bind_param'),$vars);
          //$statement->bind_param($types,$names);
          $statement->execute();
          $statement->bind_result($id);
          $ids = array();
          while ($statement->fetch()) {
              $ids[] = $id;
          } // double loop to allow all data to be retrieved before preparing a new statement. 
          $statement->close();
          for ($i=0;$i<count($ids);$i++) {
              $obj = new huh_agentvariant();
              $obj->load($ids[$i]);
              $returnvalue[] = $obj;
              $result=true;
          }
          if ($result===false) { $this->error = mysqli_error($connection); }
       }
       return $returnvalue;
   }	

   //---------------------------------------------------------------------------

// TODO: *************** link to related tables 

   //---------------------------------------------------------------------------

  public function loadLinkedTo() { 
     $returnvalue = array(); 
       // fk: ModifiedByAgentID
      $t = new agent();
      $t->load(getModifiedByAgentID());
      $returnvalue[ModifiedByAgentID] = $t;
       // fk: AgentID
      $t = new agent();
      $t->load(getAgentID());
      $returnvalue[AgentID] = $t;
       // fk: CreatedByAgentID
      $t = new agent();
      $t->load(getCreatedByAgentID());
      $returnvalue[CreatedByAgentID] = $t;
     return $returnvalue;
  } 
   // Returns an array of primary key values (id) and concatenated values of all other fields (fields)
   // wrapped as $values in: '{ "identifier":"id", "items": [ '.$values.' ] }';
   // when druid_handler.php is called with druid_action=returnfkjson
   // Used with dojo dijit.form.FilteringSelect to submit surrogate numeric key values from a text picklist 
   public function keySelectAllConcatJSON($orderby='ASC') {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
       $returnvalue = '';
       $order = '';
       if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
       $sql = "SELECT AgentVariantID, concat(IFNULL(TimestampCreated,'') || ' ' || IFNULL(TimestampModified,'') || ' ' || IFNULL(Version,'') || ' ' || IFNULL(Country,'') || ' ' || IFNULL(Language,'') || ' ' || IFNULL(Name,'') || ' ' || IFNULL(VarType,'') || ' ' || IFNULL(Variant,'') || ' ' || IFNULL(ModifiedByAgentID,'') || ' ' || IFNULL(AgentID,'') || ' ' || IFNULL(CreatedByAgentID,'')) FROM agentvariant order by Name, ModifiedByAgentID, AgentID, CreatedByAgentID $order ";
       $comma = '';
       if ($result = $connection->query($sql)) { 
          while ($row = $result->fetch_row()) {
             if ($row) {
                $pkval = trim($row[0]);
                $fval = trim($row[1]);
                if ($pkval!='') { 
                    $pkval = str_replace('"','&quot;',$pkval);
                    $fval = str_replace('"','&quot;',$fval);
                    $returnvalue .= $comma . ' { "id":"'.$pkval.'", "fields": "'.$fval.'" } ';
                    $comma = ', ';
                }
             }
          }
       } else { 
          $this->error = mysqli_error(); 
       }
       $result->close();
       return $returnvalue;
   }
   //---------------------------------------------------------------------------

   public function keySelectDistinctJSON($field,$orderby='ASC') {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = '';
       if ($this->hasField($field)) { 
          $order = '';
          $fieldesc = mysql_escape_string($field);
          if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
          $preparemysql = "SELECT DISTINCT $fieldesc FROM agentvariant order by $fieldesc $order ";
          $comma = '';
         if ($stmt = $connection->prepare($preparemysql)) { 
             $stmt->execute();
             $stmt->bind_result($val);
             while ($stmt->fetch()) {
                $val = trim($val);                if ($val!='') { 
                    $val = str_replace('"','&quot;',$val);
                    $returnvalue .= $comma . ' { "'.$field.'":"'.$val.'" } ';
                    $comma = ', ';
                 }
             }
             $stmt->close();
         }
       }
       return $returnvalue;
   }
   //---------------------------------------------------------------------------


   //---------------------------------------------------------------------------

   // Each field with an index has a load array method generated for it.
   public function loadArrayByName($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentVariantID FROM agentvariant WHERE Name $operator '$searchTerm'";
        $preparedsql = "SELECT AgentVariantID FROM agentvariant WHERE Name $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentvariant();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByModifiedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentVariantID FROM agentvariant WHERE ModifiedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentVariantID FROM agentvariant WHERE ModifiedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentvariant();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentVariantID FROM agentvariant WHERE AgentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentVariantID FROM agentvariant WHERE AgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentvariant();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByCreatedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentVariantID FROM agentvariant WHERE CreatedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentVariantID FROM agentvariant WHERE CreatedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentvariant();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }

   //---------------------------------------------------------------------------

   // Each fulltext index has a load array method generated for it.

   //---------------------------------------------------------------------------

   // Each field with an index has a select distinct method generated for it.
   public function selectDistinctName($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' Name ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, Name FROM agentvariant group by Name order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&Name=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ModifiedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ModifiedByAgentID FROM agentvariant group by ModifiedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ModifiedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' AgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, AgentID FROM agentvariant group by AgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&AgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' CreatedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, CreatedByAgentID FROM agentvariant group by CreatedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&CreatedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }

   public function keySelectDistinct($fieldname,$startline,$link,$endline,$includecount=false,$orderbycount=false) {
       $returnvalue = '';
       switch ($fieldname) { 
          case 'Name':
             $returnvalue = $this->selectDistinctName($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'ModifiedByAgentID':
             $returnvalue = $this->selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'AgentID':
             $returnvalue = $this->selectDistinctAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'CreatedByAgentID':
             $returnvalue = $this->selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
       }
       return $returnvalue;
    }

   //---------------------------------------------------------------------------

   public function hasField($fieldname) {
       $returnvalue = false;
       if (trim($fieldname)!='' && trim($fieldname)!=',') {
            if (strpos(self::FIELDLIST," $fieldname, ")!==false) { 
               $returnvalue = true;
            }
       }
       return $returnvalue;
    }
   //---------------------------------------------------------------------------

}


// Write your own views by extending this class.
// Place your extended views in a separate file and you
// can use Druid to regenerate the agentvariant.php file to reflect changes
// in the underlying database without overwriting your custom views of the data.
// 
class huh_agentvariantView implements viewer
{
   var $model = null;
   public function setModel($aModel) { 
       $this->model = $aModel;
   }
   // @param $includeRelated default true shows rows from other tables through foreign key relationships.
   // @param $editLinkURL default '' allows adding a link to show this record in an editing form.
   public function getDetailsView($includeRelated=true, $editLinkURL='') {
       $returnvalue = '<ul>';
       $editLinkURL=trim($editLinkURL);
       $model = $this->model;
       $primarykeys = $model->schemaPK();
       if ($editLinkURL!='') { 
          if (!preg_match('/\&$/',$editLinkURL)) { $editLinkURL .= '&'; } 
          $nullpk = false; 
          foreach ($primarykeys as $primarykey) { 
              // Add fieldname=value pairs for primary key(s) to editLinkURL. 
              $editLinkURL .= urlencode($primarykey) . '=' . urlencode($model->keyGet($primarykey));
              if ($model->keyGet($primarykey)=='') { $nullpk = true; } 
          }
          if (!$nullpk) { $returnvalue .= "<li>huh_agentvariant <a href='$editLinkURL'>Edit</a></li>\n";  } 
       }
       $returnvalue .= "<li>".huh_agentvariant::AGENTVARIANTID.": ".$model->getAgentVariantID()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::TIMESTAMPCREATED.": ".$model->getTimestampCreated()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::TIMESTAMPMODIFIED.": ".$model->getTimestampModified()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::VERSION.": ".$model->getVersion()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::COUNTRY.": ".$model->getCountry()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::LANGUAGE.": ".$model->getLanguage()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::NAME.": ".$model->getName()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::VARTYPE.": ".$model->getVarType()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::VARIANT.": ".$model->getVariant()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::MODIFIEDBYAGENTID.": ".$model->getModifiedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::AGENTID.": ".$model->getAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_agentvariant::CREATEDBYAGENTID.": ".$model->getCreatedByAgentID()."</li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getModifiedByAgentID() != '') { 
               $t_agent->load($model->getModifiedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getAgentID() != '') { 
               $t_agent->load($model->getAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getCreatedByAgentID() != '') { 
               $t_agent->load($model->getCreatedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }

        }
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getJSON() {
       $returnvalue = '{ ';
       $model = $this->model;
       $returnvalue .= '"'.huh_agentvariant::AGENTVARIANTID.': "'.$model->getAgentVariantID().'",';
       $returnvalue .= '"'.huh_agentvariant::TIMESTAMPCREATED.': "'.$model->getTimestampCreated().'",';
       $returnvalue .= '"'.huh_agentvariant::TIMESTAMPMODIFIED.': "'.$model->getTimestampModified().'",';
       $returnvalue .= '"'.huh_agentvariant::VERSION.': "'.$model->getVersion().'",';
       $returnvalue .= '"'.huh_agentvariant::COUNTRY.': "'.$model->getCountry().'",';
       $returnvalue .= '"'.huh_agentvariant::LANGUAGE.': "'.$model->getLanguage().'",';
       $returnvalue .= '"'.huh_agentvariant::NAME.': "'.$model->getName().'",';
       $returnvalue .= '"'.huh_agentvariant::VARTYPE.': "'.$model->getVarType().'",';
       $returnvalue .= '"'.huh_agentvariant::VARIANT.': "'.$model->getVariant().'",';
       $returnvalue .= '"'.huh_agentvariant::MODIFIEDBYAGENTID.': "'.$model->getModifiedByAgentID().'",';
       $returnvalue .= '"'.huh_agentvariant::AGENTID.': "'.$model->getAgentID().'",';
       $returnvalue .= '"'.huh_agentvariant::CREATEDBYAGENTID.': "'.$model->getCreatedByAgentID().'" }';
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getTableRowView() {
       $returnvalue = '<tr>';
       $model = $this->model;
       $returnvalue .= "<td>".$model->getAgentVariantID()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampCreated()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampModified()."</td>\n";
       $returnvalue .= "<td>".$model->getVersion()."</td>\n";
       $returnvalue .= "<td>".$model->getCountry()."</td>\n";
       $returnvalue .= "<td>".$model->getLanguage()."</td>\n";
       $returnvalue .= "<td>".$model->getName()."</td>\n";
       $returnvalue .= "<td>".$model->getVarType()."</td>\n";
       $returnvalue .= "<td>".$model->getVariant()."</td>\n";
       $returnvalue .= "<td>".$model->getModifiedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getCreatedByAgentID()."</td>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getHeaderRow() {
       $returnvalue = '<tr>';
       $returnvalue .= "<th>".huh_agentvariant::AGENTVARIANTID."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::TIMESTAMPCREATED."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::TIMESTAMPMODIFIED."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::VERSION."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::COUNTRY."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::LANGUAGE."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::NAME."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::VARTYPE."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::VARIANT."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::MODIFIEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::AGENTID."</th>\n";
       $returnvalue .= "<th>".huh_agentvariant::CREATEDBYAGENTID."</th>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getEditFormDojoView($includeRelated=true) {
       $model = $this->model;
       if ($model->PK()=='') { $addform=true; } else { $addform=false; } 
       $returnvalue = '';
       $id = trim($model->PK());
       $feedback = "status$id";
       $formname = "editform$id";
       $script = '
  var saveprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function save'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Saving...";
     dojo.xhrGet(saveprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_agentvariant">';
       $returnvalue .= "<div id='div_$formnane' >";
       if($addform) { 
          $returnvalue .= "Add a new AgentVariantID"; 
       } else { 
         $returnvalue .= "<div><label for=".huh_agentvariant::AGENTVARIANTID.">AGENTVARIANTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentvariant::AGENTVARIANTID." id=".huh_agentvariant::AGENTVARIANTID." value='".$model->getAgentVariantID()."'  style=' width:".huh_agentvariant::AGENTVARIANTID_SIZE ."em;  '  maxlength='".huh_agentvariant::AGENTVARIANTID_SIZE ."' ></div>\n";
       }  
       $returnvalue .= "<div><label for=".huh_agentvariant::TIMESTAMPCREATED.">TIMESTAMPCREATED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentvariant::TIMESTAMPCREATED." id=".huh_agentvariant::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  style=' width:".huh_agentvariant::TIMESTAMPCREATED_SIZE ."em;  '  maxlength='".huh_agentvariant::TIMESTAMPCREATED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::TIMESTAMPMODIFIED.">TIMESTAMPMODIFIED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentvariant::TIMESTAMPMODIFIED." id=".huh_agentvariant::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  style=' width:".huh_agentvariant::TIMESTAMPMODIFIED_SIZE ."em;  '  maxlength='".huh_agentvariant::TIMESTAMPMODIFIED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::VERSION.">VERSION</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentvariant::VERSION." id=".huh_agentvariant::VERSION." value='".$model->getVersion()."'  style=' width:".huh_agentvariant::VERSION_SIZE ."em;  '  maxlength='".huh_agentvariant::VERSION_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::COUNTRY.">COUNTRY</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentvariant::COUNTRY." id=".huh_agentvariant::COUNTRY." value='".$model->getCountry()."'  style=' width:".huh_agentvariant::COUNTRY_SIZE ."em;  '  maxlength='".huh_agentvariant::COUNTRY_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::LANGUAGE.">LANGUAGE</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentvariant::LANGUAGE." id=".huh_agentvariant::LANGUAGE." value='".$model->getLanguage()."'  style=' width:".huh_agentvariant::LANGUAGE_SIZE ."em;  '  maxlength='".huh_agentvariant::LANGUAGE_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::NAME.">NAME</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_agentvariant::NAME." id=".huh_agentvariant::NAME." >".$model->getName()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::VARTYPE.">VARTYPE</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentvariant::VARTYPE." id=".huh_agentvariant::VARTYPE." value='".$model->getVarType()."'  style=' width:".huh_agentvariant::VARTYPE_SIZE ."em;  '  maxlength='".huh_agentvariant::VARTYPE_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::VARIANT.">VARIANT</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentvariant::VARIANT." id=".huh_agentvariant::VARIANT." value='".$model->getVariant()."'  style=' width:".huh_agentvariant::VARIANT_SIZE ."em;  '  maxlength='".huh_agentvariant::VARIANT_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::MODIFIEDBYAGENTID.">MODIFIEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentvariant::MODIFIEDBYAGENTID." id=".huh_agentvariant::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  style=' width:".huh_agentvariant::MODIFIEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_agentvariant::MODIFIEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::AGENTID.">AGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentvariant::AGENTID." id=".huh_agentvariant::AGENTID." value='".$model->getAgentID()."'  style=' width:".huh_agentvariant::AGENTID_SIZE ."em;  '  maxlength='".huh_agentvariant::AGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentvariant::CREATEDBYAGENTID.">CREATEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentvariant::CREATEDBYAGENTID." id=".huh_agentvariant::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  style=' width:".huh_agentvariant::CREATEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_agentvariant::CREATEDBYAGENTID_SIZE ."' ></div>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= "<li><input name=save id=save type=button value='Save' onclick='$script  save$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</div>';
       $returnvalue .= '</form>';
       if(!$addform) { 
          // show delete button if editing an existing record 
       $id = trim($model->PK());
       $feedback = "deletestatus$id";
       $formname = "deleteform$id";
       $script = '
  var deleteprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function deleterecord'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Deleting...";
     dojo.xhrGet(deleteprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=delete>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_table value="huh_agentvariant">';
       $returnvalue .= '<input type=hidden name=AgentVariantID id=druid_table value="'.$id.'">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li><input name=delete id=save type=button value='Delete' onclick='$script  deleterecord$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       } 
       return  $returnvalue;
   }
   public function getEditFormView($includeRelated=true) {
       $model = $this->model;
       $returnvalue = '<form method=get action=druid_handler.php>';
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_agentvariant">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li>AGENTVARIANTID<input type=text name=".huh_agentvariant::AGENTVARIANTID." id=".huh_agentvariant::AGENTVARIANTID." value='".$model->getAgentVariantID()."'  size='".huh_agentvariant::AGENTVARIANTID_SIZE ."'  maxlength='".huh_agentvariant::AGENTVARIANTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPCREATED<input type=text name=".huh_agentvariant::TIMESTAMPCREATED." id=".huh_agentvariant::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  size='".huh_agentvariant::TIMESTAMPCREATED_SIZE ."'  maxlength='".huh_agentvariant::TIMESTAMPCREATED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPMODIFIED<input type=text name=".huh_agentvariant::TIMESTAMPMODIFIED." id=".huh_agentvariant::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  size='".huh_agentvariant::TIMESTAMPMODIFIED_SIZE ."'  maxlength='".huh_agentvariant::TIMESTAMPMODIFIED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VERSION<input type=text name=".huh_agentvariant::VERSION." id=".huh_agentvariant::VERSION." value='".$model->getVersion()."'  size='".huh_agentvariant::VERSION_SIZE ."'  maxlength='".huh_agentvariant::VERSION_SIZE ."' ></li>\n";
       $returnvalue .= "<li>COUNTRY<input type=text name=".huh_agentvariant::COUNTRY." id=".huh_agentvariant::COUNTRY." value='".$model->getCountry()."'  size='".huh_agentvariant::COUNTRY_SIZE ."'  maxlength='".huh_agentvariant::COUNTRY_SIZE ."' ></li>\n";
       $returnvalue .= "<li>LANGUAGE<input type=text name=".huh_agentvariant::LANGUAGE." id=".huh_agentvariant::LANGUAGE." value='".$model->getLanguage()."'  size='".huh_agentvariant::LANGUAGE_SIZE ."'  maxlength='".huh_agentvariant::LANGUAGE_SIZE ."' ></li>\n";
       $returnvalue .= "<li>NAME<input type=text name=".huh_agentvariant::NAME." id=".huh_agentvariant::NAME." value='".$model->getName()."'  size='51'  maxlength='".huh_agentvariant::NAME_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VARTYPE<input type=text name=".huh_agentvariant::VARTYPE." id=".huh_agentvariant::VARTYPE." value='".$model->getVarType()."'  size='".huh_agentvariant::VARTYPE_SIZE ."'  maxlength='".huh_agentvariant::VARTYPE_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VARIANT<input type=text name=".huh_agentvariant::VARIANT." id=".huh_agentvariant::VARIANT." value='".$model->getVariant()."'  size='".huh_agentvariant::VARIANT_SIZE ."'  maxlength='".huh_agentvariant::VARIANT_SIZE ."' ></li>\n";
       $returnvalue .= "<li>MODIFIEDBYAGENTID<input type=text name=".huh_agentvariant::MODIFIEDBYAGENTID." id=".huh_agentvariant::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  size='".huh_agentvariant::MODIFIEDBYAGENTID_SIZE ."'  maxlength='".huh_agentvariant::MODIFIEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>AGENTID<input type=text name=".huh_agentvariant::AGENTID." id=".huh_agentvariant::AGENTID." value='".$model->getAgentID()."'  size='".huh_agentvariant::AGENTID_SIZE ."'  maxlength='".huh_agentvariant::AGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>CREATEDBYAGENTID<input type=text name=".huh_agentvariant::CREATEDBYAGENTID." id=".huh_agentvariant::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  size='".huh_agentvariant::CREATEDBYAGENTID_SIZE ."'  maxlength='".huh_agentvariant::CREATEDBYAGENTID_SIZE ."' ></li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= '<li><input type=submit value="Save"></li>';
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       return  $returnvalue;
   }
}

//==============================================================================
?>
