<?php
//==============================================================================
//===   fieldnotebookattachment.php                         
//===   Autogenerated by Druid from MySQL db Build:6
//==============================================================================

include_once("druid_interfaces.php");

class huh_fieldnotebookattachment implements  model , loadableModel, saveableModel, tableSchema 
{
   // These constants hold the sizes the fields in this table in the database.
   const FIELDNOTEBOOKATTACHMENTID_SIZE = 11; //INTEGER
   const TIMESTAMPCREATED_SIZE = 21; //TIMESTAMP
   const TIMESTAMPMODIFIED_SIZE = 21; //TIMESTAMP
   const VERSION_SIZE         = 11; //INTEGER
   const ORDINAL_SIZE         = 11; //INTEGER
   const REMARKS_SIZE         = 255; //LONGVARCHAR
   const FIELDNOTEBOOKID_SIZE = 11; //INTEGER
   const CREATEDBYAGENTID_SIZE = 11; //INTEGER
   const MODIFIEDBYAGENTID_SIZE = 11; //INTEGER
   const ATTACHMENTID_SIZE    = 11; //INTEGER
    // These constants hold the field names of the table in the database. 
   const FIELDNOTEBOOKATTACHMENTID = 'FieldNotebookAttachmentId';
   const TIMESTAMPCREATED  = 'TimestampCreated';
   const TIMESTAMPMODIFIED = 'TimestampModified';
   const VERSION           = 'Version';
   const ORDINAL           = 'Ordinal';
   const REMARKS           = 'Remarks';
   const FIELDNOTEBOOKID   = 'FieldNotebookID';
   const CREATEDBYAGENTID  = 'CreatedByAgentID';
   const MODIFIEDBYAGENTID = 'ModifiedByAgentID';
   const ATTACHMENTID      = 'AttachmentID';

   //---------------------------------------------------------------------------

   // interface tableSchema implementation
   // schemaPK returns array of primary key field names
   public function schemaPK() {
       return $this->primaryKeyArray;
   } 
   // schemaHaveDistinct returns array of field names for which selectDistinct{fieldname} methods are available.
   public function schemaHaveDistinct() {
       return $this->selectDistinctFieldsArray;
   } 
   // schemaFields returns array of all field names
   public function schemaFields() { 
       return $this->allFieldsArray;
   } 
/*  Example sanitized retrieval of variable matching object variables from $_GET 
/*  Customize these to limit each variable to narrowest possible set of known good values. 

  $FieldNotebookAttachmentId = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['FieldNotebookAttachmentId']), 0, 11);
  $TimestampCreated = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampCreated']), 0, 21);
  $TimestampModified = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampModified']), 0, 21);
  $Version = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Version']), 0, 11);
  $Ordinal = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Ordinal']), 0, 11);
  $Remarks = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Remarks']), 0, 255);
  $FieldNotebookID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['FieldNotebookID']), 0, 11);
  $CreatedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['CreatedByAgentID']), 0, 11);
  $ModifiedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ModifiedByAgentID']), 0, 11);
  $AttachmentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['AttachmentID']), 0, 11);
*/

   //---------------------------------------------------------------------------

   private $FieldNotebookAttachmentId; // PK INTEGER 
   private $TimestampCreated; // TIMESTAMP 
   private $TimestampModified; // TIMESTAMP 
   private $Version; // INTEGER 
   private $Ordinal; // INTEGER 
   private $Remarks; // LONGVARCHAR 
   private $FieldNotebookID; // INTEGER 
   private $CreatedByAgentID; // INTEGER 
   private $ModifiedByAgentID; // INTEGER 
   private $AttachmentID; // INTEGER 
   private $dirty;
   private $loaded;
   private $error;
   const FIELDLIST = ' FieldNotebookAttachmentId, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, FieldNotebookID, CreatedByAgentID, ModifiedByAgentID, AttachmentID, ';
   const PKFIELDLIST = ' FieldNotebookAttachmentId, ';
   const NUMBER_OF_PRIMARY_KEYS = 1;
   private $primaryKeyArray = array( 1 => 'FieldNotebookAttachmentId'  ) ;
   private $allFieldsArray = array( 0 => 'FieldNotebookAttachmentId' , 1 => 'TimestampCreated' , 2 => 'TimestampModified' , 3 => 'Version' , 4 => 'Ordinal' , 5 => 'Remarks' , 6 => 'FieldNotebookID' , 7 => 'CreatedByAgentID' , 8 => 'ModifiedByAgentID' , 9 => 'AttachmentID'  ) ;
   private $selectDistinctFieldsArray = array( 6 => 'FieldNotebookID' , 7 => 'CreatedByAgentID' , 8 => 'ModifiedByAgentID' , 9 => 'AttachmentID'  ) ;

   //---------------------------------------------------------------------------

   // constructor 
   function huh_fieldnotebookattachment(){
       $this->FieldNotebookAttachmentId = NULL;
       $this->TimestampCreated = '';
       $this->TimestampModified = '';
       $this->Version = '';
       $this->Ordinal = '';
       $this->Remarks = '';
       $this->FieldNotebookID = '';
       $this->CreatedByAgentID = '';
       $this->ModifiedByAgentID = '';
       $this->AttachmentID = '';
       $this->dirty = false;
       $this->loaded = false;
       $this->error = '';
   }

   private function l_addslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = addslashes($value);
      }
      return $retval;
   }
   private function l_stripslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = stripslashes($value);
      }
      return $retval;
   }
   public function isDirty() {
       return $this->dirty;
   }
   public function isLoaded() {
       return $this->loaded;
   }
   public function errorMessage() {
       return $this->error;
   }

   //---------------------------------------------------------------------------

   public function keyValueSet($fieldname,$value) {
       $returnvalue = false;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='FieldNotebookAttachmentId') { $returnvalue = $this->setFieldNotebookAttachmentId($value); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->setTimestampCreated($value); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->setTimestampModified($value); } 
             if ($fieldname=='Version') { $returnvalue = $this->setVersion($value); } 
             if ($fieldname=='Ordinal') { $returnvalue = $this->setOrdinal($value); } 
             if ($fieldname=='Remarks') { $returnvalue = $this->setRemarks($value); } 
             if ($fieldname=='FieldNotebookID') { $returnvalue = $this->setFieldNotebookID($value); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->setCreatedByAgentID($value); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->setModifiedByAgentID($value); } 
             if ($fieldname=='AttachmentID') { $returnvalue = $this->setAttachmentID($value); } 
             $returnvalue = true;
          }
          catch (exception $e) { ;
              $returnvalue = false;
              throw new Exception('Field Set Error'.$e->getMessage()); 
          }
       } else { 
          throw new Exception('No Such field'); 
       }  
       return $returnvalue;
   }
   public function keyGet($fieldname) {
       $returnvalue = null;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='FieldNotebookAttachmentId') { $returnvalue = $this->getFieldNotebookAttachmentId(); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->getTimestampCreated(); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->getTimestampModified(); } 
             if ($fieldname=='Version') { $returnvalue = $this->getVersion(); } 
             if ($fieldname=='Ordinal') { $returnvalue = $this->getOrdinal(); } 
             if ($fieldname=='Remarks') { $returnvalue = $this->getRemarks(); } 
             if ($fieldname=='FieldNotebookID') { $returnvalue = $this->getFieldNotebookID(); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->getCreatedByAgentID(); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->getModifiedByAgentID(); } 
             if ($fieldname=='AttachmentID') { $returnvalue = $this->getAttachmentID(); } 
          }
          catch (exception $e) { ;
              $returnvalue = null;
          }
       }
       return $returnvalue;
   }
/*FieldNotebookAttachmentId*/
   public function getFieldNotebookAttachmentId() {
       if ($this->FieldNotebookAttachmentId==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->FieldNotebookAttachmentId));
       }
   }
   public function setFieldNotebookAttachmentId($FieldNotebookAttachmentId) {
       if (strlen(preg_replace('/[^0-9]/','',$FieldNotebookAttachmentId)) > huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $FieldNotebookAttachmentId = trim($FieldNotebookAttachmentId);
       if (!ctype_digit(strval($FieldNotebookAttachmentId)) && trim(strval($FieldNotebookAttachmentId))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->FieldNotebookAttachmentId = $this->l_addslashes($FieldNotebookAttachmentId);
       $this->dirty = true;
   }
/*TimestampCreated*/
   public function getTimestampCreated() {
       if ($this->TimestampCreated==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampCreated));
       }
   }
   public function setTimestampCreated($TimestampCreated) {
       if (strlen($TimestampCreated) > huh_fieldnotebookattachment::TIMESTAMPCREATED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampCreated = $this->l_addslashes($TimestampCreated);
       $this->dirty = true;
   }
/*TimestampModified*/
   public function getTimestampModified() {
       if ($this->TimestampModified==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampModified));
       }
   }
   public function setTimestampModified($TimestampModified) {
       if (strlen($TimestampModified) > huh_fieldnotebookattachment::TIMESTAMPMODIFIED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampModified = $this->l_addslashes($TimestampModified);
       $this->dirty = true;
   }
/*Version*/
   public function getVersion() {
       if ($this->Version==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Version));
       }
   }
   public function setVersion($Version) {
       if (strlen(preg_replace('/[^0-9]/','',$Version)) > huh_fieldnotebookattachment::VERSION_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Version = trim($Version);
       if (!ctype_digit(strval($Version)) && trim(strval($Version))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Version = $this->l_addslashes($Version);
       $this->dirty = true;
   }
/*Ordinal*/
   public function getOrdinal() {
       if ($this->Ordinal==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Ordinal));
       }
   }
   public function setOrdinal($Ordinal) {
       if (strlen(preg_replace('/[^0-9]/','',$Ordinal)) > huh_fieldnotebookattachment::ORDINAL_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Ordinal = trim($Ordinal);
       if (!ctype_digit(strval($Ordinal)) && trim(strval($Ordinal))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Ordinal = $this->l_addslashes($Ordinal);
       $this->dirty = true;
   }
/*Remarks*/
   public function getRemarks() {
       if ($this->Remarks==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Remarks));
       }
   }
   public function setRemarks($Remarks) {
       if (strlen($Remarks) > huh_fieldnotebookattachment::REMARKS_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Remarks = $this->l_addslashes($Remarks);
       $this->dirty = true;
   }
/*FieldNotebookID*/
   public function getFieldNotebookID() {
       if ($this->FieldNotebookID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->FieldNotebookID));
       }
   }
   public function setFieldNotebookID($FieldNotebookID) {
       if (strlen(preg_replace('/[^0-9]/','',$FieldNotebookID)) > huh_fieldnotebookattachment::FIELDNOTEBOOKID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $FieldNotebookID = trim($FieldNotebookID);
       if (!ctype_digit(strval($FieldNotebookID))) {
             throw new Exception("Value must be an integer");
       }
       $this->FieldNotebookID = $this->l_addslashes($FieldNotebookID);
       $this->dirty = true;
   }
/*CreatedByAgentID*/
   public function getCreatedByAgentID() {
       if ($this->CreatedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->CreatedByAgentID));
       }
   }
   public function setCreatedByAgentID($CreatedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$CreatedByAgentID)) > huh_fieldnotebookattachment::CREATEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $CreatedByAgentID = trim($CreatedByAgentID);
       if (!ctype_digit(strval($CreatedByAgentID)) && trim(strval($CreatedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->CreatedByAgentID = $this->l_addslashes($CreatedByAgentID);
       $this->dirty = true;
   }
/*ModifiedByAgentID*/
   public function getModifiedByAgentID() {
       if ($this->ModifiedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ModifiedByAgentID));
       }
   }
   public function setModifiedByAgentID($ModifiedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$ModifiedByAgentID)) > huh_fieldnotebookattachment::MODIFIEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ModifiedByAgentID = trim($ModifiedByAgentID);
       if (!ctype_digit(strval($ModifiedByAgentID)) && trim(strval($ModifiedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ModifiedByAgentID = $this->l_addslashes($ModifiedByAgentID);
       $this->dirty = true;
   }
/*AttachmentID*/
   public function getAttachmentID() {
       if ($this->AttachmentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->AttachmentID));
       }
   }
   public function setAttachmentID($AttachmentID) {
       if (strlen(preg_replace('/[^0-9]/','',$AttachmentID)) > huh_fieldnotebookattachment::ATTACHMENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $AttachmentID = trim($AttachmentID);
       if (!ctype_digit(strval($AttachmentID))) {
             throw new Exception("Value must be an integer");
       }
       $this->AttachmentID = $this->l_addslashes($AttachmentID);
       $this->dirty = true;
   }
   public function PK() { // get value of primary key 
        $returnvalue = '';
        $returnvalue .= $this->getFieldNotebookAttachmentId();
        return $returnvalue;
   }
   public function PKArray() { // get name and value of primary key fields 
        $returnvalue = array();
        $returnvalue['FieldNotebookAttachmentId'] = $this->getFieldNotebookAttachmentId();
        return $returnvalue;
   }
   public function NumberOfPrimaryKeyFields() { // returns the number of primary key fields defined for this table 
        return 1;
   }

   // Constants holding the mysqli field type character (s,i,d) for each field
  const C_FieldNotebookAttachmentIdMYSQLI_TYPE = 'i';
  const C_TimestampCreatedMYSQLI_TYPE = 's';
  const C_TimestampModifiedMYSQLI_TYPE = 's';
  const C_VersionMYSQLI_TYPE = 'i';
  const C_OrdinalMYSQLI_TYPE = 'i';
  const C_RemarksMYSQLI_TYPE = 's';
  const C_FieldNotebookIDMYSQLI_TYPE = 'i';
  const C_CreatedByAgentIDMYSQLI_TYPE = 'i';
  const C_ModifiedByAgentIDMYSQLI_TYPE = 'i';
  const C_AttachmentIDMYSQLI_TYPE = 'i';

   // function to obtain the mysqli field type character from a fieldname
   public function MySQLiFieldType($aFieldname) { 
      $retval = '';
      if ($aFieldname=='FieldNotebookAttachmentId') { $retval = self::C_FieldNotebookAttachmentIdMYSQLI_TYPE; }
      if ($aFieldname=='TimestampCreated') { $retval = self::C_TimestampCreatedMYSQLI_TYPE; }
      if ($aFieldname=='TimestampModified') { $retval = self::C_TimestampModifiedMYSQLI_TYPE; }
      if ($aFieldname=='Version') { $retval = self::C_VersionMYSQLI_TYPE; }
      if ($aFieldname=='Ordinal') { $retval = self::C_OrdinalMYSQLI_TYPE; }
      if ($aFieldname=='Remarks') { $retval = self::C_RemarksMYSQLI_TYPE; }
      if ($aFieldname=='FieldNotebookID') { $retval = self::C_FieldNotebookIDMYSQLI_TYPE; }
      if ($aFieldname=='CreatedByAgentID') { $retval = self::C_CreatedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='ModifiedByAgentID') { $retval = self::C_ModifiedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='AttachmentID') { $retval = self::C_AttachmentIDMYSQLI_TYPE; }
      return $retval;
   }

   // Function load() can take either the value of the primary key which uniquely identifies a particular row
   // or an array of array('primarykeyfieldname'=>'value') in the case of a single field primary key
   // or an array of fieldname value pairs in the case of multiple field primary key.
   public function load($pk) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        try {
             if (is_array($pk)) { 
                 $this->setFieldNotebookAttachmentId($pk[FieldNotebookAttachmentId]);
             } else { ;
                 $this->setFieldNotebookAttachmentId($pk);
             };
        } 
        catch (Exception $e) { 
             throw new Exception($e->getMessage());
        }
        if($this->FieldNotebookAttachmentId != NULL) {
           $sql = 'SELECT FieldNotebookAttachmentId, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, FieldNotebookID, CreatedByAgentID, ModifiedByAgentID, AttachmentID FROM fieldnotebookattachment WHERE FieldNotebookAttachmentId = '.$this->FieldNotebookAttachmentId ;

           $preparesql = 'SELECT FieldNotebookAttachmentId, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, FieldNotebookID, CreatedByAgentID, ModifiedByAgentID, AttachmentID FROM fieldnotebookattachment WHERE FieldNotebookAttachmentId = ? ';

           if ($statement = $connection->prepare($preparesql)) { 
              $statement->bind_param("i", $this->FieldNotebookAttachmentId);
              $statement->execute();
              $statement->bind_result($this->FieldNotebookAttachmentId, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Ordinal, $this->Remarks, $this->FieldNotebookID, $this->CreatedByAgentID, $this->ModifiedByAgentID, $this->AttachmentID);
              $statement->fetch();
              $statement->close();
           }

            $this->loaded = true;
            $this->dirty = false;
        } else { 
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   // Function save() will either save the current record or insert a new record.
   // Inserts new record if the primary key field in this table is null 
   // for this instance of this object.
   // Otherwise updates the record identified by the primary key value.
   public function save() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        // Test to see if this is an insert or update.
        if ($this->FieldNotebookAttachmentId!= NULL) {
            $sql  = 'UPDATE  fieldnotebookattachment SET ';
            $isInsert = false;
            $sql .=  "TimestampCreated = ? ";
            $sql .=  ", TimestampModified = ? ";
            $sql .=  ", Version = ? ";
            $sql .=  ", Ordinal = ? ";
            $sql .=  ", Remarks = ? ";
            $sql .=  ", FieldNotebookID = ? ";
            $sql .=  ", CreatedByAgentID = ? ";
            $sql .=  ", ModifiedByAgentID = ? ";
            $sql .=  ", AttachmentID = ? ";

            $sql .= "  WHERE FieldNotebookAttachmentId = ? ";
        } else {
            $sql  = 'INSERT INTO fieldnotebookattachment ';
            $isInsert = true;
if ($this->PK==NULL) { throw new Exception('Can\'t insert record with null primary key for this table'); }
            $sql .= '( FieldNotebookAttachmentId ,  TimestampCreated ,  TimestampModified ,  Version ,  Ordinal ,  Remarks ,  FieldNotebookID ,  CreatedByAgentID ,  ModifiedByAgentID ,  AttachmentID ) VALUES (';
            $sql .=  "  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .= ')';

        }
        if ($statement = $connection->prepare($sql)) { 
           if ($this->FieldNotebookAttachmentId!= NULL ) {
              $statement->bind_param("issiisiiiii", $this->FieldNotebookAttachmentId , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->Ordinal , $this->Remarks , $this->FieldNotebookID , $this->CreatedByAgentID , $this->ModifiedByAgentID , $this->AttachmentID , $this->FieldNotebookAttachmentId );
           } else { 
              $statement->bind_param("issiisiiii", $this->FieldNotebookAttachmentId , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->Ordinal , $this->Remarks , $this->FieldNotebookID , $this->CreatedByAgentID , $this->ModifiedByAgentID , $this->AttachmentID );
           } 
           $statement->execute();
           if ($statement->num_rows()!=1) {
               $this->error = $statement->error; 
           }
           $statement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }
        if ($this->error=='') { 
            $returnvalue = true;
        };

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function delete() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        if($this->FieldNotebookAttachmentId != NULL) {
           $sql = 'SELECT FieldNotebookAttachmentId, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, FieldNotebookID, CreatedByAgentID, ModifiedByAgentID, AttachmentID FROM fieldnotebookattachment WHERE FieldNotebookAttachmentId = "'.$this->FieldNotebookAttachmentId.'"  ' ;

           $preparedsql = 'SELECT  FROM fieldnotebookattachment WHERE  and FieldNotebookAttachmentId = ?  ' ;
        if ($statement = $connection->prepare($preparedsql)) { 
           $statement->bind_param("issiisiiii", $this->FieldNotebookAttachmentId, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Ordinal, $this->Remarks, $this->FieldNotebookID, $this->CreatedByAgentID, $this->ModifiedByAgentID, $this->AttachmentID);
           $statement->execute();
           $statement->store_result();
           if ($statement->num_rows()==1) {
                $sql = 'DELETE FROM fieldnotebookattachment WHERE  and FieldNotebookAttachmentId = ?  ';
                if ($stmt_delete = $connection->prepare($sql)) { 
                   $stmt_delete->bind_param("issiisiiii", $this->FieldNotebookAttachmentId, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Ordinal, $this->Remarks, $this->FieldNotebookID, $this->CreatedByAgentID, $this->ModifiedByAgentID, $this->AttachmentID);
                   if ($stmnt_delete->execute()) { 
                       $returnvalue = true;
                   } else {
                       $this->error = mysqli_error($connection); 
                   }
                   $stmt_delete->close();
                }
           } else { 
               $this->error = mysqli_error($connection); 
           }
           $tatement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }

            $this->loaded = true;
            // record was deleted, so set PK to null
            $this->FieldNotebookAttachmentId = NULL; 
        } else { 
           throw new Exception('Unable to identify which record to delete, primary key is not set');
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function count() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        $sql = 'SELECT count(*)  FROM fieldnotebookattachment';
        if ($result = $connection->query($sql)) { 
           if ($result->num_rows()==1) {
             $row = $result->fetch_row();
             if ($row) {
                $returnvalue = $row[0];
             }
           }
        } else { 
           $this->error = mysqli_error($connection); 
        }
        mysqli_free_result($result);

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function loadArrayKeyValueSearch($searchTermArray) {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = array();
       $and = '';
       $wherebit = 'WHERE ';
       foreach($searchTermArray as $fieldname => $searchTerm) {
           if ($this->hasField($fieldname)) { 
               $operator = '='; 
               // change to a like search if a wildcard character is present
               if (!(strpos($searchTerm,'%')===false)) { $operator = 'like'; }
               if (!(strpos($searchTerm,'_')===false)) { $operator = 'like'; }
               if ($searchTerm=='[NULL]') { 
                   $wherebit .= "$and ($fieldname is null or $fieldname='') "; 
               } else { 
                   $wherebit .= "$and $fieldname $operator ? ";
                   $types = $types . $this->MySQLiFieldType($fieldname);
               } 
               $and = ' and ';
           }
       }
       $sql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment $wherebit";
       if ($wherebit=='') { 
             $this->error = 'Error: No search terms provided';
       } else {
          $statement = $connection->prepare($sql);
          $vars = Array();
          $vars[] = $types;
          $i = 0;
          foreach ($searchTermArray as $value) { 
               $varname = 'bind'.$i;  // create a variable name
               $$varname = $value;    // using that variable name store the value 
               $vars[] = &$$varname;  // add a reference to the variable to the array
               $i++;
           }
           //$vars[] contains $types followed by references to variables holding each value in $searchTermArray.
          call_user_func_array(array($statement,'bind_param'),$vars);
          //$statement->bind_param($types,$names);
          $statement->execute();
          $statement->bind_result($id);
          $ids = array();
          while ($statement->fetch()) {
              $ids[] = $id;
          } // double loop to allow all data to be retrieved before preparing a new statement. 
          $statement->close();
          for ($i=0;$i<count($ids);$i++) {
              $obj = new huh_fieldnotebookattachment();
              $obj->load($ids[$i]);
              $returnvalue[] = $obj;
              $result=true;
          }
          if ($result===false) { $this->error = mysqli_error($connection); }
       }
       return $returnvalue;
   }	

   //---------------------------------------------------------------------------

// TODO: *************** link to related tables 

   //---------------------------------------------------------------------------

  public function loadLinkedTo() { 
     $returnvalue = array(); 
       // fk: FieldNotebookID
      $t = new fieldnotebook();
      $t->load(getFieldNotebookID());
      $returnvalue[FieldNotebookID] = $t;
       // fk: CreatedByAgentID
      $t = new agent();
      $t->load(getCreatedByAgentID());
      $returnvalue[CreatedByAgentID] = $t;
       // fk: ModifiedByAgentID
      $t = new agent();
      $t->load(getModifiedByAgentID());
      $returnvalue[ModifiedByAgentID] = $t;
       // fk: AttachmentID
      $t = new attachment();
      $t->load(getAttachmentID());
      $returnvalue[AttachmentID] = $t;
     return $returnvalue;
  } 
   // Returns an array of primary key values (id) and concatenated values of all other fields (fields)
   // wrapped as $values in: '{ "identifier":"id", "items": [ '.$values.' ] }';
   // when druid_handler.php is called with druid_action=returnfkjson
   // Used with dojo dijit.form.FilteringSelect to submit surrogate numeric key values from a text picklist 
   public function keySelectAllConcatJSON($orderby='ASC') {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
       $returnvalue = '';
       $order = '';
       if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
       $sql = "SELECT FieldNotebookAttachmentId, concat(IFNULL(TimestampCreated,'') || ' ' || IFNULL(TimestampModified,'') || ' ' || IFNULL(Version,'') || ' ' || IFNULL(Ordinal,'') || ' ' || IFNULL(Remarks,'') || ' ' || IFNULL(FieldNotebookID,'') || ' ' || IFNULL(CreatedByAgentID,'') || ' ' || IFNULL(ModifiedByAgentID,'') || ' ' || IFNULL(AttachmentID,'')) FROM fieldnotebookattachment order by FieldNotebookID, CreatedByAgentID, ModifiedByAgentID, AttachmentID $order ";
       $comma = '';
       if ($result = $connection->query($sql)) { 
          while ($row = $result->fetch_row()) {
             if ($row) {
                $pkval = trim($row[0]);
                $fval = trim($row[1]);
                if ($pkval!='') { 
                    $pkval = str_replace('"','&quot;',$pkval);
                    $fval = str_replace('"','&quot;',$fval);
                    $returnvalue .= $comma . ' { "id":"'.$pkval.'", "fields": "'.$fval.'" } ';
                    $comma = ', ';
                }
             }
          }
       } else { 
          $this->error = mysqli_error(); 
       }
       $result->close();
       return $returnvalue;
   }
   //---------------------------------------------------------------------------

   public function keySelectDistinctJSON($field,$orderby='ASC') {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = '';
       if ($this->hasField($field)) { 
          $order = '';
          $fieldesc = mysql_escape_string($field);
          if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
          $preparemysql = "SELECT DISTINCT $fieldesc FROM fieldnotebookattachment order by $fieldesc $order ";
          $comma = '';
         if ($stmt = $connection->prepare($preparemysql)) { 
             $stmt->execute();
             $stmt->bind_result($val);
             while ($stmt->fetch()) {
                $val = trim($val);                if ($val!='') { 
                    $val = str_replace('"','&quot;',$val);
                    $returnvalue .= $comma . ' { "'.$field.'":"'.$val.'" } ';
                    $comma = ', ';
                 }
             }
             $stmt->close();
         }
       }
       return $returnvalue;
   }
   //---------------------------------------------------------------------------


   //---------------------------------------------------------------------------

   // Each field with an index has a load array method generated for it.
   public function loadArrayByFieldNotebookID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE FieldNotebookID $operator '$searchTerm'";
        $preparedsql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE FieldNotebookID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_fieldnotebookattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByCreatedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE CreatedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE CreatedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_fieldnotebookattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByModifiedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE ModifiedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE ModifiedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_fieldnotebookattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByAttachmentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE AttachmentID $operator '$searchTerm'";
        $preparedsql = "SELECT FieldNotebookAttachmentId FROM fieldnotebookattachment WHERE AttachmentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_fieldnotebookattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }

   //---------------------------------------------------------------------------

   // Each fulltext index has a load array method generated for it.

   //---------------------------------------------------------------------------

   // Each field with an index has a select distinct method generated for it.
   public function selectDistinctFieldNotebookID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' FieldNotebookID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, FieldNotebookID FROM fieldnotebookattachment group by FieldNotebookID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&FieldNotebookID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' CreatedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, CreatedByAgentID FROM fieldnotebookattachment group by CreatedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&CreatedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ModifiedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ModifiedByAgentID FROM fieldnotebookattachment group by ModifiedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ModifiedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctAttachmentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' AttachmentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, AttachmentID FROM fieldnotebookattachment group by AttachmentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&AttachmentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }

   public function keySelectDistinct($fieldname,$startline,$link,$endline,$includecount=false,$orderbycount=false) {
       $returnvalue = '';
       switch ($fieldname) { 
          case 'FieldNotebookID':
             $returnvalue = $this->selectDistinctFieldNotebookID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'CreatedByAgentID':
             $returnvalue = $this->selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'ModifiedByAgentID':
             $returnvalue = $this->selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'AttachmentID':
             $returnvalue = $this->selectDistinctAttachmentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
       }
       return $returnvalue;
    }

   //---------------------------------------------------------------------------

   public function hasField($fieldname) {
       $returnvalue = false;
       if (trim($fieldname)!='' && trim($fieldname)!=',') {
            if (strpos(self::FIELDLIST," $fieldname, ")!==false) { 
               $returnvalue = true;
            }
       }
       return $returnvalue;
    }
   //---------------------------------------------------------------------------

}


// Write your own views by extending this class.
// Place your extended views in a separate file and you
// can use Druid to regenerate the fieldnotebookattachment.php file to reflect changes
// in the underlying database without overwriting your custom views of the data.
// 
class huh_fieldnotebookattachmentView implements viewer
{
   var $model = null;
   public function setModel($aModel) { 
       $this->model = $aModel;
   }
   // @param $includeRelated default true shows rows from other tables through foreign key relationships.
   // @param $editLinkURL default '' allows adding a link to show this record in an editing form.
   public function getDetailsView($includeRelated=true, $editLinkURL='') {
       $returnvalue = '<ul>';
       $editLinkURL=trim($editLinkURL);
       $model = $this->model;
       $primarykeys = $model->schemaPK();
       if ($editLinkURL!='') { 
          if (!preg_match('/\&$/',$editLinkURL)) { $editLinkURL .= '&'; } 
          $nullpk = false; 
          foreach ($primarykeys as $primarykey) { 
              // Add fieldname=value pairs for primary key(s) to editLinkURL. 
              $editLinkURL .= urlencode($primarykey) . '=' . urlencode($model->keyGet($primarykey));
              if ($model->keyGet($primarykey)=='') { $nullpk = true; } 
          }
          if (!$nullpk) { $returnvalue .= "<li>huh_fieldnotebookattachment <a href='$editLinkURL'>Edit</a></li>\n";  } 
       }
       $returnvalue .= "<li>".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID.": ".$model->getFieldNotebookAttachmentId()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::TIMESTAMPCREATED.": ".$model->getTimestampCreated()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::TIMESTAMPMODIFIED.": ".$model->getTimestampModified()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::VERSION.": ".$model->getVersion()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::ORDINAL.": ".$model->getOrdinal()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::REMARKS.": ".$model->getRemarks()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::FIELDNOTEBOOKID.": ".$model->getFieldNotebookID()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::CREATEDBYAGENTID.": ".$model->getCreatedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::MODIFIEDBYAGENTID.": ".$model->getModifiedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_fieldnotebookattachment::ATTACHMENTID.": ".$model->getAttachmentID()."</li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
           $returnvalue .= "<li>fieldnotebook</li>";
           $t_fieldnotebook = new huh_fieldnotebook();
           $t_fieldnotebookView = new huh_fieldnotebookView();
           $t_fieldnotebookView->setModel($t_fieldnotebook);
           if ($model->getFieldNotebookID() != '') { 
               $t_fieldnotebook->load($model->getFieldNotebookID());
               $returnvalue .= $t_fieldnotebookView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getCreatedByAgentID() != '') { 
               $t_agent->load($model->getCreatedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getModifiedByAgentID() != '') { 
               $t_agent->load($model->getModifiedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>attachment</li>";
           $t_attachment = new huh_attachment();
           $t_attachmentView = new huh_attachmentView();
           $t_attachmentView->setModel($t_attachment);
           if ($model->getAttachmentID() != '') { 
               $t_attachment->load($model->getAttachmentID());
               $returnvalue .= $t_attachmentView->getDetailsView(false);
           }

        }
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getJSON() {
       $returnvalue = '{ ';
       $model = $this->model;
       $returnvalue .= '"'.huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID.': "'.$model->getFieldNotebookAttachmentId().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::TIMESTAMPCREATED.': "'.$model->getTimestampCreated().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::TIMESTAMPMODIFIED.': "'.$model->getTimestampModified().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::VERSION.': "'.$model->getVersion().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::ORDINAL.': "'.$model->getOrdinal().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::REMARKS.': "'.$model->getRemarks().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::FIELDNOTEBOOKID.': "'.$model->getFieldNotebookID().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::CREATEDBYAGENTID.': "'.$model->getCreatedByAgentID().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::MODIFIEDBYAGENTID.': "'.$model->getModifiedByAgentID().'",';
       $returnvalue .= '"'.huh_fieldnotebookattachment::ATTACHMENTID.': "'.$model->getAttachmentID().'" }';
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getTableRowView() {
       $returnvalue = '<tr>';
       $model = $this->model;
       $returnvalue .= "<td>".$model->getFieldNotebookAttachmentId()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampCreated()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampModified()."</td>\n";
       $returnvalue .= "<td>".$model->getVersion()."</td>\n";
       $returnvalue .= "<td>".$model->getOrdinal()."</td>\n";
       $returnvalue .= "<td>".$model->getRemarks()."</td>\n";
       $returnvalue .= "<td>".$model->getFieldNotebookID()."</td>\n";
       $returnvalue .= "<td>".$model->getCreatedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getModifiedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getAttachmentID()."</td>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getHeaderRow() {
       $returnvalue = '<tr>';
       $returnvalue .= "<th>".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::TIMESTAMPCREATED."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::TIMESTAMPMODIFIED."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::VERSION."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::ORDINAL."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::REMARKS."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::FIELDNOTEBOOKID."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::CREATEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::MODIFIEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_fieldnotebookattachment::ATTACHMENTID."</th>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getEditFormDojoView($includeRelated=true) {
       $model = $this->model;
       if ($model->PK()=='') { $addform=true; } else { $addform=false; } 
       $returnvalue = '';
       $id = trim($model->PK());
       $feedback = "status$id";
       $formname = "editform$id";
       $script = '
  var saveprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function save'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Saving...";
     dojo.xhrGet(saveprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_fieldnotebookattachment">';
       $returnvalue .= "<div id='div_$formnane' >";
       if($addform) { 
          $returnvalue .= "Add a new FieldNotebookAttachmentId"; 
       } else { 
         $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID.">FIELDNOTEBOOKATTACHMENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID." id=".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID." value='".$model->getFieldNotebookAttachmentId()."'  style=' width:".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID_SIZE ."' ></div>\n";
       }  
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::TIMESTAMPCREATED.">TIMESTAMPCREATED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_fieldnotebookattachment::TIMESTAMPCREATED." id=".huh_fieldnotebookattachment::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  style=' width:".huh_fieldnotebookattachment::TIMESTAMPCREATED_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::TIMESTAMPCREATED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::TIMESTAMPMODIFIED.">TIMESTAMPMODIFIED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_fieldnotebookattachment::TIMESTAMPMODIFIED." id=".huh_fieldnotebookattachment::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  style=' width:".huh_fieldnotebookattachment::TIMESTAMPMODIFIED_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::TIMESTAMPMODIFIED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::VERSION.">VERSION</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::VERSION." id=".huh_fieldnotebookattachment::VERSION." value='".$model->getVersion()."'  style=' width:".huh_fieldnotebookattachment::VERSION_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::VERSION_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::ORDINAL.">ORDINAL</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::ORDINAL." id=".huh_fieldnotebookattachment::ORDINAL." value='".$model->getOrdinal()."'  style=' width:".huh_fieldnotebookattachment::ORDINAL_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::ORDINAL_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::REMARKS.">REMARKS</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_fieldnotebookattachment::REMARKS." id=".huh_fieldnotebookattachment::REMARKS." >".$model->getRemarks()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::FIELDNOTEBOOKID.">FIELDNOTEBOOKID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::FIELDNOTEBOOKID." id=".huh_fieldnotebookattachment::FIELDNOTEBOOKID." value='".$model->getFieldNotebookID()."'  style=' width:".huh_fieldnotebookattachment::FIELDNOTEBOOKID_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::FIELDNOTEBOOKID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::CREATEDBYAGENTID.">CREATEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::CREATEDBYAGENTID." id=".huh_fieldnotebookattachment::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  style=' width:".huh_fieldnotebookattachment::CREATEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::CREATEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::MODIFIEDBYAGENTID.">MODIFIEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::MODIFIEDBYAGENTID." id=".huh_fieldnotebookattachment::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  style=' width:".huh_fieldnotebookattachment::MODIFIEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::MODIFIEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_fieldnotebookattachment::ATTACHMENTID.">ATTACHMENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_fieldnotebookattachment::ATTACHMENTID." id=".huh_fieldnotebookattachment::ATTACHMENTID." value='".$model->getAttachmentID()."'  style=' width:".huh_fieldnotebookattachment::ATTACHMENTID_SIZE ."em;  '  maxlength='".huh_fieldnotebookattachment::ATTACHMENTID_SIZE ."' ></div>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= "<li><input name=save id=save type=button value='Save' onclick='$script  save$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</div>';
       $returnvalue .= '</form>';
       if(!$addform) { 
          // show delete button if editing an existing record 
       $id = trim($model->PK());
       $feedback = "deletestatus$id";
       $formname = "deleteform$id";
       $script = '
  var deleteprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function deleterecord'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Deleting...";
     dojo.xhrGet(deleteprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=delete>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_table value="huh_fieldnotebookattachment">';
       $returnvalue .= '<input type=hidden name=FieldNotebookAttachmentId id=druid_table value="'.$id.'">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li><input name=delete id=save type=button value='Delete' onclick='$script  deleterecord$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       } 
       return  $returnvalue;
   }
   public function getEditFormView($includeRelated=true) {
       $model = $this->model;
       $returnvalue = '<form method=get action=druid_handler.php>';
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_fieldnotebookattachment">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li>FIELDNOTEBOOKATTACHMENTID<input type=text name=".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID." id=".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID." value='".$model->getFieldNotebookAttachmentId()."'  size='".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID_SIZE ."'  maxlength='".huh_fieldnotebookattachment::FIELDNOTEBOOKATTACHMENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPCREATED<input type=text name=".huh_fieldnotebookattachment::TIMESTAMPCREATED." id=".huh_fieldnotebookattachment::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  size='".huh_fieldnotebookattachment::TIMESTAMPCREATED_SIZE ."'  maxlength='".huh_fieldnotebookattachment::TIMESTAMPCREATED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPMODIFIED<input type=text name=".huh_fieldnotebookattachment::TIMESTAMPMODIFIED." id=".huh_fieldnotebookattachment::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  size='".huh_fieldnotebookattachment::TIMESTAMPMODIFIED_SIZE ."'  maxlength='".huh_fieldnotebookattachment::TIMESTAMPMODIFIED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VERSION<input type=text name=".huh_fieldnotebookattachment::VERSION." id=".huh_fieldnotebookattachment::VERSION." value='".$model->getVersion()."'  size='".huh_fieldnotebookattachment::VERSION_SIZE ."'  maxlength='".huh_fieldnotebookattachment::VERSION_SIZE ."' ></li>\n";
       $returnvalue .= "<li>ORDINAL<input type=text name=".huh_fieldnotebookattachment::ORDINAL." id=".huh_fieldnotebookattachment::ORDINAL." value='".$model->getOrdinal()."'  size='".huh_fieldnotebookattachment::ORDINAL_SIZE ."'  maxlength='".huh_fieldnotebookattachment::ORDINAL_SIZE ."' ></li>\n";
       $returnvalue .= "<li>REMARKS<input type=text name=".huh_fieldnotebookattachment::REMARKS." id=".huh_fieldnotebookattachment::REMARKS." value='".$model->getRemarks()."'  size='51'  maxlength='".huh_fieldnotebookattachment::REMARKS_SIZE ."' ></li>\n";
       $returnvalue .= "<li>FIELDNOTEBOOKID<input type=text name=".huh_fieldnotebookattachment::FIELDNOTEBOOKID." id=".huh_fieldnotebookattachment::FIELDNOTEBOOKID." value='".$model->getFieldNotebookID()."'  size='".huh_fieldnotebookattachment::FIELDNOTEBOOKID_SIZE ."'  maxlength='".huh_fieldnotebookattachment::FIELDNOTEBOOKID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>CREATEDBYAGENTID<input type=text name=".huh_fieldnotebookattachment::CREATEDBYAGENTID." id=".huh_fieldnotebookattachment::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  size='".huh_fieldnotebookattachment::CREATEDBYAGENTID_SIZE ."'  maxlength='".huh_fieldnotebookattachment::CREATEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>MODIFIEDBYAGENTID<input type=text name=".huh_fieldnotebookattachment::MODIFIEDBYAGENTID." id=".huh_fieldnotebookattachment::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  size='".huh_fieldnotebookattachment::MODIFIEDBYAGENTID_SIZE ."'  maxlength='".huh_fieldnotebookattachment::MODIFIEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>ATTACHMENTID<input type=text name=".huh_fieldnotebookattachment::ATTACHMENTID." id=".huh_fieldnotebookattachment::ATTACHMENTID." value='".$model->getAttachmentID()."'  size='".huh_fieldnotebookattachment::ATTACHMENTID_SIZE ."'  maxlength='".huh_fieldnotebookattachment::ATTACHMENTID_SIZE ."' ></li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= '<li><input type=submit value="Save"></li>';
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       return  $returnvalue;
   }
}

//==============================================================================
?>
