<?php
//==============================================================================
//===   agentattachment.php                         
//===   Autogenerated by Druid from MySQL db Build:6
//==============================================================================

include_once("druid_interfaces.php");

class huh_agentattachment implements  model , loadableModel, saveableModel, tableSchema 
{
   // These constants hold the sizes the fields in this table in the database.
   const AGENTATTACHMENTID_SIZE = 11; //INTEGER
   const TIMESTAMPCREATED_SIZE = 21; //TIMESTAMP
   const TIMESTAMPMODIFIED_SIZE = 21; //TIMESTAMP
   const VERSION_SIZE         = 11; //INTEGER
   const ORDINAL_SIZE         = 11; //INTEGER
   const REMARKS_SIZE         = 255; //LONGVARCHAR
   const AGENTID_SIZE         = 11; //INTEGER
   const MODIFIEDBYAGENTID_SIZE = 11; //INTEGER
   const ATTACHMENTID_SIZE    = 11; //INTEGER
   const CREATEDBYAGENTID_SIZE = 11; //INTEGER
    // These constants hold the field names of the table in the database. 
   const AGENTATTACHMENTID = 'AgentAttachmentID';
   const TIMESTAMPCREATED  = 'TimestampCreated';
   const TIMESTAMPMODIFIED = 'TimestampModified';
   const VERSION           = 'Version';
   const ORDINAL           = 'Ordinal';
   const REMARKS           = 'Remarks';
   const AGENTID           = 'AgentID';
   const MODIFIEDBYAGENTID = 'ModifiedByAgentID';
   const ATTACHMENTID      = 'AttachmentID';
   const CREATEDBYAGENTID  = 'CreatedByAgentID';

   //---------------------------------------------------------------------------

   // interface tableSchema implementation
   // schemaPK returns array of primary key field names
   public function schemaPK() {
       return $this->primaryKeyArray;
   } 
   // schemaHaveDistinct returns array of field names for which selectDistinct{fieldname} methods are available.
   public function schemaHaveDistinct() {
       return $this->selectDistinctFieldsArray;
   } 
   // schemaFields returns array of all field names
   public function schemaFields() { 
       return $this->allFieldsArray;
   } 
/*  Example sanitized retrieval of variable matching object variables from $_GET 
/*  Customize these to limit each variable to narrowest possible set of known good values. 

  $AgentAttachmentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['AgentAttachmentID']), 0, 11);
  $TimestampCreated = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampCreated']), 0, 21);
  $TimestampModified = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['TimestampModified']), 0, 21);
  $Version = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Version']), 0, 11);
  $Ordinal = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['Ordinal']), 0, 11);
  $Remarks = substr(preg_replace('/[^A-Za-z0-9\.\.\ \[NULL\]]/','',$_GET['Remarks']), 0, 255);
  $AgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['AgentID']), 0, 11);
  $ModifiedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['ModifiedByAgentID']), 0, 11);
  $AttachmentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['AttachmentID']), 0, 11);
  $CreatedByAgentID = substr(preg_replace('/[^0-9\-\[NULL\]]/','',$_GET['CreatedByAgentID']), 0, 11);
*/

   //---------------------------------------------------------------------------

   private $AgentAttachmentID; // PK INTEGER 
   private $TimestampCreated; // TIMESTAMP 
   private $TimestampModified; // TIMESTAMP 
   private $Version; // INTEGER 
   private $Ordinal; // INTEGER 
   private $Remarks; // LONGVARCHAR 
   private $AgentID; // INTEGER 
   private $ModifiedByAgentID; // INTEGER 
   private $AttachmentID; // INTEGER 
   private $CreatedByAgentID; // INTEGER 
   private $dirty;
   private $loaded;
   private $error;
   const FIELDLIST = ' AgentAttachmentID, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, AgentID, ModifiedByAgentID, AttachmentID, CreatedByAgentID, ';
   const PKFIELDLIST = ' AgentAttachmentID, ';
   const NUMBER_OF_PRIMARY_KEYS = 1;
   private $primaryKeyArray = array( 1 => 'AgentAttachmentID'  ) ;
   private $allFieldsArray = array( 0 => 'AgentAttachmentID' , 1 => 'TimestampCreated' , 2 => 'TimestampModified' , 3 => 'Version' , 4 => 'Ordinal' , 5 => 'Remarks' , 6 => 'AgentID' , 7 => 'ModifiedByAgentID' , 8 => 'AttachmentID' , 9 => 'CreatedByAgentID'  ) ;
   private $selectDistinctFieldsArray = array( 6 => 'AgentID' , 7 => 'ModifiedByAgentID' , 8 => 'AttachmentID' , 9 => 'CreatedByAgentID'  ) ;

   //---------------------------------------------------------------------------

   // constructor 
   function huh_agentattachment(){
       $this->AgentAttachmentID = NULL;
       $this->TimestampCreated = '';
       $this->TimestampModified = '';
       $this->Version = '';
       $this->Ordinal = '';
       $this->Remarks = '';
       $this->AgentID = '';
       $this->ModifiedByAgentID = '';
       $this->AttachmentID = '';
       $this->CreatedByAgentID = '';
       $this->dirty = false;
       $this->loaded = false;
       $this->error = '';
   }

   private function l_addslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = addslashes($value);
      }
      return $retval;
   }
   private function l_stripslashes($value) {
      $retval = $value;
      if (!get_magic_quotes_gpc()) {
          $retval = stripslashes($value);
      }
      return $retval;
   }
   public function isDirty() {
       return $this->dirty;
   }
   public function isLoaded() {
       return $this->loaded;
   }
   public function errorMessage() {
       return $this->error;
   }

   //---------------------------------------------------------------------------

   public function keyValueSet($fieldname,$value) {
       $returnvalue = false;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='AgentAttachmentID') { $returnvalue = $this->setAgentAttachmentID($value); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->setTimestampCreated($value); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->setTimestampModified($value); } 
             if ($fieldname=='Version') { $returnvalue = $this->setVersion($value); } 
             if ($fieldname=='Ordinal') { $returnvalue = $this->setOrdinal($value); } 
             if ($fieldname=='Remarks') { $returnvalue = $this->setRemarks($value); } 
             if ($fieldname=='AgentID') { $returnvalue = $this->setAgentID($value); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->setModifiedByAgentID($value); } 
             if ($fieldname=='AttachmentID') { $returnvalue = $this->setAttachmentID($value); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->setCreatedByAgentID($value); } 
             $returnvalue = true;
          }
          catch (exception $e) { ;
              $returnvalue = false;
              throw new Exception('Field Set Error'.$e->getMessage()); 
          }
       } else { 
          throw new Exception('No Such field'); 
       }  
       return $returnvalue;
   }
   public function keyGet($fieldname) {
       $returnvalue = null;
       if ($this->hasField($fieldname)) { 
          try {
             if ($fieldname=='AgentAttachmentID') { $returnvalue = $this->getAgentAttachmentID(); } 
             if ($fieldname=='TimestampCreated') { $returnvalue = $this->getTimestampCreated(); } 
             if ($fieldname=='TimestampModified') { $returnvalue = $this->getTimestampModified(); } 
             if ($fieldname=='Version') { $returnvalue = $this->getVersion(); } 
             if ($fieldname=='Ordinal') { $returnvalue = $this->getOrdinal(); } 
             if ($fieldname=='Remarks') { $returnvalue = $this->getRemarks(); } 
             if ($fieldname=='AgentID') { $returnvalue = $this->getAgentID(); } 
             if ($fieldname=='ModifiedByAgentID') { $returnvalue = $this->getModifiedByAgentID(); } 
             if ($fieldname=='AttachmentID') { $returnvalue = $this->getAttachmentID(); } 
             if ($fieldname=='CreatedByAgentID') { $returnvalue = $this->getCreatedByAgentID(); } 
          }
          catch (exception $e) { ;
              $returnvalue = null;
          }
       }
       return $returnvalue;
   }
/*AgentAttachmentID*/
   public function getAgentAttachmentID() {
       if ($this->AgentAttachmentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->AgentAttachmentID));
       }
   }
   public function setAgentAttachmentID($AgentAttachmentID) {
       if (strlen(preg_replace('/[^0-9]/','',$AgentAttachmentID)) > huh_agentattachment::AGENTATTACHMENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $AgentAttachmentID = trim($AgentAttachmentID);
       if (!ctype_digit(strval($AgentAttachmentID)) && trim(strval($AgentAttachmentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->AgentAttachmentID = $this->l_addslashes($AgentAttachmentID);
       $this->dirty = true;
   }
/*TimestampCreated*/
   public function getTimestampCreated() {
       if ($this->TimestampCreated==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampCreated));
       }
   }
   public function setTimestampCreated($TimestampCreated) {
       if (strlen($TimestampCreated) > huh_agentattachment::TIMESTAMPCREATED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampCreated = $this->l_addslashes($TimestampCreated);
       $this->dirty = true;
   }
/*TimestampModified*/
   public function getTimestampModified() {
       if ($this->TimestampModified==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->TimestampModified));
       }
   }
   public function setTimestampModified($TimestampModified) {
       if (strlen($TimestampModified) > huh_agentattachment::TIMESTAMPMODIFIED_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->TimestampModified = $this->l_addslashes($TimestampModified);
       $this->dirty = true;
   }
/*Version*/
   public function getVersion() {
       if ($this->Version==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Version));
       }
   }
   public function setVersion($Version) {
       if (strlen(preg_replace('/[^0-9]/','',$Version)) > huh_agentattachment::VERSION_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Version = trim($Version);
       if (!ctype_digit(strval($Version)) && trim(strval($Version))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Version = $this->l_addslashes($Version);
       $this->dirty = true;
   }
/*Ordinal*/
   public function getOrdinal() {
       if ($this->Ordinal==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Ordinal));
       }
   }
   public function setOrdinal($Ordinal) {
       if (strlen(preg_replace('/[^0-9]/','',$Ordinal)) > huh_agentattachment::ORDINAL_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $Ordinal = trim($Ordinal);
       if (!ctype_digit(strval($Ordinal)) && trim(strval($Ordinal))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->Ordinal = $this->l_addslashes($Ordinal);
       $this->dirty = true;
   }
/*Remarks*/
   public function getRemarks() {
       if ($this->Remarks==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->Remarks));
       }
   }
   public function setRemarks($Remarks) {
       if (strlen($Remarks) > huh_agentattachment::REMARKS_SIZE) { 
           throw new Exception('Value exceeds field length.');
       } 
       $this->Remarks = $this->l_addslashes($Remarks);
       $this->dirty = true;
   }
/*AgentID*/
   public function getAgentID() {
       if ($this->AgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->AgentID));
       }
   }
   public function setAgentID($AgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$AgentID)) > huh_agentattachment::AGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $AgentID = trim($AgentID);
       if (!ctype_digit(strval($AgentID))) {
             throw new Exception("Value must be an integer");
       }
       $this->AgentID = $this->l_addslashes($AgentID);
       $this->dirty = true;
   }
/*ModifiedByAgentID*/
   public function getModifiedByAgentID() {
       if ($this->ModifiedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->ModifiedByAgentID));
       }
   }
   public function setModifiedByAgentID($ModifiedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$ModifiedByAgentID)) > huh_agentattachment::MODIFIEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $ModifiedByAgentID = trim($ModifiedByAgentID);
       if (!ctype_digit(strval($ModifiedByAgentID)) && trim(strval($ModifiedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->ModifiedByAgentID = $this->l_addslashes($ModifiedByAgentID);
       $this->dirty = true;
   }
/*AttachmentID*/
   public function getAttachmentID() {
       if ($this->AttachmentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->AttachmentID));
       }
   }
   public function setAttachmentID($AttachmentID) {
       if (strlen(preg_replace('/[^0-9]/','',$AttachmentID)) > huh_agentattachment::ATTACHMENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $AttachmentID = trim($AttachmentID);
       if (!ctype_digit(strval($AttachmentID))) {
             throw new Exception("Value must be an integer");
       }
       $this->AttachmentID = $this->l_addslashes($AttachmentID);
       $this->dirty = true;
   }
/*CreatedByAgentID*/
   public function getCreatedByAgentID() {
       if ($this->CreatedByAgentID==null) { 
          return null;
       } else { ;
          return trim($this->l_stripslashes($this->CreatedByAgentID));
       }
   }
   public function setCreatedByAgentID($CreatedByAgentID) {
       if (strlen(preg_replace('/[^0-9]/','',$CreatedByAgentID)) > huh_agentattachment::CREATEDBYAGENTID_SIZE) { 
           throw new Exception('Value has too many digits for the field length.');
       } 
       $CreatedByAgentID = trim($CreatedByAgentID);
       if (!ctype_digit(strval($CreatedByAgentID)) && trim(strval($CreatedByAgentID))!='' ) {
             throw new Exception("Value must be an integer");
       }
       $this->CreatedByAgentID = $this->l_addslashes($CreatedByAgentID);
       $this->dirty = true;
   }
   public function PK() { // get value of primary key 
        $returnvalue = '';
        $returnvalue .= $this->getAgentAttachmentID();
        return $returnvalue;
   }
   public function PKArray() { // get name and value of primary key fields 
        $returnvalue = array();
        $returnvalue['AgentAttachmentID'] = $this->getAgentAttachmentID();
        return $returnvalue;
   }
   public function NumberOfPrimaryKeyFields() { // returns the number of primary key fields defined for this table 
        return 1;
   }

   // Constants holding the mysqli field type character (s,i,d) for each field
  const C_AgentAttachmentIDMYSQLI_TYPE = 'i';
  const C_TimestampCreatedMYSQLI_TYPE = 's';
  const C_TimestampModifiedMYSQLI_TYPE = 's';
  const C_VersionMYSQLI_TYPE = 'i';
  const C_OrdinalMYSQLI_TYPE = 'i';
  const C_RemarksMYSQLI_TYPE = 's';
  const C_AgentIDMYSQLI_TYPE = 'i';
  const C_ModifiedByAgentIDMYSQLI_TYPE = 'i';
  const C_AttachmentIDMYSQLI_TYPE = 'i';
  const C_CreatedByAgentIDMYSQLI_TYPE = 'i';

   // function to obtain the mysqli field type character from a fieldname
   public function MySQLiFieldType($aFieldname) { 
      $retval = '';
      if ($aFieldname=='AgentAttachmentID') { $retval = self::C_AgentAttachmentIDMYSQLI_TYPE; }
      if ($aFieldname=='TimestampCreated') { $retval = self::C_TimestampCreatedMYSQLI_TYPE; }
      if ($aFieldname=='TimestampModified') { $retval = self::C_TimestampModifiedMYSQLI_TYPE; }
      if ($aFieldname=='Version') { $retval = self::C_VersionMYSQLI_TYPE; }
      if ($aFieldname=='Ordinal') { $retval = self::C_OrdinalMYSQLI_TYPE; }
      if ($aFieldname=='Remarks') { $retval = self::C_RemarksMYSQLI_TYPE; }
      if ($aFieldname=='AgentID') { $retval = self::C_AgentIDMYSQLI_TYPE; }
      if ($aFieldname=='ModifiedByAgentID') { $retval = self::C_ModifiedByAgentIDMYSQLI_TYPE; }
      if ($aFieldname=='AttachmentID') { $retval = self::C_AttachmentIDMYSQLI_TYPE; }
      if ($aFieldname=='CreatedByAgentID') { $retval = self::C_CreatedByAgentIDMYSQLI_TYPE; }
      return $retval;
   }

   // Function load() can take either the value of the primary key which uniquely identifies a particular row
   // or an array of array('primarykeyfieldname'=>'value') in the case of a single field primary key
   // or an array of fieldname value pairs in the case of multiple field primary key.
   public function load($pk) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        try {
             if (is_array($pk)) { 
                 $this->setAgentAttachmentID($pk[AgentAttachmentID]);
             } else { ;
                 $this->setAgentAttachmentID($pk);
             };
        } 
        catch (Exception $e) { 
             throw new Exception($e->getMessage());
        }
        if($this->AgentAttachmentID != NULL) {
           $sql = 'SELECT AgentAttachmentID, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, AgentID, ModifiedByAgentID, AttachmentID, CreatedByAgentID FROM agentattachment WHERE AgentAttachmentID = '.$this->AgentAttachmentID ;

           $preparesql = 'SELECT AgentAttachmentID, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, AgentID, ModifiedByAgentID, AttachmentID, CreatedByAgentID FROM agentattachment WHERE AgentAttachmentID = ? ';

           if ($statement = $connection->prepare($preparesql)) { 
              $statement->bind_param("i", $this->AgentAttachmentID);
              $statement->execute();
              $statement->bind_result($this->AgentAttachmentID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Ordinal, $this->Remarks, $this->AgentID, $this->ModifiedByAgentID, $this->AttachmentID, $this->CreatedByAgentID);
              $statement->fetch();
              $statement->close();
           }

            $this->loaded = true;
            $this->dirty = false;
        } else { 
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   // Function save() will either save the current record or insert a new record.
   // Inserts new record if the primary key field in this table is null 
   // for this instance of this object.
   // Otherwise updates the record identified by the primary key value.
   public function save() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        // Test to see if this is an insert or update.
        if ($this->AgentAttachmentID!= NULL) {
            $sql  = 'UPDATE  agentattachment SET ';
            $isInsert = false;
            $sql .=  "TimestampCreated = ? ";
            $sql .=  ", TimestampModified = ? ";
            $sql .=  ", Version = ? ";
            $sql .=  ", Ordinal = ? ";
            $sql .=  ", Remarks = ? ";
            $sql .=  ", AgentID = ? ";
            $sql .=  ", ModifiedByAgentID = ? ";
            $sql .=  ", AttachmentID = ? ";
            $sql .=  ", CreatedByAgentID = ? ";

            $sql .= "  WHERE AgentAttachmentID = ? ";
        } else {
            $sql  = 'INSERT INTO agentattachment ';
            $isInsert = true;
if ($this->PK==NULL) { throw new Exception('Can\'t insert record with null primary key for this table'); }
            $sql .= '( AgentAttachmentID ,  TimestampCreated ,  TimestampModified ,  Version ,  Ordinal ,  Remarks ,  AgentID ,  ModifiedByAgentID ,  AttachmentID ,  CreatedByAgentID ) VALUES (';
            $sql .=  "  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .=  " ,  ? ";
            $sql .= ')';

        }
        if ($statement = $connection->prepare($sql)) { 
           if ($this->AgentAttachmentID!= NULL ) {
              $statement->bind_param("issiisiiiii", $this->AgentAttachmentID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->Ordinal , $this->Remarks , $this->AgentID , $this->ModifiedByAgentID , $this->AttachmentID , $this->CreatedByAgentID , $this->AgentAttachmentID );
           } else { 
              $statement->bind_param("issiisiiii", $this->AgentAttachmentID , $this->TimestampCreated , $this->TimestampModified , $this->Version , $this->Ordinal , $this->Remarks , $this->AgentID , $this->ModifiedByAgentID , $this->AttachmentID , $this->CreatedByAgentID );
           } 
           $statement->execute();
           if ($statement->num_rows()!=1) {
               $this->error = $statement->error; 
           }
           $statement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }
        if ($this->error=='') { 
            $returnvalue = true;
        };

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function delete() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        if($this->AgentAttachmentID != NULL) {
           $sql = 'SELECT AgentAttachmentID, TimestampCreated, TimestampModified, Version, Ordinal, Remarks, AgentID, ModifiedByAgentID, AttachmentID, CreatedByAgentID FROM agentattachment WHERE AgentAttachmentID = "'.$this->AgentAttachmentID.'"  ' ;

           $preparedsql = 'SELECT  FROM agentattachment WHERE  and AgentAttachmentID = ?  ' ;
        if ($statement = $connection->prepare($preparedsql)) { 
           $statement->bind_param("issiisiiii", $this->AgentAttachmentID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Ordinal, $this->Remarks, $this->AgentID, $this->ModifiedByAgentID, $this->AttachmentID, $this->CreatedByAgentID);
           $statement->execute();
           $statement->store_result();
           if ($statement->num_rows()==1) {
                $sql = 'DELETE FROM agentattachment WHERE  and AgentAttachmentID = ?  ';
                if ($stmt_delete = $connection->prepare($sql)) { 
                   $stmt_delete->bind_param("issiisiiii", $this->AgentAttachmentID, $this->TimestampCreated, $this->TimestampModified, $this->Version, $this->Ordinal, $this->Remarks, $this->AgentID, $this->ModifiedByAgentID, $this->AttachmentID, $this->CreatedByAgentID);
                   if ($stmnt_delete->execute()) { 
                       $returnvalue = true;
                   } else {
                       $this->error = mysqli_error($connection); 
                   }
                   $stmt_delete->close();
                }
           } else { 
               $this->error = mysqli_error($connection); 
           }
           $tatement->close();
        } else { 
            $this->error = mysqli_error($connection); 
        }

            $this->loaded = true;
            // record was deleted, so set PK to null
            $this->AgentAttachmentID = NULL; 
        } else { 
           throw new Exception('Unable to identify which record to delete, primary key is not set');
        }
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function count() {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = false;
        $sql = 'SELECT count(*)  FROM agentattachment';
        if ($result = $connection->query($sql)) { 
           if ($result->num_rows()==1) {
             $row = $result->fetch_row();
             if ($row) {
                $returnvalue = $row[0];
             }
           }
        } else { 
           $this->error = mysqli_error($connection); 
        }
        mysqli_free_result($result);

        $this->loaded = true;
        return $returnvalue;
    }
   //---------------------------------------------------------------------------

   public function loadArrayKeyValueSearch($searchTermArray) {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = array();
       $and = '';
       $wherebit = 'WHERE ';
       foreach($searchTermArray as $fieldname => $searchTerm) {
           if ($this->hasField($fieldname)) { 
               $operator = '='; 
               // change to a like search if a wildcard character is present
               if (!(strpos($searchTerm,'%')===false)) { $operator = 'like'; }
               if (!(strpos($searchTerm,'_')===false)) { $operator = 'like'; }
               if ($searchTerm=='[NULL]') { 
                   $wherebit .= "$and ($fieldname is null or $fieldname='') "; 
               } else { 
                   $wherebit .= "$and $fieldname $operator ? ";
                   $types = $types . $this->MySQLiFieldType($fieldname);
               } 
               $and = ' and ';
           }
       }
       $sql = "SELECT AgentAttachmentID FROM agentattachment $wherebit";
       if ($wherebit=='') { 
             $this->error = 'Error: No search terms provided';
       } else {
          $statement = $connection->prepare($sql);
          $vars = Array();
          $vars[] = $types;
          $i = 0;
          foreach ($searchTermArray as $value) { 
               $varname = 'bind'.$i;  // create a variable name
               $$varname = $value;    // using that variable name store the value 
               $vars[] = &$$varname;  // add a reference to the variable to the array
               $i++;
           }
           //$vars[] contains $types followed by references to variables holding each value in $searchTermArray.
          call_user_func_array(array($statement,'bind_param'),$vars);
          //$statement->bind_param($types,$names);
          $statement->execute();
          $statement->bind_result($id);
          $ids = array();
          while ($statement->fetch()) {
              $ids[] = $id;
          } // double loop to allow all data to be retrieved before preparing a new statement. 
          $statement->close();
          for ($i=0;$i<count($ids);$i++) {
              $obj = new huh_agentattachment();
              $obj->load($ids[$i]);
              $returnvalue[] = $obj;
              $result=true;
          }
          if ($result===false) { $this->error = mysqli_error($connection); }
       }
       return $returnvalue;
   }	

   //---------------------------------------------------------------------------

// TODO: *************** link to related tables 

   //---------------------------------------------------------------------------

  public function loadLinkedTo() { 
     $returnvalue = array(); 
       // fk: AgentID
      $t = new agent();
      $t->load(getAgentID());
      $returnvalue[AgentID] = $t;
       // fk: ModifiedByAgentID
      $t = new agent();
      $t->load(getModifiedByAgentID());
      $returnvalue[ModifiedByAgentID] = $t;
       // fk: AttachmentID
      $t = new attachment();
      $t->load(getAttachmentID());
      $returnvalue[AttachmentID] = $t;
       // fk: CreatedByAgentID
      $t = new agent();
      $t->load(getCreatedByAgentID());
      $returnvalue[CreatedByAgentID] = $t;
     return $returnvalue;
  } 
   // Returns an array of primary key values (id) and concatenated values of all other fields (fields)
   // wrapped as $values in: '{ "identifier":"id", "items": [ '.$values.' ] }';
   // when druid_handler.php is called with druid_action=returnfkjson
   // Used with dojo dijit.form.FilteringSelect to submit surrogate numeric key values from a text picklist 
   public function keySelectAllConcatJSON($orderby='ASC') {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
       $returnvalue = '';
       $order = '';
       if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
       $sql = "SELECT AgentAttachmentID, concat(IFNULL(TimestampCreated,'') || ' ' || IFNULL(TimestampModified,'') || ' ' || IFNULL(Version,'') || ' ' || IFNULL(Ordinal,'') || ' ' || IFNULL(Remarks,'') || ' ' || IFNULL(AgentID,'') || ' ' || IFNULL(ModifiedByAgentID,'') || ' ' || IFNULL(AttachmentID,'') || ' ' || IFNULL(CreatedByAgentID,'')) FROM agentattachment order by AgentID, ModifiedByAgentID, AttachmentID, CreatedByAgentID $order ";
       $comma = '';
       if ($result = $connection->query($sql)) { 
          while ($row = $result->fetch_row()) {
             if ($row) {
                $pkval = trim($row[0]);
                $fval = trim($row[1]);
                if ($pkval!='') { 
                    $pkval = str_replace('"','&quot;',$pkval);
                    $fval = str_replace('"','&quot;',$fval);
                    $returnvalue .= $comma . ' { "id":"'.$pkval.'", "fields": "'.$fval.'" } ';
                    $comma = ', ';
                }
             }
          }
       } else { 
          $this->error = mysqli_error(); 
       }
       $result->close();
       return $returnvalue;
   }
   //---------------------------------------------------------------------------

   public function keySelectDistinctJSON($field,$orderby='ASC') {
       // ******* Note: $connection must be a mysqli object.
       global $connection;
       $returnvalue = '';
       if ($this->hasField($field)) { 
          $order = '';
          $fieldesc = mysql_escape_string($field);
          if ($orderby=='ASC') { $order = 'ASC'; } else { $order = 'DESC'; } 
          $preparemysql = "SELECT DISTINCT $fieldesc FROM agentattachment order by $fieldesc $order ";
          $comma = '';
         if ($stmt = $connection->prepare($preparemysql)) { 
             $stmt->execute();
             $stmt->bind_result($val);
             while ($stmt->fetch()) {
                $val = trim($val);                if ($val!='') { 
                    $val = str_replace('"','&quot;',$val);
                    $returnvalue .= $comma . ' { "'.$field.'":"'.$val.'" } ';
                    $comma = ', ';
                 }
             }
             $stmt->close();
         }
       }
       return $returnvalue;
   }
   //---------------------------------------------------------------------------


   //---------------------------------------------------------------------------

   // Each field with an index has a load array method generated for it.
   public function loadArrayByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentAttachmentID FROM agentattachment WHERE AgentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentAttachmentID FROM agentattachment WHERE AgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByModifiedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentAttachmentID FROM agentattachment WHERE ModifiedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentAttachmentID FROM agentattachment WHERE ModifiedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByAttachmentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentAttachmentID FROM agentattachment WHERE AttachmentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentAttachmentID FROM agentattachment WHERE AttachmentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }
   public function loadArrayByCreatedByAgentID($searchTerm) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = array();
        $operator = "=";
        // change to a like search if a wildcard character is present
        if (!(strpos($searchTerm,"%")===false)) { $operator = "like"; }
        if (!(strpos($searchTerm,"_")===false)) { $operator = "like"; }
        $sql = "SELECT AgentAttachmentID FROM agentattachment WHERE CreatedByAgentID $operator '$searchTerm'";
        $preparedsql = "SELECT AgentAttachmentID FROM agentattachment WHERE CreatedByAgentID $operator ? ";
        if ($statement = $connection->prepare($preparedsql)) { 
            $statement->bind_param("s", $searchTerm);
            $statement->execute();
            $statement->bind_result($id);
            while ($statement->fetch()) { ;
                $obj = new huh_agentattachment();
                $obj->load($id);
                $returnvalue[] = $obj;
            }
            $statement->close();
        }
        return $returnvalue;
   }

   //---------------------------------------------------------------------------

   // Each fulltext index has a load array method generated for it.

   //---------------------------------------------------------------------------

   // Each field with an index has a select distinct method generated for it.
   public function selectDistinctAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' AgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, AgentID FROM agentattachment group by AgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&AgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' ModifiedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, ModifiedByAgentID FROM agentattachment group by ModifiedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&ModifiedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctAttachmentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' AttachmentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, AttachmentID FROM agentattachment group by AttachmentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&AttachmentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }
   public function selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount=false,$orderbycount=false) {
        // ******* Note: $connection must be a mysqli object.
        global $connection;
        $returnvalue = '';
        $order = ' CreatedByAgentID ';
        if ($orderbycount) { $order = ' druid_ct DESC '; } 
        $sql = "SELECT count(*) as druid_ct, CreatedByAgentID FROM agentattachment group by CreatedByAgentID order by $order ";
        if ($result = $connection->query($sql)) { 
           while ($row = $result->fetch_row()) {
              if ($row) {
                  $count = $row[0];
                  $val = $row[1];
                  $escaped = urlencode($row[1]);
                  if ($val=='') {
                     $val = '[NULL]'; 
                     $escaped = urlencode('[NULL]');
                  }
                  if ($link=='') { 
                     $returnvalue .= "$startline$val&nbsp;($count)$endline";
                  } else { 
                     $returnvalue .= "$startline<a href='$link&CreatedByAgentID=$escaped'>$val</a>&nbsp;($count)$endline";
                  }
              }
           }
           $result->close();
        }
        return $returnvalue;
    }

   public function keySelectDistinct($fieldname,$startline,$link,$endline,$includecount=false,$orderbycount=false) {
       $returnvalue = '';
       switch ($fieldname) { 
          case 'AgentID':
             $returnvalue = $this->selectDistinctAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'ModifiedByAgentID':
             $returnvalue = $this->selectDistinctModifiedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'AttachmentID':
             $returnvalue = $this->selectDistinctAttachmentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
          case 'CreatedByAgentID':
             $returnvalue = $this->selectDistinctCreatedByAgentID($startline,$link,$endline,$includecount,$orderbycount);
             break;
       }
       return $returnvalue;
    }

   //---------------------------------------------------------------------------

   public function hasField($fieldname) {
       $returnvalue = false;
       if (trim($fieldname)!='' && trim($fieldname)!=',') {
            if (strpos(self::FIELDLIST," $fieldname, ")!==false) { 
               $returnvalue = true;
            }
       }
       return $returnvalue;
    }
   //---------------------------------------------------------------------------

}


// Write your own views by extending this class.
// Place your extended views in a separate file and you
// can use Druid to regenerate the agentattachment.php file to reflect changes
// in the underlying database without overwriting your custom views of the data.
// 
class huh_agentattachmentView implements viewer
{
   var $model = null;
   public function setModel($aModel) { 
       $this->model = $aModel;
   }
   // @param $includeRelated default true shows rows from other tables through foreign key relationships.
   // @param $editLinkURL default '' allows adding a link to show this record in an editing form.
   public function getDetailsView($includeRelated=true, $editLinkURL='') {
       $returnvalue = '<ul>';
       $editLinkURL=trim($editLinkURL);
       $model = $this->model;
       $primarykeys = $model->schemaPK();
       if ($editLinkURL!='') { 
          if (!preg_match('/\&$/',$editLinkURL)) { $editLinkURL .= '&'; } 
          $nullpk = false; 
          foreach ($primarykeys as $primarykey) { 
              // Add fieldname=value pairs for primary key(s) to editLinkURL. 
              $editLinkURL .= urlencode($primarykey) . '=' . urlencode($model->keyGet($primarykey));
              if ($model->keyGet($primarykey)=='') { $nullpk = true; } 
          }
          if (!$nullpk) { $returnvalue .= "<li>huh_agentattachment <a href='$editLinkURL'>Edit</a></li>\n";  } 
       }
       $returnvalue .= "<li>".huh_agentattachment::AGENTATTACHMENTID.": ".$model->getAgentAttachmentID()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::TIMESTAMPCREATED.": ".$model->getTimestampCreated()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::TIMESTAMPMODIFIED.": ".$model->getTimestampModified()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::VERSION.": ".$model->getVersion()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::ORDINAL.": ".$model->getOrdinal()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::REMARKS.": ".$model->getRemarks()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::AGENTID.": ".$model->getAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::MODIFIEDBYAGENTID.": ".$model->getModifiedByAgentID()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::ATTACHMENTID.": ".$model->getAttachmentID()."</li>\n";
       $returnvalue .= "<li>".huh_agentattachment::CREATEDBYAGENTID.": ".$model->getCreatedByAgentID()."</li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getAgentID() != '') { 
               $t_agent->load($model->getAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getModifiedByAgentID() != '') { 
               $t_agent->load($model->getModifiedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }
           $returnvalue .= "<li>attachment</li>";
           $t_attachment = new huh_attachment();
           $t_attachmentView = new huh_attachmentView();
           $t_attachmentView->setModel($t_attachment);
           if ($model->getAttachmentID() != '') { 
               $t_attachment->load($model->getAttachmentID());
               $returnvalue .= $t_attachmentView->getDetailsView(false);
           }
           $returnvalue .= "<li>agent</li>";
           $t_agent = new huh_agent();
           $t_agentView = new huh_agentView();
           $t_agentView->setModel($t_agent);
           if ($model->getCreatedByAgentID() != '') { 
               $t_agent->load($model->getCreatedByAgentID());
               $returnvalue .= $t_agentView->getDetailsView(false);
           }

        }
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getJSON() {
       $returnvalue = '{ ';
       $model = $this->model;
       $returnvalue .= '"'.huh_agentattachment::AGENTATTACHMENTID.': "'.$model->getAgentAttachmentID().'",';
       $returnvalue .= '"'.huh_agentattachment::TIMESTAMPCREATED.': "'.$model->getTimestampCreated().'",';
       $returnvalue .= '"'.huh_agentattachment::TIMESTAMPMODIFIED.': "'.$model->getTimestampModified().'",';
       $returnvalue .= '"'.huh_agentattachment::VERSION.': "'.$model->getVersion().'",';
       $returnvalue .= '"'.huh_agentattachment::ORDINAL.': "'.$model->getOrdinal().'",';
       $returnvalue .= '"'.huh_agentattachment::REMARKS.': "'.$model->getRemarks().'",';
       $returnvalue .= '"'.huh_agentattachment::AGENTID.': "'.$model->getAgentID().'",';
       $returnvalue .= '"'.huh_agentattachment::MODIFIEDBYAGENTID.': "'.$model->getModifiedByAgentID().'",';
       $returnvalue .= '"'.huh_agentattachment::ATTACHMENTID.': "'.$model->getAttachmentID().'",';
       $returnvalue .= '"'.huh_agentattachment::CREATEDBYAGENTID.': "'.$model->getCreatedByAgentID().'" }';
       $returnvalue .= '</ul>';
       return  $returnvalue;
   }
   public function getTableRowView() {
       $returnvalue = '<tr>';
       $model = $this->model;
       $returnvalue .= "<td>".$model->getAgentAttachmentID()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampCreated()."</td>\n";
       $returnvalue .= "<td>".$model->getTimestampModified()."</td>\n";
       $returnvalue .= "<td>".$model->getVersion()."</td>\n";
       $returnvalue .= "<td>".$model->getOrdinal()."</td>\n";
       $returnvalue .= "<td>".$model->getRemarks()."</td>\n";
       $returnvalue .= "<td>".$model->getAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getModifiedByAgentID()."</td>\n";
       $returnvalue .= "<td>".$model->getAttachmentID()."</td>\n";
       $returnvalue .= "<td>".$model->getCreatedByAgentID()."</td>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getHeaderRow() {
       $returnvalue = '<tr>';
       $returnvalue .= "<th>".huh_agentattachment::AGENTATTACHMENTID."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::TIMESTAMPCREATED."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::TIMESTAMPMODIFIED."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::VERSION."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::ORDINAL."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::REMARKS."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::AGENTID."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::MODIFIEDBYAGENTID."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::ATTACHMENTID."</th>\n";
       $returnvalue .= "<th>".huh_agentattachment::CREATEDBYAGENTID."</th>\n";
       $returnvalue .= '</tr>';
       return  $returnvalue;
   }
   public function getEditFormDojoView($includeRelated=true) {
       $model = $this->model;
       if ($model->PK()=='') { $addform=true; } else { $addform=false; } 
       $returnvalue = '';
       $id = trim($model->PK());
       $feedback = "status$id";
       $formname = "editform$id";
       $script = '
  var saveprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function save'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Saving...";
     dojo.xhrGet(saveprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_agentattachment">';
       $returnvalue .= "<div id='div_$formnane' >";
       if($addform) { 
          $returnvalue .= "Add a new AgentAttachmentID"; 
       } else { 
         $returnvalue .= "<div><label for=".huh_agentattachment::AGENTATTACHMENTID.">AGENTATTACHMENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::AGENTATTACHMENTID." id=".huh_agentattachment::AGENTATTACHMENTID." value='".$model->getAgentAttachmentID()."'  style=' width:".huh_agentattachment::AGENTATTACHMENTID_SIZE ."em;  '  maxlength='".huh_agentattachment::AGENTATTACHMENTID_SIZE ."' ></div>\n";
       }  
       $returnvalue .= "<div><label for=".huh_agentattachment::TIMESTAMPCREATED.">TIMESTAMPCREATED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentattachment::TIMESTAMPCREATED." id=".huh_agentattachment::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  style=' width:".huh_agentattachment::TIMESTAMPCREATED_SIZE ."em;  '  maxlength='".huh_agentattachment::TIMESTAMPCREATED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::TIMESTAMPMODIFIED.">TIMESTAMPMODIFIED</label><input  dojoType='dijit.form.ValidationTextBox'  name=".huh_agentattachment::TIMESTAMPMODIFIED." id=".huh_agentattachment::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  style=' width:".huh_agentattachment::TIMESTAMPMODIFIED_SIZE ."em;  '  maxlength='".huh_agentattachment::TIMESTAMPMODIFIED_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::VERSION.">VERSION</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::VERSION." id=".huh_agentattachment::VERSION." value='".$model->getVersion()."'  style=' width:".huh_agentattachment::VERSION_SIZE ."em;  '  maxlength='".huh_agentattachment::VERSION_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::ORDINAL.">ORDINAL</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::ORDINAL." id=".huh_agentattachment::ORDINAL." value='".$model->getOrdinal()."'  style=' width:".huh_agentattachment::ORDINAL_SIZE ."em;  '  maxlength='".huh_agentattachment::ORDINAL_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::REMARKS.">REMARKS</label><textarea  dojoType='dijit.form.Textarea'  style=' width:51em; border:1px solid grey; '  name=".huh_agentattachment::REMARKS." id=".huh_agentattachment::REMARKS." >".$model->getRemarks()."</textarea></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::AGENTID.">AGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::AGENTID." id=".huh_agentattachment::AGENTID." value='".$model->getAgentID()."'  style=' width:".huh_agentattachment::AGENTID_SIZE ."em;  '  maxlength='".huh_agentattachment::AGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::MODIFIEDBYAGENTID.">MODIFIEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::MODIFIEDBYAGENTID." id=".huh_agentattachment::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  style=' width:".huh_agentattachment::MODIFIEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_agentattachment::MODIFIEDBYAGENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::ATTACHMENTID.">ATTACHMENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::ATTACHMENTID." id=".huh_agentattachment::ATTACHMENTID." value='".$model->getAttachmentID()."'  style=' width:".huh_agentattachment::ATTACHMENTID_SIZE ."em;  '  maxlength='".huh_agentattachment::ATTACHMENTID_SIZE ."' ></div>\n";
       $returnvalue .= "<div><label for=".huh_agentattachment::CREATEDBYAGENTID.">CREATEDBYAGENTID</label><input  dojoType='dijit.form.ValidationTextBox'  regExp='^[0-9-]*'  invalidMessage='The value entered is not valid.  It must be an integer.' name=".huh_agentattachment::CREATEDBYAGENTID." id=".huh_agentattachment::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  style=' width:".huh_agentattachment::CREATEDBYAGENTID_SIZE ."em;  '  maxlength='".huh_agentattachment::CREATEDBYAGENTID_SIZE ."' ></div>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= "<li><input name=save id=save type=button value='Save' onclick='$script  save$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</div>';
       $returnvalue .= '</form>';
       if(!$addform) { 
          // show delete button if editing an existing record 
       $id = trim($model->PK());
       $feedback = "deletestatus$id";
       $formname = "deleteform$id";
       $script = '
  var deleteprocessor'.$id.' = {
        form: dojo.byId("'.$formname.'"),
        url: "ajax_handler.php",
        handleAs: "text",
        load: function(data){
                dojo.byId("'.$feedback.'").innerHTML = data;
        },
        error: function(data){
                dojo.byId("'.$feedback.'").innerHTML = "Error: " + data;
                console.debug("Error: ", data);
        },
        timeout: 8000
  };
  function deleterecord'.$id.'() {
     dojo.byId("'.$feedback.'").innerHTML = "Deleting...";
     dojo.xhrGet(deleteprocessor'.$id.');
  };
       ';
       $returnvalue .= "<form id='$formname' name='$formname' dojoType='dijit.form.Form'>";
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=delete>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_table value="huh_agentattachment">';
       $returnvalue .= '<input type=hidden name=AgentAttachmentID id=druid_table value="'.$id.'">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li><input name=delete id=save type=button value='Delete' onclick='$script  deleterecord$id();'><div id='$feedback'></div></li>";
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       } 
       return  $returnvalue;
   }
   public function getEditFormView($includeRelated=true) {
       $model = $this->model;
       $returnvalue = '<form method=get action=druid_handler.php>';
       $returnvalue .= '<input type=hidden name=druid_action id=druid_action value=save>';
       $returnvalue .= '<input type=hidden name=druid_table id=druid_action value="huh_agentattachment">';
       $returnvalue .= '<ul>';
       $returnvalue .= "<li>AGENTATTACHMENTID<input type=text name=".huh_agentattachment::AGENTATTACHMENTID." id=".huh_agentattachment::AGENTATTACHMENTID." value='".$model->getAgentAttachmentID()."'  size='".huh_agentattachment::AGENTATTACHMENTID_SIZE ."'  maxlength='".huh_agentattachment::AGENTATTACHMENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPCREATED<input type=text name=".huh_agentattachment::TIMESTAMPCREATED." id=".huh_agentattachment::TIMESTAMPCREATED." value='".$model->getTimestampCreated()."'  size='".huh_agentattachment::TIMESTAMPCREATED_SIZE ."'  maxlength='".huh_agentattachment::TIMESTAMPCREATED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>TIMESTAMPMODIFIED<input type=text name=".huh_agentattachment::TIMESTAMPMODIFIED." id=".huh_agentattachment::TIMESTAMPMODIFIED." value='".$model->getTimestampModified()."'  size='".huh_agentattachment::TIMESTAMPMODIFIED_SIZE ."'  maxlength='".huh_agentattachment::TIMESTAMPMODIFIED_SIZE ."' ></li>\n";
       $returnvalue .= "<li>VERSION<input type=text name=".huh_agentattachment::VERSION." id=".huh_agentattachment::VERSION." value='".$model->getVersion()."'  size='".huh_agentattachment::VERSION_SIZE ."'  maxlength='".huh_agentattachment::VERSION_SIZE ."' ></li>\n";
       $returnvalue .= "<li>ORDINAL<input type=text name=".huh_agentattachment::ORDINAL." id=".huh_agentattachment::ORDINAL." value='".$model->getOrdinal()."'  size='".huh_agentattachment::ORDINAL_SIZE ."'  maxlength='".huh_agentattachment::ORDINAL_SIZE ."' ></li>\n";
       $returnvalue .= "<li>REMARKS<input type=text name=".huh_agentattachment::REMARKS." id=".huh_agentattachment::REMARKS." value='".$model->getRemarks()."'  size='51'  maxlength='".huh_agentattachment::REMARKS_SIZE ."' ></li>\n";
       $returnvalue .= "<li>AGENTID<input type=text name=".huh_agentattachment::AGENTID." id=".huh_agentattachment::AGENTID." value='".$model->getAgentID()."'  size='".huh_agentattachment::AGENTID_SIZE ."'  maxlength='".huh_agentattachment::AGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>MODIFIEDBYAGENTID<input type=text name=".huh_agentattachment::MODIFIEDBYAGENTID." id=".huh_agentattachment::MODIFIEDBYAGENTID." value='".$model->getModifiedByAgentID()."'  size='".huh_agentattachment::MODIFIEDBYAGENTID_SIZE ."'  maxlength='".huh_agentattachment::MODIFIEDBYAGENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>ATTACHMENTID<input type=text name=".huh_agentattachment::ATTACHMENTID." id=".huh_agentattachment::ATTACHMENTID." value='".$model->getAttachmentID()."'  size='".huh_agentattachment::ATTACHMENTID_SIZE ."'  maxlength='".huh_agentattachment::ATTACHMENTID_SIZE ."' ></li>\n";
       $returnvalue .= "<li>CREATEDBYAGENTID<input type=text name=".huh_agentattachment::CREATEDBYAGENTID." id=".huh_agentattachment::CREATEDBYAGENTID." value='".$model->getCreatedByAgentID()."'  size='".huh_agentattachment::CREATEDBYAGENTID_SIZE ."'  maxlength='".huh_agentattachment::CREATEDBYAGENTID_SIZE ."' ></li>\n";
       if ($includeRelated) { 
           // note that $includeRelated is provided as false in calls out to
           // related tables to prevent infinite loops between related objects.
        }
       $returnvalue .= '<li><input type=submit value="Save"></li>';
       $returnvalue .= '</ul>';
       $returnvalue .= '</form>';
       return  $returnvalue;
   }
}

//==============================================================================
?>
